/**
 * @file nimcp_distributed_cognition_internal.h
 * @brief Internal shared declarations for nimcp_distributed_cognition SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_DISTRIBUTED_COGNITION_INTERNAL_H
#define NIMCP_DISTRIBUTED_COGNITION_INTERNAL_H

#include "networking/distributed/nimcp_distributed_cognition.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "utils/memory/nimcp_unified_memory.h"
#include "async/nimcp_future.h"
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_router.h"
#include "async/nimcp_bio_messages.h"
#include "utils/error/nimcp_error_codes.h"
#include "api/nimcp_api_exception.h"
#include "security/nimcp_security.h"
#include "utils/config/nimcp_dynamic_config.h"
#include "utils/thread/nimcp_thread.h"
#include "utils/time/nimcp_time.h"
#include "utils/validation/nimcp_validate.h"
#include "utils/validation/nimcp_common.h"
#include <string.h>
#include <math.h>
#include "utils/fault_tolerance/nimcp_health_agent_macros.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

//=============================================================================
// Internal Structures
//=============================================================================

/**
 * @brief Registered neuromodulator pool for synchronization
 */
typedef struct {
    neuromodulator_pool_t* pool;   /**< Local neuromod pool */
    uint64_t last_sync_time;        /**< Last sync timestamp */
    bool needs_broadcast;           /**< Flag for pending broadcast */
} registered_neuromod_t;

/**
 * @brief Registered glial integration system
 */
typedef struct {
    glial_integration_t* glial;    /**< Local glial system */
    uint64_t last_sync_time;        /**< Last sync timestamp */
    uint32_t pending_prunings;      /**< Pending pruning operations */
} registered_glial_t;

/**
 * @brief Registered brain region
 */
typedef struct {
    brain_region_t* region;        /**< Local brain region */
    uint16_t region_type;           /**< Region type identifier */
    uint64_t last_sync_time;        /**< Last sync timestamp */
} registered_region_t;

/**
 * @brief Distributed cognition coordinator (opaque struct)
 */
struct distrib_cognition_struct {
    // Configuration
    distrib_cognition_config_t config;

    // P2P network
    p2p_node_t p2p_node;

    // Registered systems
    registered_neuromod_t* neuromod_pools;
    size_t neuromod_pool_count;
    size_t neuromod_pool_capacity;

    registered_glial_t* glial_systems;
    size_t glial_system_count;
    size_t glial_system_capacity;

    registered_region_t* brain_regions;
    size_t brain_region_count;
    size_t brain_region_capacity;

    // Statistics
    distrib_cognition_stats_t stats;

    // Thread safety
    nimcp_rwlock_t rwlock;

    // Worker threads
    nimcp_thread_t neuromod_thread;
    nimcp_thread_t glial_thread;
    nimcp_thread_t region_thread;

    // Control flags
    bool running;
    bool shutdown_requested;

    // Bio-async integration
    bio_module_context_t bio_ctx;
    bool bio_async_enabled;
};

//=============================================================================
// Async Operations - Context Structures
//=============================================================================

/**
 * @brief Context for async neuromodulator broadcast
 */
typedef struct {
    distrib_cognition_t dc;
    neuromodulator_type_t type;
    float concentration;
    nimcp_promise_t promise;
} async_neuromod_broadcast_ctx_t;

/**
 * @brief Context for async calcium wave propagation
 */
typedef struct {
    distrib_cognition_t dc;
    uint32_t astrocyte_id;
    float calcium_level;
    float wave_velocity;
    nimcp_promise_t promise;
} async_calcium_wave_ctx_t;

/**
 * @brief Context for async pruning coordination
 */
typedef struct {
    distrib_cognition_t dc;
    uint32_t source_neuron_id;
    uint32_t target_neuron_id;
    float activity_score;
    uint8_t action;
    nimcp_promise_t promise;
} async_pruning_ctx_t;

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- lifecycle module --- */
/* distrib_cognition_create - defined in nimcp_distributed_cognition_lifecycle.c */
/* distrib_cognition_destroy - defined in nimcp_distributed_cognition_lifecycle.c */
/* distrib_cognition_start - defined in nimcp_distributed_cognition_lifecycle.c */
/* distrib_cognition_stop - defined in nimcp_distributed_cognition_lifecycle.c */
/* distrib_cognition_register_neuromod_pool - defined in nimcp_distributed_cognition_lifecycle.c */
/* distrib_cognition_broadcast_neuromod - defined in nimcp_distributed_cognition_lifecycle.c */
/* distrib_cognition_register_glial_system - defined in nimcp_distributed_cognition_lifecycle.c */

/* --- stats module --- */
/* distrib_cognition_get_stats - defined in nimcp_distributed_cognition_stats.c */

/* --- sync module --- */
/* distrib_cognition_set_sync_mode - defined in nimcp_distributed_cognition_sync.c */
/* distrib_cognition_propagate_calcium_wave - defined in nimcp_distributed_cognition_sync.c */
/* distrib_cognition_register_brain_region - defined in nimcp_distributed_cognition_sync.c */
/* distrib_cognition_broadcast_region_activity - defined in nimcp_distributed_cognition_sync.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_DISTRIBUTED_COGNITION_INTERNAL_H */
