/**
 * @file nimcp_neuromodulators_internal.h
 * @brief Internal shared declarations for nimcp_neuromodulators SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_NEUROMODULATORS_INTERNAL_H
#define NIMCP_NEUROMODULATORS_INTERNAL_H

#include "plasticity/neuromodulators/nimcp_neuromodulators.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include <stddef.h>  /* for NULL */
#include "plasticity/neuromodulators/nimcp_phasic_tonic.h"       // Phase C2.2 Enhancement #2
#include "plasticity/neuromodulators/nimcp_receptor_subtypes.h"  // Phase C2.2 Enhancement #1
#include "plasticity/neuromodulators/nimcp_vesicle_packaging.h"  // Phase C2.3 Enhancement #3
#include "plasticity/neuromodulators/nimcp_metabolic_pathways.h" // Phase C2.4 Enhancement #4
#include "plasticity/neuromodulators/nimcp_neuromodulators_sleep_bridge.h"  // Sleep integration
#include "cognitive/nimcp_sleep_wake.h"                          // Sleep state
#include "cognitive/nimcp_grief_and_loss.h"                      // Phase E1: Grief and Loss Understanding
#include "cognitive/nimcp_joy_euphoria.h"                        // Phase E2: Joy and Euphoria System Integration
#include "cognitive/nimcp_love_loyalty_friendship.h"             // Phase E4: Love, Loyalty, Friendship System Integration
#include "utils/validation/nimcp_validate.h"
#include "utils/thread/nimcp_thread.h"
#include "utils/platform/nimcp_platform_rwlock.h"
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_messages.h"
#include "async/nimcp_bio_router.h"
#include "async/nimcp_wiring_helpers.h"
#include "security/nimcp_security.h"
#include "utils/tensor/nimcp_tensor.h"
#include <math.h>
#include <string.h>
#include <stdatomic.h>
#include "utils/fault_tolerance/nimcp_health_agent_macros.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

//=============================================================================
// Bio-Async Integration State (Global for module registration)
//=============================================================================

/**
 * @brief Bio-async state for neuromodulator system
 *
 * WHAT: Global singleton state for bio-async integration
 * WHY:  Bio-router requires static module registration
 * HOW:  Registered once, routes messages to appropriate system instance
 */
typedef struct {
    bio_module_context_t module_ctx;        /**< Bio-router module context */
    neuromodulator_system_t current_system; /**< Currently active system (set by last create) */
    bool initialized;                       /**< Whether bio-async is initialized */
    atomic_uint_fast64_t messages_processed;/**< Message processing counter */
    nimcp_mutex_t init_mutex;             /**< Mutex protecting initialization */
    bool mutex_initialized;                 /**< Whether mutex is initialized */
} neuromod_bio_state_t;

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- acetylcholine module --- */
/* neuromodulator_release_acetylcholine - defined in nimcp_neuromodulators_acetylcholine.c */
/* neuromodulator_pool_get_acetylcholine - defined in nimcp_neuromodulators_acetylcholine.c */
/* neuromodulator_pool_set_acetylcholine - defined in nimcp_neuromodulators_acetylcholine.c */
/* modulation_effects_get_attention_weight - defined in nimcp_neuromodulators_acetylcholine.c */
/* modulation_effects_set_attention_weight - defined in nimcp_neuromodulators_acetylcholine.c */
/* neuromodulator_release_norepinephrine - defined in nimcp_neuromodulators_acetylcholine.c */
/* neuromodulator_compute_effects - defined in nimcp_neuromodulators_acetylcholine.c */
/* neuromodulator_pool_get_norepinephrine - defined in nimcp_neuromodulators_acetylcholine.c */
/* neuromodulator_pool_get_gaba - defined in nimcp_neuromodulators_acetylcholine.c */
/* neuromodulator_pool_set_norepinephrine - defined in nimcp_neuromodulators_acetylcholine.c */
/* neuromodulator_pool_set_gaba - defined in nimcp_neuromodulators_acetylcholine.c */
/* neuromodulator_pool_set_glutamate - defined in nimcp_neuromodulators_acetylcholine.c */
/* modulation_effects_get_transmission_gain - defined in nimcp_neuromodulators_acetylcholine.c */
/* modulation_effects_get_excitability_shift - defined in nimcp_neuromodulators_acetylcholine.c */
/* modulation_effects_set_learning_rate_multiplier - defined in nimcp_neuromodulators_acetylcholine.c */
/* modulation_effects_set_transmission_gain - defined in nimcp_neuromodulators_acetylcholine.c */
/* modulation_effects_set_excitability_shift - defined in nimcp_neuromodulators_acetylcholine.c */

/* --- dopamine module --- */
/* neuromodulator_release_dopamine - defined in nimcp_neuromodulators_dopamine.c */
/* neuromodulator_pool_get_dopamine - defined in nimcp_neuromodulators_dopamine.c */
/* neuromodulator_pool_set_dopamine - defined in nimcp_neuromodulators_dopamine.c */
/* neuromodulator_pool_get_glutamate - defined in nimcp_neuromodulators_dopamine.c */

/* --- integration module --- */
/* neuromodulator_modulate_learning_rate - defined in nimcp_neuromodulators_integration.c */
/* neuromodulator_modulate_transmission - defined in nimcp_neuromodulators_integration.c */
/* neuromodulator_modulate_threshold - defined in nimcp_neuromodulators_integration.c */
/* neuromodulator_profile_cortical_excitatory - defined in nimcp_neuromodulators_integration.c */
/* neuromodulator_profile_cortical_inhibitory - defined in nimcp_neuromodulators_integration.c */
/* neuromodulator_profile_hippocampal - defined in nimcp_neuromodulators_integration.c */
/* neuromodulator_profile_striatal - defined in nimcp_neuromodulators_integration.c */
/* neuromodulator_profile_amygdala - defined in nimcp_neuromodulators_integration.c */
/* neuromodulator_release_from_ethics - defined in nimcp_neuromodulators_integration.c */

/* --- lifecycle module --- */
/* neuromodulator_system_create - defined in nimcp_neuromodulators_lifecycle.c */
/* neuromodulator_system_destroy - defined in nimcp_neuromodulators_lifecycle.c */
/* neuromodulator_reset - defined in nimcp_neuromodulators_lifecycle.c */
/* neuromodulator_pool_create - defined in nimcp_neuromodulators_lifecycle.c */
/* neuromodulator_pool_destroy - defined in nimcp_neuromodulators_lifecycle.c */
/* receptor_profile_create - defined in nimcp_neuromodulators_lifecycle.c */
/* receptor_profile_destroy - defined in nimcp_neuromodulators_lifecycle.c */
/* modulation_effects_create - defined in nimcp_neuromodulators_lifecycle.c */
/* modulation_effects_destroy - defined in nimcp_neuromodulators_lifecycle.c */
/* neuromodulator_bio_async_process - defined in nimcp_neuromodulators_lifecycle.c */
/* neuromodulator_connect_brain - defined in nimcp_neuromodulators_lifecycle.c */
/* neuromodulator_get_levels - defined in nimcp_neuromodulators_lifecycle.c */
/* neuromodulator_set_sleep_state - defined in nimcp_neuromodulators_lifecycle.c */
/* neuromodulator_get_sleep_state - defined in nimcp_neuromodulators_lifecycle.c */
/* neuromodulator_pool_get_by_type - defined in nimcp_neuromodulators_lifecycle.c */
/* neuromodulator_pool_set_by_type - defined in nimcp_neuromodulators_lifecycle.c */
/* receptor_profile_get_density - defined in nimcp_neuromodulators_lifecycle.c */
/* receptor_profile_set_beta_density - defined in nimcp_neuromodulators_lifecycle.c */
/* modulation_effects_get_learning_rate_multiplier - defined in nimcp_neuromodulators_lifecycle.c */

/* --- serotonin module --- */
/* neuromodulator_release_serotonin - defined in nimcp_neuromodulators_serotonin.c */
/* neuromodulator_pool_get_serotonin - defined in nimcp_neuromodulators_serotonin.c */
/* neuromodulator_pool_set_serotonin - defined in nimcp_neuromodulators_serotonin.c */
/* receptor_profile_get_serotonin_density - defined in nimcp_neuromodulators_serotonin.c */
/* receptor_profile_set_serotonin_density - defined in nimcp_neuromodulators_serotonin.c */
/* receptor_profile_set_density - defined in nimcp_neuromodulators_serotonin.c */
/* receptor_profile_get_d1_density - defined in nimcp_neuromodulators_serotonin.c */
/* receptor_profile_get_d2_density - defined in nimcp_neuromodulators_serotonin.c */
/* receptor_profile_get_nicotinic_density - defined in nimcp_neuromodulators_serotonin.c */
/* receptor_profile_get_alpha_density - defined in nimcp_neuromodulators_serotonin.c */
/* receptor_profile_get_beta_density - defined in nimcp_neuromodulators_serotonin.c */
/* receptor_profile_set_d1_density - defined in nimcp_neuromodulators_serotonin.c */
/* receptor_profile_set_d2_density - defined in nimcp_neuromodulators_serotonin.c */
/* receptor_profile_set_nicotinic_density - defined in nimcp_neuromodulators_serotonin.c */
/* receptor_profile_set_alpha_density - defined in nimcp_neuromodulators_serotonin.c */

/* --- stats module --- */
/* neuromodulator_get_stats - defined in nimcp_neuromodulators_stats.c */
/* neuromodulator_get_learning_weight - defined in nimcp_neuromodulators_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_NEUROMODULATORS_INTERNAL_H */
