//=============================================================================
// nimcp_thermo_snn_bridge.h - Thermodynamics to SNN Temperature Effects Bridge
//=============================================================================
/**
 * @file nimcp_thermo_snn_bridge.h
 * @brief Temperature modulation of Spiking Neural Network dynamics
 * @version 1.0.0
 * @date 2026-01-13
 *
 * WHAT: Bridges non-equilibrium thermodynamics to SNN computation,
 *       applying temperature-dependent effects on neural firing.
 *
 * WHY:  Temperature profoundly affects neural dynamics:
 *       - Ion channel kinetics follow Q10 temperature coefficients
 *       - Spike threshold varies with temperature
 *       - Firing rates increase exponentially with temperature
 *       - Synaptic transmission is temperature-sensitive
 *       - Metabolic heat generation scales with activity
 *
 * HOW:  - Monitors thermodynamic state (temperature, ATP, heat)
 *       - Computes Q10-scaled rate constants for SNN parameters
 *       - Modulates firing thresholds and time constants
 *       - Tracks metabolic heat generated by neural activity
 *       - Provides feedback loop for activity-dependent heating
 *
 * BIOLOGICAL BASIS:
 * =================================================================================
 *
 * TEMPERATURE EFFECTS ON SNN PARAMETERS:
 * --------------------------------------
 * 1. Firing threshold (Q10 ~ 1.3):
 *    - Higher temp -> lower threshold -> increased excitability
 *    - V_th(T) = V_th_ref * Q10^((T_ref - T) / 10)
 *
 * 2. Membrane time constant (Q10 ~ 2.5):
 *    - Higher temp -> faster membrane dynamics
 *    - tau_m(T) = tau_m_ref * Q10^((T_ref - T) / 10)
 *
 * 3. Synaptic time constants (Q10 ~ 2.0):
 *    - Faster EPSP/IPSP kinetics at higher temperatures
 *    - Affects temporal summation and integration
 *
 * 4. Refractory period (Q10 ~ 2.3):
 *    - Shorter refractory -> higher max firing rates
 *    - Affects population coding capacity
 *
 * METABOLIC HEAT GENERATION:
 * --------------------------
 * - Each spike consumes ~10^8 ATP molecules
 * - ATP hydrolysis releases ~50 kJ/mol as heat
 * - Neural activity directly generates local heating
 * - Creates feedback: activity -> heat -> more activity
 *
 * NIMCP STANDARDS:
 * - All functions < 50 lines
 * - Guard clauses (early returns)
 * - WHAT-WHY-HOW documentation
 * - Thread-safe via mutex
 * - nimcp_malloc/nimcp_free memory management
 *
 * @author NIMCP Development Team
 */

#ifndef NIMCP_THERMO_SNN_BRIDGE_H
#define NIMCP_THERMO_SNN_BRIDGE_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "common/nimcp_export.h"
#include "physics/thermodynamics/nimcp_thermodynamics.h"

#ifdef __cplusplus
extern "C" {
#endif

//=============================================================================
// Module Constants
//=============================================================================

/** Module name for logging */
#define THERMO_SNN_MODULE_NAME              "thermo_snn_bridge"

/** Reference temperature (Kelvin) - body temperature */
#define THERMO_SNN_TEMP_REF_K               310.15f

/** Q10 for membrane time constant */
#define THERMO_SNN_Q10_TAU_M                2.5f

/** Q10 for firing threshold */
#define THERMO_SNN_Q10_THRESHOLD            1.3f

/** Q10 for synaptic time constants */
#define THERMO_SNN_Q10_SYNAPTIC             2.0f

/** Q10 for refractory period */
#define THERMO_SNN_Q10_REFRACTORY           2.3f

/** Q10 for firing rate (Arrhenius-like) */
#define THERMO_SNN_Q10_FIRING_RATE          2.0f

/** ATP consumed per spike (moles) - approx 10^8 molecules */
#define THERMO_SNN_ATP_PER_SPIKE            1.66e-16

/** Heat per ATP hydrolysis (J) - ~50 kJ/mol */
#define THERMO_SNN_HEAT_PER_ATP             8.3e-20

/** Maximum temperature deviation from reference (K) */
#define THERMO_SNN_MAX_TEMP_DEV             10.0f

/** Default update interval (ms) */
#define THERMO_SNN_DEFAULT_UPDATE_MS        10.0f

//=============================================================================
// Enumerations
//=============================================================================

/**
 * @brief Temperature effect mode
 */
typedef enum {
    THERMO_SNN_MODE_DISABLED = 0,       /**< No temperature effects */
    THERMO_SNN_MODE_LINEAR,             /**< Linear approximation */
    THERMO_SNN_MODE_Q10,                /**< Q10 exponential scaling */
    THERMO_SNN_MODE_ARRHENIUS           /**< Full Arrhenius kinetics */
} thermo_snn_mode_t;

/**
 * @brief Heat dissipation model
 */
typedef enum {
    THERMO_SNN_HEAT_NONE = 0,           /**< No heat modeling */
    THERMO_SNN_HEAT_ACCUMULATE,         /**< Accumulate without dissipation */
    THERMO_SNN_HEAT_NEWTONIAN,          /**< Newton's law of cooling */
    THERMO_SNN_HEAT_CONVECTIVE          /**< Convective heat transfer */
} thermo_snn_heat_model_t;

//=============================================================================
// Configuration Structure
//=============================================================================

/**
 * @brief Configuration for thermo-SNN bridge
 *
 * WHAT: All parameters controlling temperature effects on SNN
 * WHY:  Allows tuning temperature sensitivity for different applications
 * HOW:  Q10 values and reference points for each modulated parameter
 */
typedef struct {
    /* Operating mode */
    thermo_snn_mode_t mode;                 /**< Temperature effect mode */
    thermo_snn_heat_model_t heat_model;     /**< Heat dissipation model */

    /* Reference values */
    float reference_temp_k;                 /**< Reference temperature (K) */
    float ambient_temp_k;                   /**< Ambient temperature for cooling (K) */

    /* Q10 coefficients */
    float q10_tau_m;                        /**< Q10 for membrane time constant */
    float q10_threshold;                    /**< Q10 for firing threshold */
    float q10_synaptic;                     /**< Q10 for synaptic time constants */
    float q10_refractory;                   /**< Q10 for refractory period */
    float q10_firing_rate;                  /**< Q10 for spontaneous firing rate */

    /* Heat parameters */
    float atp_per_spike;                    /**< ATP consumed per spike (moles) */
    float heat_per_atp;                     /**< Heat released per ATP (J) */
    float cooling_coefficient;              /**< Heat dissipation rate (W/K) */
    float thermal_mass;                     /**< Thermal capacity (J/K) */

    /* Limits and safety */
    float min_temp_k;                       /**< Minimum allowed temperature (K) */
    float max_temp_k;                       /**< Maximum allowed temperature (K) */
    float hyperthermia_threshold_k;         /**< Temperature triggering protection */

    /* Feature flags */
    bool enable_threshold_modulation;       /**< Modulate firing threshold */
    bool enable_tau_modulation;             /**< Modulate time constants */
    bool enable_heat_generation;            /**< Track heat from activity */
    bool enable_heat_dissipation;           /**< Model heat dissipation */
    bool enable_atp_tracking;               /**< Track ATP consumption */
    bool enable_hyperthermia_protection;    /**< Reduce activity at high temp */

    /* Update parameters */
    float update_interval_ms;               /**< Bridge update interval */
} thermo_snn_config_t;

//=============================================================================
// SNN Parameter Modulation Structure
//=============================================================================

/**
 * @brief Temperature-modulated SNN parameters
 *
 * WHAT: Scaled SNN parameters based on current temperature
 * WHY:  Provides ready-to-use parameters for SNN simulation
 * HOW:  Q10 scaling applied to reference values
 */
typedef struct {
    /* Temperature state */
    float current_temp_k;                   /**< Current temperature (K) */
    float temp_deviation;                   /**< Deviation from reference (K) */

    /* Scaled parameters (multipliers) */
    float tau_m_factor;                     /**< Membrane time constant factor */
    float threshold_factor;                 /**< Firing threshold factor */
    float tau_syn_factor;                   /**< Synaptic time constant factor */
    float refractory_factor;                /**< Refractory period factor */
    float rate_factor;                      /**< Firing rate factor */

    /* Absolute scaled values (if reference provided) */
    float scaled_tau_m_ms;                  /**< Scaled tau_m (ms) */
    float scaled_threshold_mv;              /**< Scaled threshold (mV) */
    float scaled_tau_syn_ms;                /**< Scaled tau_syn (ms) */
    float scaled_refractory_ms;             /**< Scaled refractory (ms) */

    /* Heat state */
    float accumulated_heat_j;               /**< Accumulated heat (J) */
    float heat_generation_rate_w;           /**< Current heat generation (W) */
    float heat_dissipation_rate_w;          /**< Current heat dissipation (W) */

    /* ATP state */
    float atp_consumed_moles;               /**< Total ATP consumed (moles) */
    float atp_consumption_rate;             /**< ATP consumption rate (moles/s) */

    /* Safety state */
    bool hyperthermia_active;               /**< High-temp protection engaged */
    float protection_factor;                /**< Activity reduction factor [0,1] */

    /* Timestamp */
    uint64_t last_update_us;                /**< Last update timestamp */
} thermo_snn_modulation_t;

//=============================================================================
// Statistics Structure
//=============================================================================

/**
 * @brief Bridge statistics
 */
typedef struct {
    /* Update counts */
    uint64_t updates_performed;             /**< Total bridge updates */
    uint64_t spikes_processed;              /**< Total spikes tracked */

    /* Temperature stats */
    float min_temp_observed_k;              /**< Minimum temperature seen */
    float max_temp_observed_k;              /**< Maximum temperature seen */
    float avg_temp_k;                       /**< Average temperature */

    /* Heat stats */
    double total_heat_generated_j;          /**< Total heat from activity */
    double total_heat_dissipated_j;         /**< Total heat dissipated */
    float peak_heat_rate_w;                 /**< Peak heat generation rate */

    /* ATP stats */
    double total_atp_consumed;              /**< Total ATP consumed (moles) */
    float avg_atp_per_second;               /**< Average ATP consumption rate */

    /* Modulation stats */
    float avg_tau_factor;                   /**< Average tau modulation */
    float avg_threshold_factor;             /**< Average threshold modulation */

    /* Protection stats */
    uint64_t hyperthermia_events;           /**< Times protection triggered */
    float total_protection_time_s;          /**< Time in protection mode */

    /* Timing */
    uint64_t start_time_us;                 /**< Bridge start time */
    uint64_t total_runtime_us;              /**< Total running time */
} thermo_snn_stats_t;

//=============================================================================
// Opaque Bridge Handle
//=============================================================================

/** Opaque bridge handle */
typedef struct thermo_snn_bridge_struct thermo_snn_bridge_t;

//=============================================================================
// Configuration API
//=============================================================================

/**
 * @brief Get default configuration
 *
 * WHAT: Initialize configuration with biologically-plausible defaults
 * WHY:  Simplifies bridge creation with sensible starting point
 * HOW:  Sets Q10 values from literature, enables common features
 *
 * @param config    Configuration to initialize
 * @return 0 on success, -1 on error
 */
NIMCP_EXPORT int thermo_snn_default_config(thermo_snn_config_t* config);

//=============================================================================
// Lifecycle API
//=============================================================================

/**
 * @brief Create thermo-SNN bridge
 *
 * WHAT: Allocate and initialize bridge instance
 * WHY:  Enables temperature modulation of SNN parameters
 * HOW:  Creates internal state, initializes thermal tracking
 *
 * @param config    Configuration (NULL for defaults)
 * @return Bridge handle or NULL on error
 */
NIMCP_EXPORT thermo_snn_bridge_t* thermo_snn_bridge_create(
    const thermo_snn_config_t* config
);

/**
 * @brief Destroy bridge and free resources
 *
 * @param bridge    Bridge to destroy (NULL-safe)
 */
NIMCP_EXPORT void thermo_snn_bridge_destroy(thermo_snn_bridge_t* bridge);

//=============================================================================
// Connection API
//=============================================================================

/**
 * @brief Connect bridge to thermodynamic state
 *
 * WHAT: Link bridge to thermodynamics module for temperature input
 * WHY:  Enables real-time temperature tracking from physics layer
 * HOW:  Stores reference to thermodynamic state for polling
 *
 * @param bridge    Bridge handle
 * @param thermo    Thermodynamic state to monitor
 * @return 0 on success, -1 on error
 */
NIMCP_EXPORT int thermo_snn_connect_thermo(
    thermo_snn_bridge_t* bridge,
    const nimcp_thermodynamic_state_t* thermo
);

/**
 * @brief Set reference SNN parameters for scaling
 *
 * WHAT: Provide base SNN parameters to scale by temperature
 * WHY:  Allows computing absolute scaled values, not just factors
 * HOW:  Stores reference values, computes scaled versions on update
 *
 * @param bridge            Bridge handle
 * @param ref_tau_m_ms      Reference membrane time constant (ms)
 * @param ref_threshold_mv  Reference firing threshold (mV)
 * @param ref_tau_syn_ms    Reference synaptic time constant (ms)
 * @param ref_refractory_ms Reference refractory period (ms)
 * @return 0 on success, -1 on error
 */
NIMCP_EXPORT int thermo_snn_set_reference_params(
    thermo_snn_bridge_t* bridge,
    float ref_tau_m_ms,
    float ref_threshold_mv,
    float ref_tau_syn_ms,
    float ref_refractory_ms
);

//=============================================================================
// Update API
//=============================================================================

/**
 * @brief Update bridge state
 *
 * WHAT: Periodic update of temperature modulation
 * WHY:  Recomputes scaling factors based on current temperature
 * HOW:  Reads temperature, applies Q10 scaling, updates heat model
 *
 * @param bridge    Bridge handle
 * @param dt_ms     Time step (milliseconds)
 * @return 0 on success, -1 on error
 */
NIMCP_EXPORT int thermo_snn_update(
    thermo_snn_bridge_t* bridge,
    float dt_ms
);

/**
 * @brief Set temperature directly
 *
 * WHAT: Manually set operating temperature
 * WHY:  For use without connected thermodynamic state
 * HOW:  Updates internal temperature, recomputes modulation
 *
 * @param bridge        Bridge handle
 * @param temperature_k Temperature in Kelvin
 * @return 0 on success, -1 on error
 */
NIMCP_EXPORT int thermo_snn_set_temperature(
    thermo_snn_bridge_t* bridge,
    float temperature_k
);

/**
 * @brief Register spike activity for heat tracking
 *
 * WHAT: Record spikes for metabolic heat calculation
 * WHY:  Activity generates heat proportional to spike count
 * HOW:  Accumulates ATP cost and heat generation
 *
 * @param bridge        Bridge handle
 * @param num_spikes    Number of spikes this timestep
 * @return 0 on success, -1 on error
 */
NIMCP_EXPORT int thermo_snn_register_activity(
    thermo_snn_bridge_t* bridge,
    uint32_t num_spikes
);

/**
 * @brief Reset bridge state
 *
 * @param bridge    Bridge handle
 * @return 0 on success, -1 on error
 */
NIMCP_EXPORT int thermo_snn_reset(thermo_snn_bridge_t* bridge);

//=============================================================================
// Query API
//=============================================================================

/**
 * @brief Get current modulation parameters
 *
 * WHAT: Retrieve temperature-scaled SNN parameters
 * WHY:  For applying modulation to SNN simulation
 * HOW:  Copies current modulation state to output
 *
 * @param bridge        Bridge handle
 * @param modulation    Output modulation structure
 * @return 0 on success, -1 on error
 */
NIMCP_EXPORT int thermo_snn_get_modulation(
    const thermo_snn_bridge_t* bridge,
    thermo_snn_modulation_t* modulation
);

/**
 * @brief Get individual scaling factor
 *
 * @param bridge    Bridge handle
 * @param tau_factor        Output: tau_m scaling factor
 * @param threshold_factor  Output: threshold scaling factor
 * @param rate_factor       Output: firing rate scaling factor
 * @return 0 on success, -1 on error
 */
NIMCP_EXPORT int thermo_snn_get_factors(
    const thermo_snn_bridge_t* bridge,
    float* tau_factor,
    float* threshold_factor,
    float* rate_factor
);

/**
 * @brief Compute Q10 scaling for arbitrary parameter
 *
 * WHAT: Calculate Q10 scaling factor for given temperatures
 * WHY:  General utility for custom parameter scaling
 * HOW:  factor = Q10^((T - T_ref) / 10)
 *
 * @param q10               Q10 coefficient
 * @param current_temp_k    Current temperature (K)
 * @param reference_temp_k  Reference temperature (K)
 * @return Scaling factor
 */
NIMCP_EXPORT float thermo_snn_compute_q10_factor(
    float q10,
    float current_temp_k,
    float reference_temp_k
);

/**
 * @brief Get bridge statistics
 *
 * @param bridge    Bridge handle
 * @param stats     Output statistics structure
 * @return 0 on success, -1 on error
 */
NIMCP_EXPORT int thermo_snn_get_stats(
    const thermo_snn_bridge_t* bridge,
    thermo_snn_stats_t* stats
);

/**
 * @brief Reset statistics
 *
 * @param bridge    Bridge handle
 * @return 0 on success, -1 on error
 */
NIMCP_EXPORT int thermo_snn_reset_stats(thermo_snn_bridge_t* bridge);

/**
 * @brief Check if hyperthermia protection is active
 *
 * @param bridge    Bridge handle
 * @return true if protection is engaged
 */
NIMCP_EXPORT bool thermo_snn_is_hyperthermic(
    const thermo_snn_bridge_t* bridge
);

/**
 * @brief Get current temperature
 *
 * @param bridge    Bridge handle
 * @return Current temperature in Kelvin, or 0 on error
 */
NIMCP_EXPORT float thermo_snn_get_temperature(
    const thermo_snn_bridge_t* bridge
);

//=============================================================================
// Utility API
//=============================================================================

/**
 * @brief Convert Celsius to Kelvin
 *
 * @param celsius   Temperature in Celsius
 * @return Temperature in Kelvin
 */
NIMCP_EXPORT float thermo_snn_celsius_to_kelvin(float celsius);

/**
 * @brief Convert Kelvin to Celsius
 *
 * @param kelvin    Temperature in Kelvin
 * @return Temperature in Celsius
 */
NIMCP_EXPORT float thermo_snn_kelvin_to_celsius(float kelvin);

/**
 * @brief Print bridge summary to stdout
 *
 * @param bridge    Bridge handle
 */
NIMCP_EXPORT void thermo_snn_print_summary(const thermo_snn_bridge_t* bridge);

#ifdef __cplusplus
}
#endif

#endif /* NIMCP_THERMO_SNN_BRIDGE_H */
