/**
 * @file nimcp_salience_internal.h
 * @brief Internal shared declarations for nimcp_salience SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_SALIENCE_INTERNAL_H
#define NIMCP_SALIENCE_INTERNAL_H

#include "cognitive/salience/nimcp_salience.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "cognitive/knowledge/nimcp_kg_reader.h"
#include "security/nimcp_security.h"
#include "security/nimcp_blood_brain_barrier.h"
#include "utils/memory/nimcp_unified_memory.h"
#include <math.h>
#include <stdio.h>
#include <string.h>
#include "utils/memory/nimcp_memory_pool.h"
#include "utils/thread/nimcp_thread.h"
#include "utils/thread/nimcp_thread_pool.h"
#include "utils/time/nimcp_time.h"
#include "utils/containers/nimcp_vector.h"
#include "plasticity/neuromodulators/nimcp_neuromodulators.h"  // Acetylcholine gating
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_messages.h"
#include "async/nimcp_bio_router.h"
#include "async/nimcp_wiring_helpers.h"
#include "nimcp.h"  // For error codes
#include "cognitive/salience/nimcp_salience_snn_bridge.h"
#include "cognitive/salience/nimcp_salience_plasticity_bridge.h"
#include <immintrin.h>
#include "utils/bridge/nimcp_bridge_boilerplate.h"
#include "mesh/nimcp_mesh_participant.h"
#include "mesh/nimcp_mesh_adapter.h"
#include "constants/nimcp_buffer_constants.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

/**
 * WHAT: Single entry in history buffer
 * WHY: Store recent inputs for novelty comparison
 * NOTE: Now uses fixed-size array for nimcp_queue compatibility
 */
typedef struct {
    float features[SALIENCE_MAX_FEATURES];  // Feature vector (fixed-size)
    uint32_t num_features;                  // Actual size used
    uint64_t timestamp;                     // When input occurred
    bool valid;                             // Is this slot occupied?
} history_entry_t;

/**
 * WHAT: Circular buffer for recent input history
 * WHY: Novelty = how different from recent past
 * HOW: Ring buffer with fixed-size entries (no heap allocation per entry)
 *
 * PATTERN: Memento pattern - stores past states for comparison
 * NOTE: Uses fixed-size entries to eliminate per-entry malloc/free
 */
typedef struct {
    history_entry_t* entries;  // Circular buffer (fixed-size entries)
    uint32_t capacity;         // Buffer size
    uint32_t head;             // Next write position
    uint32_t count;            // Current entry count
    nimcp_mutex_t lock;        // Thread safety
} history_buffer_t;

//=============================================================================
// Prediction Model for Surprise Detection
//=============================================================================

/**
 * WHAT: Simple exponential moving average predictor
 * WHY: Predict next input based on recent trend
 * HOW: EMA of recent inputs
 *
 * PATTERN: Memento pattern - maintains prediction state
 */
typedef struct {
    float* prediction;      // Predicted next input
    uint32_t num_features;  // Feature dimension
    float alpha;            // EMA smoothing factor (0-1)
    bool initialized;       // Has seen at least one input?
    nimcp_mutex_t lock;     // Thread safety
} predictor_t;

//=============================================================================
// Salience Evaluator Structure (Opaque Implementation)
//=============================================================================

/**
 * WHAT: Per-modality salience storage
 * WHY: Track salience separately for each sensory modality before fusion
 * HOW: Store salience scores and activation state per modality
 */
typedef struct {
    brain_salience_t salience;  /**< Most recent salience for this modality */
    float weight;               /**< Fusion weight (normalized) */
    bool active;                /**< Is this modality registered/active? */
    bool has_data;              /**< Has received evaluation data? */
} modality_state_t;

/**
 * WHAT: Complete salience evaluator state
 * WHY: Encapsulates all evaluation data and configuration
 * PATTERN: Opaque pointer (Pimpl idiom)
 */
struct salience_evaluator_struct {
    // Brain association
    brain_t brain;

    // Configuration
    salience_config_t config;

    // Novelty detection (Memento pattern)
    history_buffer_t* history;

    // Surprise detection (Memento pattern)
    predictor_t* predictor;

    // Event callback (Observer pattern)
    salience_event_callback_fn callback;
    void* callback_context;

    // Bio-async module context
    bio_module_context_t bio_ctx;
    bool bio_async_enabled;

    // Statistics
    _Atomic uint64_t stats_evaluations;
    _Atomic uint64_t stats_high_salience;
    _Atomic uint64_t stats_high_novelty;
    _Atomic uint64_t stats_high_surprise;
    _Atomic uint64_t stats_high_urgency;

    float running_avg_salience;
    float running_avg_novelty;
    float running_avg_surprise;
    float running_avg_urgency;

    uint64_t total_eval_time_us;

    // Thread safety
    nimcp_mutex_t eval_lock;

    // Parallel processing (for batch operations)
    nimcp_thread_pool_t* thread_pool;

    // Phase 1.5: Memory pool for history entry allocations
    memory_pool_t history_entry_pool;

    // Cross-modal fusion state
    modality_state_t modalities[SALIENCE_MODALITY_COUNT];
    salience_fusion_strategy_t fusion_strategy;

    // SNN and Plasticity bridges
    salience_snn_bridge_t* snn_bridge;             /**< SNN integration bridge */
    salience_plasticity_bridge_t* plasticity_bridge;  /**< Plasticity integration bridge */
    bool bridges_enabled;                          /**< Whether bridges are active */
};

/**
 * WHAT: Task context for parallel batch evaluation
 * WHY: Worker threads need access to evaluator and specific sample
 * PATTERN: Command pattern - encapsulates evaluation request
 */
typedef struct {
    salience_evaluator_t eval; /* Evaluator to use */
    const float* features;     /* Input features for this sample */
    uint32_t num_features;     /* Feature count */
    brain_salience_t* output;  /* Where to store result */
} batch_task_t;

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- detection module --- */
/* brain_evaluate_salience - defined in nimcp_salience_detection.c */
/* brain_evaluate_salience_temporal - defined in nimcp_salience_detection.c */
/* brain_evaluate_salience_batch - defined in nimcp_salience_detection.c */
/* salience_quick_evaluate - defined in nimcp_salience_detection.c */
/* salience_boost_threat_detection - defined in nimcp_salience_detection.c */
/* salience_evaluate_modality - defined in nimcp_salience_detection.c */
/* salience_default_config - defined in nimcp_salience_detection.c */
/* salience_boost_negative_cues - defined in nimcp_salience_detection.c */
/* salience_get_surprise_level - defined in nimcp_salience_detection.c */
/* salience_register_modality - defined in nimcp_salience_detection.c */

/* --- integration module --- */
/* salience_fuse_modalities - defined in nimcp_salience_integration.c */

/* --- lifecycle module --- */
/* salience_evaluator_create - defined in nimcp_salience_lifecycle.c */
/* salience_evaluator_destroy - defined in nimcp_salience_lifecycle.c */
/* salience_reset_stats - defined in nimcp_salience_lifecycle.c */
/* salience_get_last_error - defined in nimcp_salience_lifecycle.c */

/* --- stats module --- */
/* salience_get_stats - defined in nimcp_salience_stats.c */
/* salience_set_weights - defined in nimcp_salience_stats.c */
/* salience_set_thresholds - defined in nimcp_salience_stats.c */
/* salience_register_callback - defined in nimcp_salience_stats.c */
/* salience_clear_history - defined in nimcp_salience_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_SALIENCE_INTERNAL_H */
