/**
 * @file nimcp_lnn_gradient_internal.h
 * @brief Internal shared declarations for nimcp_lnn_gradient SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_LNN_GRADIENT_INTERNAL_H
#define NIMCP_LNN_GRADIENT_INTERNAL_H

#include "lnn/nimcp_lnn_gradient.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "lnn/nimcp_lnn_types.h"
#include "lnn/nimcp_lnn_layer.h"
#include "lnn/nimcp_lnn_neuron.h"
#include "lnn/nimcp_lnn_ode.h"
#include "utils/thread/nimcp_thread.h"
#include "utils/thread/nimcp_thread_pool.h"
#include "middleware/training/nimcp_optimizers.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include "utils/fault_tolerance/nimcp_health_agent_macros.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

    // Allocate per-batch gradient buffers
    typedef struct batch_task_ctx {
        lnn_gradient_ctx_t* grad_ctx;
        lnn_network_t* network;
        const float* dL_dx_data;
        uint32_t batch_idx;
        uint32_t seq_len;
        uint32_t n_neurons;
        nimcp_tensor_t* local_grad;
        int result;
    } batch_task_ctx_t;

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- apply module --- */
/* lnn_gradient_adjoint_step - defined in nimcp_lnn_gradient_apply.c */
/* lnn_gradient_apply - defined in nimcp_lnn_gradient_apply.c */

/* --- compute module --- */
/* lnn_gradient_compute_adjoint - defined in nimcp_lnn_gradient_compute.c */
/* lnn_gradient_compute_bptt - defined in nimcp_lnn_gradient_compute.c */
/* lnn_gradient_compute_batch_parallel - defined in nimcp_lnn_gradient_compute.c */
/* lnn_gradient_compute_jacobian - defined in nimcp_lnn_gradient_compute.c */
/* lnn_network_backward - defined in nimcp_lnn_gradient_compute.c */
/* lnn_gradient_get_params - defined in nimcp_lnn_gradient_compute.c */

/* --- io module --- */
/* lnn_gradient_save_checkpoint - defined in nimcp_lnn_gradient_io.c */
/* lnn_gradient_load_checkpoint - defined in nimcp_lnn_gradient_io.c */
/* lnn_gradient_recompute_from_checkpoint - defined in nimcp_lnn_gradient_io.c */

/* --- lifecycle module --- */
/* lnn_gradient_ctx_create - defined in nimcp_lnn_gradient_lifecycle.c */
/* lnn_gradient_ctx_destroy - defined in nimcp_lnn_gradient_lifecycle.c */
/* lnn_gradient_reset - defined in nimcp_lnn_gradient_lifecycle.c */

/* --- stats module --- */
/* lnn_gradient_get_stats - defined in nimcp_lnn_gradient_stats.c */
/* lnn_gradient_norm - defined in nimcp_lnn_gradient_stats.c */
/* lnn_gradient_clip - defined in nimcp_lnn_gradient_stats.c */
/* lnn_gradient_check_health - defined in nimcp_lnn_gradient_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_LNN_GRADIENT_INTERNAL_H */
