/**
 * @file nimcp_collective_cognition_internal.h
 * @brief Internal shared declarations for nimcp_collective_cognition SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_COLLECTIVE_COGNITION_INTERNAL_H
#define NIMCP_COLLECTIVE_COGNITION_INTERNAL_H

#include "cognitive/collective_cognition/nimcp_collective_cognition.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "cognitive/knowledge/nimcp_kg_reader.h"
#include "cognitive/collective_cognition/nimcp_hyperscanning.h"
#include "cognitive/collective_cognition/nimcp_extended_mind.h"
#include "cognitive/collective_cognition/nimcp_collective_phi.h"
#include "cognitive/collective_cognition/nimcp_shared_intentionality.h"
#include "utils/time/nimcp_time.h"
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <stdatomic.h>
#include "utils/bridge/nimcp_bridge_boilerplate.h"
#include "mesh/nimcp_mesh_participant.h"
#include "mesh/nimcp_mesh_adapter.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

 * Internal Structures
 *===========================================================================*/

/**
 * @brief Registered brain instance
 */
typedef struct {
    uint32_t instance_id;
    brain_t* brain;                 /* Optional direct brain reference */
    bool active;

    /* Per-instance state */
    float local_phi;                /* Individual phi */
    float atp_level;                /* Metabolic state */
    float fatigue_level;
    uint64_t last_heartbeat_us;
    uint32_t missed_heartbeats;

    /* Sync state per band */
    float band_power[SYNC_BAND_COUNT];
    float band_phase[SYNC_BAND_COUNT];
} registered_instance_t;

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- io module --- */
/* collective_cognition_balance_load - defined in nimcp_collective_cognition_io.c */
/* collective_cognition_get_extended_mind_state - defined in nimcp_collective_cognition_io.c */
/* collective_cognition_get_phi - defined in nimcp_collective_cognition_io.c */
/* collective_cognition_get_we_mode - defined in nimcp_collective_cognition_io.c */
/* collective_cognition_get_hyperscanning - defined in nimcp_collective_cognition_io.c */
/* collective_cognition_get_extended_mind - defined in nimcp_collective_cognition_io.c */
/* collective_cognition_get_phi_system - defined in nimcp_collective_cognition_io.c */
/* collective_cognition_get_intentionality - defined in nimcp_collective_cognition_io.c */
/* collective_cognition_connect_bio_async - defined in nimcp_collective_cognition_io.c */
/* collective_cognition_disconnect_bio_async - defined in nimcp_collective_cognition_io.c */
/* collective_cognition_is_bio_async_connected - defined in nimcp_collective_cognition_io.c */

/* --- lifecycle module --- */
/* collective_cognition_create - defined in nimcp_collective_cognition_lifecycle.c */
/* collective_cognition_destroy - defined in nimcp_collective_cognition_lifecycle.c */
/* collective_cognition_reset - defined in nimcp_collective_cognition_lifecycle.c */
/* collective_cognition_reset_stats - defined in nimcp_collective_cognition_lifecycle.c */
/* collective_cognition_default_config - defined in nimcp_collective_cognition_lifecycle.c */
/* hyperscanning_default_config - defined in nimcp_collective_cognition_lifecycle.c */
/* extended_mind_default_config - defined in nimcp_collective_cognition_lifecycle.c */
/* collective_phi_default_config - defined in nimcp_collective_cognition_lifecycle.c */
/* shared_intentionality_default_config - defined in nimcp_collective_cognition_lifecycle.c */
/* collective_cognition_register_instance - defined in nimcp_collective_cognition_lifecycle.c */
/* collective_cognition_unregister_instance - defined in nimcp_collective_cognition_lifecycle.c */
/* collective_consciousness_level_name - defined in nimcp_collective_cognition_lifecycle.c */

/* --- stats module --- */
/* collective_cognition_get_stats - defined in nimcp_collective_cognition_stats.c */
/* collective_cognition_dump - defined in nimcp_collective_cognition_stats.c */
/* collective_cognition_offload_task - defined in nimcp_collective_cognition_stats.c */
/* sync_band_name - defined in nimcp_collective_cognition_stats.c */
/* extension_type_name - defined in nimcp_collective_cognition_stats.c */
/* collective_cognition_query_self_knowledge - defined in nimcp_collective_cognition_stats.c */
/* collective_cognition_set_instance_health_agent - defined in nimcp_collective_cognition_stats.c */
/* collective_cognition_training_begin - defined in nimcp_collective_cognition_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_COLLECTIVE_COGNITION_INTERNAL_H */
