/**
 * @file nimcp_omni_world_model_internal.h
 * @brief Internal shared declarations for nimcp_omni_world_model SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_OMNI_WORLD_MODEL_INTERNAL_H
#define NIMCP_OMNI_WORLD_MODEL_INTERNAL_H

#include "cognitive/omni/nimcp_omni_world_model.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "async/nimcp_bio_router.h"
#include "async/nimcp_bio_messages.h"
#include "utils/thread/nimcp_thread.h"
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <float.h>
#include <time.h>
#include <stdio.h>
#include "utils/bridge/nimcp_bridge_boilerplate.h"
#include "mesh/nimcp_mesh_participant.h"
#include "mesh/nimcp_mesh_adapter.h"
#include "constants/nimcp_constants.h"
#include "constants/nimcp_math_constants.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

/**
 * @brief Checkpoint storage structure
 */
typedef struct {
    omni_wm_checkpoint_t checkpoints[OMNI_WM_MAX_CHECKPOINTS];
    uint32_t count;
    uint64_t next_id;
} omni_wm_checkpoint_store_t;

/**
 * @brief Experience replay buffer (circular)
 */
typedef struct {
    omni_wm_experience_t** experiences;  /**< Experience array */
    uint32_t capacity;                    /**< Maximum size */
    uint32_t size;                        /**< Current size */
    uint32_t head;                        /**< Write position */
    float* priorities;                    /**< Priority values */
} omni_wm_replay_buffer_t;

/**
 * @brief Forward dynamics model weights (simple linear for now)
 */
typedef struct {
    float* W_h;      /**< Weights for deterministic transition */
    float* W_z;      /**< Weights for stochastic prior */
    float* W_obs;    /**< Weights for observation model */
    float* b_h;      /**< Bias for deterministic */
    float* b_z;      /**< Bias for stochastic */
    float* b_obs;    /**< Bias for observation */
    uint32_t h_dim;
    uint32_t z_dim;
    uint32_t obs_dim;
    uint32_t action_dim;
} omni_wm_dynamics_t;

 * Bio-Async Integration - Message Structures
 * ============================================================================ */

/**
 * @brief Prediction request message (BIO_MSG_OMNI_WM_PREDICT - 0x6201)
 */
typedef struct {
    bio_message_header_t header;
    float state[OMNI_WM_MAX_STATE_DIM];   /**< Current state */
    uint32_t state_dim;                    /**< State dimensionality */
    float action[OMNI_WM_MAX_ACTION_DIM]; /**< Action to predict */
    uint32_t action_dim;                   /**< Action dimensionality */
    omni_wm_direction_t direction;         /**< Dynamics direction */
} bio_msg_omni_wm_predict_t;

/**
 * @brief Prediction response message
 */
typedef struct {
    bio_message_header_t header;
    float predicted_state[OMNI_WM_MAX_STATE_DIM]; /**< Predicted state */
    uint32_t state_dim;                            /**< State dimensionality */
    float prediction_error;                        /**< Prediction error estimate */
    float confidence;                              /**< Prediction confidence */
} bio_msg_omni_wm_predict_response_t;

/**
 * @brief Counterfactual query message (BIO_MSG_OMNI_WM_COUNTERFACTUAL - 0x6202)
 */
typedef struct {
    bio_message_header_t header;
    omni_wm_counterfactual_type_t cf_type;         /**< Type of counterfactual */
    float initial_state[OMNI_WM_MAX_STATE_DIM];    /**< Starting state */
    uint32_t state_dim;                             /**< State dimensionality */
    float hypothetical_action[OMNI_WM_MAX_ACTION_DIM]; /**< Hypothetical action */
    uint32_t action_dim;                            /**< Action dimensionality */
    uint32_t horizon;                               /**< Simulation horizon */
} bio_msg_omni_wm_counterfactual_t;

/**
 * @brief Counterfactual response message
 */
typedef struct {
    bio_message_header_t header;
    float expected_reward;       /**< Expected cumulative reward */
    float divergence;            /**< Divergence from actual trajectory */
    float confidence;            /**< Prediction confidence */
    uint32_t trajectory_length;  /**< Number of simulated steps */
} bio_msg_omni_wm_counterfactual_response_t;

/**
 * @brief Model update message (BIO_MSG_OMNI_WM_UPDATE - 0x6203)
 */
typedef struct {
    bio_message_header_t header;
    float state[OMNI_WM_MAX_STATE_DIM];       /**< Current state */
    uint32_t state_dim;                        /**< State dimensionality */
    float action[OMNI_WM_MAX_ACTION_DIM];     /**< Action taken */
    uint32_t action_dim;                       /**< Action dimensionality */
    float next_state[OMNI_WM_MAX_STATE_DIM];  /**< Resulting state */
    float reward;                              /**< Reward received */
} bio_msg_omni_wm_update_t;

/**
 * @brief Model update acknowledgment message
 */
typedef struct {
    bio_message_header_t header;
    nimcp_error_t status;       /**< Update status */
    float prediction_error;     /**< Error before update */
} bio_msg_omni_wm_update_ack_t;

/**
 * @brief Rollout request message (BIO_MSG_OMNI_WM_ROLLOUT - 0x6204)
 */
typedef struct {
    bio_message_header_t header;
    float initial_state[OMNI_WM_MAX_STATE_DIM]; /**< Starting state */
    uint32_t state_dim;                          /**< State dimensionality */
    float policy_actions[OMNI_WM_MAX_HORIZON * OMNI_WM_MAX_ACTION_DIM]; /**< Action sequence */
    uint32_t action_dim;                         /**< Action dimensionality */
    uint32_t horizon;                            /**< Rollout horizon */
    float preferred_obs[OMNI_WM_MAX_OBS_DIM];   /**< Preferred observations (goal) */
    uint32_t obs_dim;                            /**< Observation dimensionality */
} bio_msg_omni_wm_rollout_t;

/**
 * @brief Rollout response message
 */
typedef struct {
    bio_message_header_t header;
    float total_reward;          /**< Cumulative reward */
    float expected_free_energy;  /**< Expected free energy */
    uint32_t steps_completed;    /**< Actual steps completed */
    float final_state[OMNI_WM_MAX_STATE_DIM]; /**< Final state */
    uint32_t state_dim;                        /**< State dimensionality */
} bio_msg_omni_wm_rollout_response_t;

    union { float f; uint32_t i; } conv;

    union { double d; uint64_t i; } conv;

    union { uint32_t i; float f; } conv;

    union { uint64_t i; double d; } conv;

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- bio_async module --- */
/* omni_wm_connect_bio_async - defined in nimcp_omni_world_model_bio_async.c */
/* omni_wm_disconnect_bio_async - defined in nimcp_omni_world_model_bio_async.c */

/* --- lifecycle module --- */
/* omni_wm_create - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_create_simple - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_destroy - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_mdn_create - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_mdn_destroy - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_cf_query_create - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_cf_query_destroy - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_cf_result_destroy - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_reset_stats - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_symlog - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_symexp - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_symlog_array - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_symexp_array - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_get_default_config - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_generate_dream - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_set_learning_rate - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_what_if - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_direction_to_string - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_learn_mode_to_string - defined in nimcp_omni_world_model_lifecycle.c */
/* omni_wm_cf_type_to_string - defined in nimcp_omni_world_model_lifecycle.c */

/* --- prediction module --- */
/* omni_world_model_training_step - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_rssm_state_create - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_rssm_state_clone - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_rssm_state_destroy - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_get_rssm_state - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_set_rssm_state - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_rssm_step - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_rssm_imagine - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_predict_forward - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_predict_lateral - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_predict_hierarchical - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_latent_create - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_latent_destroy - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_encode - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_decode - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_predict_latent - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_predict_mdn - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_predict_observations - defined in nimcp_omni_world_model_prediction.c */
/* omni_world_model_set_instance_health_agent - defined in nimcp_omni_world_model_prediction.c */
/* omni_world_model_training_begin - defined in nimcp_omni_world_model_prediction.c */
/* omni_world_model_training_end - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_get_state - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_infer_backward - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_mdn_sample - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_evaluate_efe - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_infer_state - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_connect_active_inference - defined in nimcp_omni_world_model_prediction.c */
/* omni_wm_evaluate_policy - defined in nimcp_omni_world_model_prediction.c */

/* --- serialization module --- */
/* omni_wm_serialize - defined in nimcp_omni_world_model_serialization.c */
/* omni_wm_deserialize - defined in nimcp_omni_world_model_serialization.c */
/* omni_wm_save - defined in nimcp_omni_world_model_serialization.c */
/* omni_wm_load - defined in nimcp_omni_world_model_serialization.c */
/* omni_wm_checkpoint - defined in nimcp_omni_world_model_serialization.c */
/* omni_wm_restore_checkpoint - defined in nimcp_omni_world_model_serialization.c */
/* omni_wm_delete_checkpoint - defined in nimcp_omni_world_model_serialization.c */
/* omni_wm_get_checkpoint_count - defined in nimcp_omni_world_model_serialization.c */
/* omni_wm_clear_checkpoints - defined in nimcp_omni_world_model_serialization.c */

/* --- simulation module --- */
/* omni_wm_experience_create - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_experience_destroy - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_add_experience - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_sample_experiences - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_get_replay_size - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_clear_replay - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_counterfactual - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_rollout_create - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_rollout_destroy - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_rollout - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_mdn_mode - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_mdn_log_prob - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_update - defined in nimcp_omni_world_model_simulation.c */
/* omni_wm_dream - defined in nimcp_omni_world_model_simulation.c */

/* --- state module --- */
/* omni_wm_state_create - defined in nimcp_omni_world_model_state.c */
/* omni_wm_state_clone - defined in nimcp_omni_world_model_state.c */
/* omni_wm_state_destroy - defined in nimcp_omni_world_model_state.c */
/* omni_wm_state_from_values - defined in nimcp_omni_world_model_state.c */
/* omni_wm_set_state - defined in nimcp_omni_world_model_state.c */

/* --- stats module --- */
/* omni_wm_get_stats - defined in nimcp_omni_world_model_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_OMNI_WORLD_MODEL_INTERNAL_H */
