/**
 * @file nimcp_plasticity_orchestrator_internal.h
 * @brief Internal shared declarations for nimcp_plasticity_orchestrator SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_PLASTICITY_ORCHESTRATOR_INTERNAL_H
#define NIMCP_PLASTICITY_ORCHESTRATOR_INTERNAL_H

#include "plasticity/nimcp_plasticity_orchestrator.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "plasticity/stdp/nimcp_triplet_stdp.h"
#include "plasticity/bcm/nimcp_bcm.h"
#include "plasticity/homeostatic/nimcp_homeostatic.h"
#include "plasticity/calcium/nimcp_calcium_dynamics.h"
#include "plasticity/structural/nimcp_structural_plasticity.h"
#include "plasticity/metabolic/nimcp_metabolic_plasticity.h"
#include "plasticity/heterosynaptic/nimcp_heterosynaptic.h"
#include "plasticity/astrocyte/nimcp_astrocyte_plasticity.h"
#include "plasticity/protein/nimcp_protein_synthesis.h"
#include "plasticity/metaplasticity/nimcp_extended_metaplasticity.h"
#include "utils/platform/nimcp_platform_mutex.h"
#include "utils/validation/nimcp_common.h"
#include "cognitive/nimcp_sleep_wake.h"
#include "cognitive/immune/nimcp_brain_immune.h"
#include <string.h>
#include <math.h>
#include <stdio.h>
#include "utils/fault_tolerance/nimcp_health_agent_macros.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

 * Internal Structures
 * ============================================================================ */

typedef struct {
    plasticity_event_callback_t callback;
    void* user_data;
    plasticity_event_type_t event_type;
    int id;
    bool active;
} event_callback_entry_t;

typedef struct {
    plasticity_update_callback_t callback;
    void* user_data;
    bool active;
} update_callback_entry_t;

/**
 * @brief Synapse entry in orchestrator
 *
 * Contains all per-synapse plasticity module states
 */
typedef struct {
    uint32_t id;
    uint32_t pre_neuron_id;
    uint32_t post_neuron_id;
    float weight;
    float w_min;
    float w_max;

    /* Module-specific states */
    triplet_stdp_synapse_t* triplet_stdp;
    bcm_synapse_t bcm_state;
    uint32_t structural_synapse_id;  /* ID in structural plasticity system */

    /* Activity tracking */
    uint64_t last_pre_spike_time;
    uint64_t last_post_spike_time;
    uint64_t total_pre_spikes;
    uint64_t total_post_spikes;
    float recent_activity_hz;
    float eligibility_trace;

    /* Consolidation state */
    bool consolidation_tagged;
    float ltp_accumulator;
    float ltd_accumulator;

    bool active;
} synapse_entry_t;

/**
 * @brief Neuron entry in orchestrator
 */
typedef struct {
    uint32_t id;
    float firing_rate;
    float bcm_threshold;
    float target_rate;

    /* Homeostatic state */
    synaptic_scaling_state_t scaling_state;
    intrinsic_plasticity_state_t ip_state;
    metaplasticity_state_t meta_state;

    /* Associated synapses (indices into synapse array) */
    uint32_t* input_synapse_indices;
    uint32_t num_inputs;
    uint32_t input_capacity;

    bool active;
} neuron_entry_t;

/**
 * @brief Internal orchestrator state
 */
struct plasticity_orchestrator_struct {
    /* Configuration */
    plasticity_orchestrator_config_t config;

    /* Synapse and neuron arrays */
    synapse_entry_t* synapses;
    neuron_entry_t* neurons;
    size_t num_synapses;
    size_t num_neurons;
    size_t synapse_capacity;
    size_t neuron_capacity;

    /* Global plasticity modules */
    metabolic_plasticity_t* metabolic;
    calcium_dynamics_t calcium;
    structural_plasticity_system_t* structural;
    hetero_system_t* heterosynaptic;
    astrocyte_plasticity_t astrocyte;
    protein_synthesis_system_t protein_synthesis;
    homeostatic_controller_t homeostatic;
    metaplasticity_controller_t metaplasticity;

    /* Integration handles */
    struct brain_immune_system* immune;
    struct sleep_system_struct* sleep;
    struct neuromodulator_system_struct* neuromod;

    /* Current modulation state */
    sleep_state_t current_sleep_state;
    float sleep_modulation_factor;
    float immune_modulation_factor;
    neuromodulator_levels_t neuromod_levels;

    /* Callbacks */
    event_callback_entry_t event_callbacks[MAX_CALLBACKS];
    update_callback_entry_t pre_update_callbacks[MAX_CALLBACKS];
    update_callback_entry_t post_update_callbacks[MAX_CALLBACKS];
    int next_callback_id;

    /* Statistics */
    plasticity_stats_t stats;

    /* State */
    uint64_t current_time_ms;
    uint64_t last_consolidation_time;
    uint64_t last_homeostatic_time;
    uint64_t last_structural_time;

    /* Bio-async */
    bool bio_async_connected;

    /* Thread safety */
    nimcp_platform_mutex_t* mutex;
};

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- io module --- */
/* plasticity_orchestrator_serialize - defined in nimcp_plasticity_orchestrator_io.c */
/* plasticity_orchestrator_deserialize - defined in nimcp_plasticity_orchestrator_io.c */

/* --- lifecycle module --- */
/* plasticity_orchestrator_create - defined in nimcp_plasticity_orchestrator_lifecycle.c */
/* plasticity_orchestrator_destroy - defined in nimcp_plasticity_orchestrator_lifecycle.c */
/* plasticity_orchestrator_reset_stats - defined in nimcp_plasticity_orchestrator_lifecycle.c */
/* plasticity_orchestrator_default_config - defined in nimcp_plasticity_orchestrator_lifecycle.c */
/* plasticity_orchestrator_connect_immune - defined in nimcp_plasticity_orchestrator_lifecycle.c */
/* plasticity_orchestrator_connect_sleep - defined in nimcp_plasticity_orchestrator_lifecycle.c */
/* plasticity_orchestrator_connect_neuromodulators - defined in nimcp_plasticity_orchestrator_lifecycle.c */
/* plasticity_orchestrator_connect_bio_async - defined in nimcp_plasticity_orchestrator_lifecycle.c */
/* plasticity_orchestrator_register_event_callback - defined in nimcp_plasticity_orchestrator_lifecycle.c */

/* --- stats module --- */
/* plasticity_orchestrator_get_stats - defined in nimcp_plasticity_orchestrator_stats.c */
/* plasticity_orchestrator_get_weight - defined in nimcp_plasticity_orchestrator_stats.c */
/* plasticity_orchestrator_set_weight - defined in nimcp_plasticity_orchestrator_stats.c */
/* plasticity_orchestrator_get_atp_level - defined in nimcp_plasticity_orchestrator_stats.c */
/* plasticity_orchestrator_get_calcium - defined in nimcp_plasticity_orchestrator_stats.c */
/* plasticity_orchestrator_get_threshold - defined in nimcp_plasticity_orchestrator_stats.c */

/* --- stdp module --- */
/* plasticity_orchestrator_pre_spike - defined in nimcp_plasticity_orchestrator_stdp.c */
/* plasticity_orchestrator_post_spike - defined in nimcp_plasticity_orchestrator_stdp.c */
/* plasticity_orchestrator_reward - defined in nimcp_plasticity_orchestrator_stdp.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_PLASTICITY_ORCHESTRATOR_INTERNAL_H */
