/**
 * @file nimcp_swarm_brain_internal.h
 * @brief Internal shared declarations for nimcp_swarm_brain SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_SWARM_BRAIN_INTERNAL_H
#define NIMCP_SWARM_BRAIN_INTERNAL_H

#include "swarm/nimcp_swarm_brain.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "swarm/nimcp_swarm_signal.h"
#include "core/brain/nimcp_brain.h"
#include "utils/validation/nimcp_common.h"
#include "utils/time/nimcp_time.h"
#include "utils/platform/nimcp_platform_mutex.h"
#include "api/nimcp_api_exception.h"
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_messages.h"
#include "cognitive/knowledge/nimcp_kg_reader.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include "utils/fault_tolerance/nimcp_health_agent_macros.h"
#include "constants/nimcp_buffer_constants.h"
#include "constants/nimcp_timing_constants.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

//=============================================================================
// Internal Structures
//=============================================================================

/**
 * @brief Active vote tracking
 */
typedef struct {
    vote_proposal_t proposal;         // The proposal being voted on
    uint32_t votes_for;               // Count of approve votes
    uint32_t votes_against;           // Count of reject votes
    uint32_t votes_abstain;           // Count of abstain votes
    uint64_t expiry_ms;               // When vote expires
    bool active;                      // Vote is active
    bool completed;                   // Vote has completed
    vote_decision_t result;           // Final result
} active_vote_t;

/**
 * @brief Collective workspace implementation
 */
typedef struct {
    workspace_entry_t* entries;       // Workspace entries
    uint32_t size;                    // Number of entries
    uint64_t last_update_ms;          // Last update time
    float coherence;                  // Overall coherence
    nimcp_mutex_t* lock;              // Thread safety
} collective_workspace_t;

/**
 * @brief Emergence context
 */
typedef struct {
    swarm_emergence_tier_t current_tier;  // Current tier
    uint32_t tier_change_count;           // Number of tier changes
    uint64_t tier_enter_time_ms;          // Time entered current tier
    float coherence_history[10];          // Recent coherence values
    uint32_t coherence_index;             // Circular buffer index
} emergence_context_t;

/**
 * @brief Consensus context
 */
typedef struct {
    active_vote_t votes[MAX_ACTIVE_VOTES]; // Active votes
    uint32_t vote_count;                   // Number of active votes
    uint32_t total_votes_completed;        // Total completed
    nimcp_mutex_t* lock;                   // Thread safety
} consensus_context_t;

//=============================================================================
// Local Brain Instantiation Implementation (Features 1-4)
//=============================================================================

/**
 * @brief Local brain instance tracking
 */
typedef struct {
    brain_t brain;                    // Brain instance
    uint16_t agent_id;                // Agent ID
    swarm_local_brain_config_t config;// Brain configuration
    bool active;                      // Is active
    uint64_t creation_time_ms;        // Creation timestamp
    uint64_t last_sync_ms;            // Last sync time
} local_brain_instance_t;

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- consensus module --- */

/* --- coordination module --- */
/* swarm_brain_sync_neuromodulators - defined in nimcp_swarm_brain_coordination.c */
/* swarm_brain_sync_weights - defined in nimcp_swarm_brain_coordination.c */
/* swarm_brain_broadcast_perception - defined in nimcp_swarm_brain_coordination.c */
/* swarm_brain_broadcast_threat - defined in nimcp_swarm_brain_coordination.c */
/* swarm_brain_propose_action - defined in nimcp_swarm_brain_coordination.c */
/* swarm_brain_collective_learn - defined in nimcp_swarm_brain_coordination.c */

/* --- lifecycle module --- */
/* swarm_brain_create - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_destroy - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_reset_stats - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_create_local - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_migration_checkpoint_destroy - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_default_config - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_join - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_leave - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_process - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_message_type_string - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_is_operational - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_migrate - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_restore_migration - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_query_self_knowledge - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_get_capabilities - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_get_integrations - defined in nimcp_swarm_brain_lifecycle.c */
/* swarm_brain_query_peer_knowledge - defined in nimcp_swarm_brain_lifecycle.c */

/* --- stats module --- */
/* swarm_brain_get_stats - defined in nimcp_swarm_brain_stats.c */
/* swarm_brain_get_emergence_tier - defined in nimcp_swarm_brain_stats.c */
/* swarm_brain_get_workspace - defined in nimcp_swarm_brain_stats.c */
/* swarm_brain_get_peers - defined in nimcp_swarm_brain_stats.c */
/* swarm_brain_get_local_brain - defined in nimcp_swarm_brain_stats.c */
/* swarm_emergence_tier_string - defined in nimcp_swarm_brain_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_SWARM_BRAIN_INTERNAL_H */
