/**
 * @file nimcp_swarm_consciousness_internal.h
 * @brief Internal shared declarations for nimcp_swarm_consciousness SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_SWARM_CONSCIOUSNESS_INTERNAL_H
#define NIMCP_SWARM_CONSCIOUSNESS_INTERNAL_H

#include "swarm/nimcp_swarm_consciousness.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "security/nimcp_bbb_helpers.h"
#include "api/nimcp_api_exception.h"
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_messages.h"
#include "async/nimcp_bio_router.h"
#include "async/nimcp_wiring_helpers.h"
#include "cognitive/imagination/nimcp_imagination_callbacks.h"
#include "cognitive/knowledge/nimcp_kg_reader.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdatomic.h>
#include <pthread.h>
#include <unistd.h>
#include <time.h>
#include "utils/thread/nimcp_thread.h"
#include "utils/fault_tolerance/nimcp_health_agent_macros.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

/* Note: BIO_MSG_SWARM_CONSCIOUSNESS_UPDATE defined in header (0x0700) */

//=============================================================================
// Internal Context Structure
//=============================================================================

/**
 * WHAT: Internal swarm consciousness context
 * WHY:  Track collective consciousness state and monitoring
 * HOW:  Stores configuration, metrics, history, and bio-async state
 */
typedef struct swarm_consciousness_ctx {
    uint32_t magic;                          /**< Magic for validation */
    swarm_consciousness_config_t config;     /**< Configuration */
    swarm_consciousness_metrics_t* current_metrics; /**< Current metrics */
    consciousness_scaling_model_t scaling_model; /**< Scaling model parameters */
    nimcp_mutex_t lock;                    /**< Thread safety */

    // Monitoring state
    bool monitoring_active;                  /**< Is monitoring thread running? */
    pthread_t monitor_thread;                /**< Monitoring thread handle */
    void (*callback)(const swarm_consciousness_metrics_t*, void*); /**< User callback */
    void* user_data;                         /**< User callback context */

    // Bio-async integration
    bool bio_async_registered;               /**< Bio-async active? */
    bio_module_context_t bio_module_ctx;     /**< Bio-router module context */

    // Imagination integration (collective creativity)
    imagination_collective_receive_callback_t collective_imagination_callback; /**< Callback for received imagination */
    void* collective_imagination_user_data;  /**< User data for imagination callback */
    bool imagination_handler_registered;     /**< Imagination handler active? */

    // History for trend analysis
    float phi_history[PHI_HISTORY_SIZE];     /**< Recent phi values */
    uint32_t history_index;                  /**< Circular buffer index */
    uint32_t history_count;                  /**< Valid history entries */

    // Statistics
    uint64_t total_computations;             /**< Total phi computations */
    uint64_t state_transitions;              /**< State change count */
    uint64_t creation_time_ms;               /**< Context creation time */

    // Swarm brain reference for monitoring
    swarm_brain_t* swarm_brain;              /**< Associated swarm brain */

} swarm_consciousness_ctx_t;

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- collective module --- */
/* swarm_consciousness_share_imagination - defined in nimcp_swarm_consciousness_collective.c */

/* --- lifecycle module --- */
/* swarm_consciousness_create - defined in nimcp_swarm_consciousness_lifecycle.c */
/* swarm_consciousness_destroy - defined in nimcp_swarm_consciousness_lifecycle.c */
/* swarm_consciousness_metrics_free - defined in nimcp_swarm_consciousness_lifecycle.c */
/* swarm_consciousness_stop_monitoring - defined in nimcp_swarm_consciousness_lifecycle.c */
/* swarm_consciousness_default_config - defined in nimcp_swarm_consciousness_lifecycle.c */
/* swarm_consciousness_state_name - defined in nimcp_swarm_consciousness_lifecycle.c */

/* --- phi module --- */
/* swarm_compute_collective_phi - defined in nimcp_swarm_consciousness_phi.c */
/* swarm_classify_collective_phi - defined in nimcp_swarm_consciousness_phi.c */
/* swarm_brain_get_collective_phi - defined in nimcp_swarm_consciousness_phi.c */
/* swarm_predict_phi_for_size - defined in nimcp_swarm_consciousness_phi.c */
/* swarm_compute_network_integration - defined in nimcp_swarm_consciousness_phi.c */
/* phi_aggregation_method_name - defined in nimcp_swarm_consciousness_phi.c */
/* swarm_brain_enable_consciousness_monitoring - defined in nimcp_swarm_consciousness_phi.c */
/* swarm_brain_disable_consciousness_monitoring - defined in nimcp_swarm_consciousness_phi.c */
/* swarm_brain_is_conscious - defined in nimcp_swarm_consciousness_phi.c */
/* swarm_fit_scaling_model - defined in nimcp_swarm_consciousness_phi.c */
/* swarm_consciousness_register_bio_async - defined in nimcp_swarm_consciousness_phi.c */
/* swarm_consciousness_bbb_validate - defined in nimcp_swarm_consciousness_phi.c */

/* --- stats module --- */
/* swarm_consciousness_get_metrics - defined in nimcp_swarm_consciousness_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_SWARM_CONSCIOUSNESS_INTERNAL_H */
