/**
 * @file nimcp_mirror_neurons_internal.h
 * @brief Internal shared declarations for nimcp_mirror_neurons SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_MIRROR_NEURONS_INTERNAL_H
#define NIMCP_MIRROR_NEURONS_INTERNAL_H

#include "cognitive/nimcp_mirror_neurons.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "security/nimcp_security.h"
#include "security/nimcp_blood_brain_barrier.h"
#include "cognitive/knowledge/nimcp_kg_reader.h"
#include "utils/memory/nimcp_unified_memory.h"
#include "cognitive/mirror_neurons/nimcp_mirror_substrate.h"  // Substrate integration (Phase 10.11.2)
#include "cognitive/mirror_neurons/nimcp_mirror_stdp.h"       // STDP learning (Phase 10.11.4)
#include "cognitive/mirror_neurons/nimcp_mirror_resonance.h"  // Motor resonance (Phase 10.11.5)
#include "cognitive/mirror_neurons/nimcp_mirror_hierarchy.h"  // Hierarchical goals (Phase 10.11.6)
#include "utils/time/nimcp_time.h"
#include "plasticity/neuromodulators/nimcp_neuromodulators.h"  // Neuromodulator integration
#include "core/brain/nimcp_brain.h"  // Brain reference
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_messages.h"
#include "async/nimcp_bio_router.h"
#include "async/nimcp_wiring_helpers.h"
#include "nimcp.h"  // For error codes
#include "cognitive/mirror_neurons/nimcp_mirror_snn_bridge.h"
#include "cognitive/mirror_neurons/nimcp_mirror_plasticity_bridge.h"
#include "utils/bridge/nimcp_bridge_boilerplate.h"
#include "mesh/nimcp_mesh_participant.h"
#include "mesh/nimcp_mesh_adapter.h"
#include "constants/nimcp_buffer_constants.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

//=============================================================================
// Internal Data Structures
//=============================================================================

/**
 * @brief Single mirror neuron unit
 *
 * WHAT: Represents one mirror neuron with dual observation/execution pathways
 * WHY:  Enable shared representation for observed and executed actions
 * HOW:  Combines cognitive state with optional biological substrate backing
 */
typedef struct {
    uint32_t neuron_id;                /**< Unique neuron identifier */
    uint32_t action_id;                /**< Action this neuron represents */

    // Dual pathways
    float observation_activation;      /**< Current observation activation */
    float execution_activation;        /**< Current execution activation */

    // Learning state
    float association_weight;          /**< Obs-exec association strength */
    uint32_t observation_count;        /**< Times activated by observation */
    uint32_t execution_count;          /**< Times activated by execution */

    // Feature representation
    /* P3-COG-06: Named constant for max features */
    float action_features[MIRROR_MAX_FEATURES];  /**< Learned action features */
    uint32_t num_features;             /**< Number of features */

    // Temporal state
    uint64_t last_observation_time;    /**< Last observation activation */
    uint64_t last_execution_time;      /**< Last execution activation */

    // Phase 10.11.2: Substrate integration
    mirror_substrate_backing_t* substrate; /**< Biological substrate backing (NULL = abstract mode) */
    bool has_substrate;                /**< True if substrate backing is active */

} mirror_neuron_unit_t;

/**
 * @brief Action-to-neuron mapping entry
 *
 * WHAT: Maps action IDs to corresponding mirror neuron populations
 * WHY:  Enable fast lookup of neurons for a given action
 */
typedef struct {
    uint32_t action_id;
    char action_name[NIMCP_ID_BUFFER_SIZE];
    uint32_t* neuron_indices;          /**< Array of neuron indices */
    uint32_t num_neurons;              /**< Number of neurons for this action */
    uint32_t capacity;                 /**< Allocated capacity */

    // Statistics
    uint32_t total_observations;
    uint32_t total_executions;
    float avg_similarity;              /**< Average obs-exec similarity */

} action_mapping_t;

/**
 * @brief Observed agent tracking
 *
 * WHAT: Track information about observed agents
 * WHY:  Enable multi-agent learning and agent-specific adaptation
 */
typedef struct {
    uint32_t agent_id;
    uint32_t observation_count;
    uint64_t last_observation_time;
    float trust_score;                 /**< Agent reliability (0.0-1.0) */
} agent_info_t;

/**
 * @brief Main mirror neuron system structure
 *
 * WHAT: Complete mirror neuron system state
 * WHY:  Encapsulate all data for observation-based learning
 * HOW:  Combines cognitive infrastructure with biological substrate integration
 */
struct mirror_neurons_system {
    // Configuration
    mirror_neuron_config_t config;

    // Neuron population
    mirror_neuron_unit_t* neurons;
    uint32_t num_neurons;

    // Action mappings
    action_mapping_t* actions;
    uint32_t num_actions;
    uint32_t actions_capacity;

    // Agent tracking
    agent_info_t* agents;
    uint32_t num_agents;
    uint32_t agents_capacity;

    // Statistics (atomic for thread-safety)
    mirror_neuron_stats_t stats;

    // Integration handles
    void* working_memory;              /**< Working memory system */
    void* theory_of_mind;              /**< Theory of mind system */
    void* predictive_network;          /**< Predictive network */
    void* glial_integration;           /**< Glial cell integration (Phase 10.11.1) */
    brain_t brain;                     /**< Brain reference for neuromodulation */

    // Temporal state
    uint64_t creation_time;
    uint64_t last_update_time;

    // Memory management
    bool initialized;

    // P2-COG-08: Thread safety mutex
    nimcp_mutex_t* mutex;

    // Phase 10.11.2: Substrate integration
    mirror_substrate_config_t substrate_config;   /**< Substrate configuration */
    mirror_substrate_pool_t* substrate_pool;      /**< Memory pool for substrate backings */
    bool substrate_enabled;                       /**< True if substrate mode active */

    // Phase 10.11.2: Network integration handles
    void* axon_network;                /**< Axon network for propagation delays */
    void* dendrite_network;            /**< Dendrite network for spine plasticity */
    void* myelin_network;              /**< Myelin sheath network for myelination */

    // Phase 10.11.4-6: Enhancement systems
    void* stdp_system;                 /**< STDP learning system */
    void* resonance_system;            /**< Motor resonance system */
    void* hierarchy_system;            /**< Goal-motor hierarchy system */
    bool stdp_enabled;                 /**< True if STDP enabled */
    bool resonance_enabled;            /**< True if resonance enabled */
    bool hierarchy_enabled;            /**< True if hierarchy enabled */

    // Bio-async integration
    bio_module_context_t bio_ctx;      /**< Bio-async module context */
    bool bio_async_enabled;            /**< Bio-async registration status */

    // SNN and Plasticity bridge integration
    mirror_snn_bridge_t* snn_bridge;           /**< SNN bridge for spike-based computation */
    mirror_plasticity_bridge_t* plasticity_bridge; /**< Plasticity bridge for learning rules */
    bool bridges_enabled;                      /**< True if bridges are active */
};

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- io module --- */
/* mirror_neurons_save - defined in nimcp_mirror_neurons_io.c */
/* mirror_neurons_load - defined in nimcp_mirror_neurons_io.c */
/* mirror_neurons_get_all_activations - defined in nimcp_mirror_neurons_io.c */

/* --- learning module --- */
/* mirror_neurons_learn_demonstration - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_set_learning_context - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_should_imitate - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_get_activation - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_match_actions - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_update_associations - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_get_stdp - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_set_stdp_dopamine - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_enable_resonance - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_get_resonance - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_enable_hierarchy - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_get_hierarchy - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_infer_goal - defined in nimcp_mirror_neurons_learning.c */
/* mirror_neurons_select_goal - defined in nimcp_mirror_neurons_learning.c */

/* --- lifecycle module --- */
/* mirror_neurons_create_action - defined in nimcp_mirror_neurons_lifecycle.c */
/* mirror_neurons_create - defined in nimcp_mirror_neurons_lifecycle.c */
/* mirror_neurons_destroy - defined in nimcp_mirror_neurons_lifecycle.c */
/* mirror_neurons_get_default_config - defined in nimcp_mirror_neurons_lifecycle.c */
/* mirror_neurons_set_brain - defined in nimcp_mirror_neurons_lifecycle.c */

/* --- simulation module --- */
/* mirror_neurons_observe_action - defined in nimcp_mirror_neurons_simulation.c */
/* mirror_neurons_execute_action - defined in nimcp_mirror_neurons_simulation.c */

/* --- social module --- */
/* mirror_neurons_integrate_theory_of_mind - defined in nimcp_mirror_neurons_social.c */
/* mirror_neurons_get_social_salience - defined in nimcp_mirror_neurons_social.c */
/* mirror_neurons_set_social_context - defined in nimcp_mirror_neurons_social.c */
/* mirror_neurons_predict_next_action - defined in nimcp_mirror_neurons_social.c */
/* mirror_neurons_integrate_working_memory - defined in nimcp_mirror_neurons_social.c */
/* mirror_neurons_integrate_predictive - defined in nimcp_mirror_neurons_social.c */
/* mirror_neurons_integrate_glial - defined in nimcp_mirror_neurons_social.c */
/* mirror_neurons_activate_observation_mode - defined in nimcp_mirror_neurons_social.c */
/* mirror_neurons_has_recent_observations - defined in nimcp_mirror_neurons_social.c */

/* --- stats module --- */
/* mirror_neurons_get_stats - defined in nimcp_mirror_neurons_stats.c */
/* mirror_neurons_decay_activations - defined in nimcp_mirror_neurons_stats.c */
/* mirror_neurons_get_activation_record - defined in nimcp_mirror_neurons_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_MIRROR_NEURONS_INTERNAL_H */
