/**
 * @file nimcp_hypergraph_internal.h
 * @brief Internal shared declarations for nimcp_hypergraph SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_HYPERGRAPH_INTERNAL_H
#define NIMCP_HYPERGRAPH_INTERNAL_H

#include "cognitive/neuro_symbolic/nimcp_hypergraph.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "utils/time/nimcp_time.h"
#include "utils/bridge/nimcp_bridge_boilerplate.h"
#include "mesh/nimcp_mesh_participant.h"
#include "mesh/nimcp_mesh_adapter.h"
#include <string.h>
#include <math.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- lifecycle module --- */
/* nimcp_hypergraph_create - defined in nimcp_hypergraph_lifecycle.c */
/* nimcp_hypergraph_create_with_config - defined in nimcp_hypergraph_lifecycle.c */
/* nimcp_hypergraph_destroy - defined in nimcp_hypergraph_lifecycle.c */
/* nimcp_hypergraph_dual_destroy - defined in nimcp_hypergraph_lifecycle.c */
/* nimcp_hypergraph_clear - defined in nimcp_hypergraph_lifecycle.c */
/* nimcp_hypergraph_transversal - defined in nimcp_hypergraph_lifecycle.c */

/* --- reasoning module --- */
/* nimcp_hypergraph_pattern_query - defined in nimcp_hypergraph_reasoning.c */
/* nimcp_hypergraph_query_result_init - defined in nimcp_hypergraph_reasoning.c */
/* nimcp_hypergraph_query_result_cleanup - defined in nimcp_hypergraph_reasoning.c */
/* nimcp_hypergraph_from_knowledge_base - defined in nimcp_hypergraph_reasoning.c */
/* nimcp_hypergraph_from_ternary - defined in nimcp_hypergraph_reasoning.c */
/* nimcp_hypergraph_to_ternary - defined in nimcp_hypergraph_reasoning.c */

/* --- stats module --- */
/* nimcp_hypergraph_get_stats - defined in nimcp_hypergraph_stats.c */
/* nimcp_hypergraph_unregister_bio_async - defined in nimcp_hypergraph_stats.c */

/* --- structure module --- */
/* nimcp_hypergraph_add_vertex - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_add_vertex_with_data - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_remove_vertex - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_add_edge - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_add_edge_full - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_remove_edge - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_get_edge - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_get_incident_edges - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_get_edges_by_type - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_update_edge_weight - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_contract_edge - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_extend_edge - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_shrink_edge - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_find_edges_containing - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_are_connected - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_connected_components - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_is_connected - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_edge_count - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_get_default_config - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_get_vertex - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_find_vertex - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_update_vertex_confidence - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_compute_dual - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_all_transversals - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_get_neighbors - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_to_tensor - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_register_bio_async - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_vertex_count - defined in nimcp_hypergraph_structure.c */
/* nimcp_hypergraph_print_diagnostics - defined in nimcp_hypergraph_structure.c */
/* hypergraph_set_instance_health_agent - defined in nimcp_hypergraph_structure.c */
/* hypergraph_training_begin - defined in nimcp_hypergraph_structure.c */
/* hypergraph_training_end - defined in nimcp_hypergraph_structure.c */
/* hypergraph_training_step - defined in nimcp_hypergraph_structure.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_HYPERGRAPH_INTERNAL_H */
