/**
 * @file nimcp_working_memory_internal.h
 * @brief Internal shared declarations for nimcp_working_memory SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_WORKING_MEMORY_INTERNAL_H
#define NIMCP_WORKING_MEMORY_INTERNAL_H

#include "cognitive/nimcp_working_memory.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "utils/bridge/nimcp_bridge_boilerplate.h"
#include "mesh/nimcp_mesh_participant.h"
#include "mesh/nimcp_mesh_adapter.h"
#include "constants/nimcp_dimension_constants.h"
#include "constants/nimcp_buffer_constants.h"
#include "utils/bridge/nimcp_bridge_base.h"
#include "plasticity/nimcp_second_messengers.h"
#include "security/nimcp_security.h"
#include "security/nimcp_blood_brain_barrier.h"
#include "api/nimcp_api_exception.h"
#include "cognitive/global_workspace/nimcp_global_workspace.h"  // Global Workspace integration
#include "cognitive/immune/nimcp_brain_immune.h"  // Brain immune integration (cytokine enums)
#include "cognitive/nimcp_sleep_wake.h"  // Sleep state integration
#include "cognitive/working_memory/nimcp_working_memory_sleep_bridge.h"  // Sleep bridge for modulation
#include "core/brain/nimcp_brain_kg_helpers.h"  // KG self-awareness integration
#include "cognitive/memory/nimcp_working_memory_quantum_bridge.h"  // Quantum retrieval bridge
#include "cognitive/memory/nimcp_working_memory_snn_bridge.h"      // SNN bridge
#include "cognitive/memory/nimcp_working_memory_plasticity_bridge.h"  // Plasticity bridge
#include "nimcp.h"  // For error codes
#include "utils/error/nimcp_error_codes.h"  // For NIMCP_CHECK_NULL macros
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_router.h"
#include "async/nimcp_bio_messages.h"
#include "async/nimcp_wiring_helpers.h"
#include "utils/memory/nimcp_unified_memory.h"
#include "utils/time/nimcp_time.h"
#include "utils/platform/nimcp_platform_mutex.h"  // Thread safety
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdio.h>
#include "utils/memory/nimcp_memory_guards.h"  // For nimcp_calloc/nimcp_free

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- lifecycle module --- */
/* working_memory_create - defined in nimcp_working_memory_lifecycle.c */
/* working_memory_create_custom - defined in nimcp_working_memory_lifecycle.c */
/* working_memory_destroy - defined in nimcp_working_memory_lifecycle.c */
/* working_memory_default_config - defined in nimcp_working_memory_lifecycle.c */
/* working_memory_add - defined in nimcp_working_memory_lifecycle.c */

/* --- retrieval module --- */
/* working_memory_decay - defined in nimcp_working_memory_retrieval.c */

/* --- stats module --- */
/* working_memory_get_stats - defined in nimcp_working_memory_stats.c */
/* working_memory_find_lowest_salience - defined in nimcp_working_memory_stats.c */
/* working_memory_encode_positions - defined in nimcp_working_memory_stats.c */
/* working_memory_get_position_embedding - defined in nimcp_working_memory_stats.c */

/* --- store module --- */
/* working_memory_get_capacity - defined in nimcp_working_memory_store.c */
/* working_memory_get_effective_capacity - defined in nimcp_working_memory_store.c */
/* working_memory_get_last_error - defined in nimcp_working_memory_store.c */
/* working_memory_get_size - defined in nimcp_working_memory_store.c */
/* working_memory_get_count - defined in nimcp_working_memory_store.c */
/* working_memory_get_utilization - defined in nimcp_working_memory_store.c */
/* working_memory_is_full - defined in nimcp_working_memory_store.c */
/* working_memory_find_highest_salience - defined in nimcp_working_memory_store.c */
/* working_memory_connect_immune - defined in nimcp_working_memory_store.c */
/* working_memory_disconnect_immune - defined in nimcp_working_memory_store.c */
/* working_memory_is_immune_impaired - defined in nimcp_working_memory_store.c */
/* working_memory_signal_stress - defined in nimcp_working_memory_store.c */
/* working_memory_set_sleep_state - defined in nimcp_working_memory_store.c */
/* working_memory_get_sleep_state - defined in nimcp_working_memory_store.c */
/* working_memory_is_empty - defined in nimcp_working_memory_store.c */

/* --- update module --- */
/* working_memory_refresh - defined in nimcp_working_memory_update.c */
/* working_memory_get_emotion - defined in nimcp_working_memory_update.c */
/* working_memory_get_total_salience - defined in nimcp_working_memory_update.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_WORKING_MEMORY_INTERNAL_H */
