/**
 * @file nimcp_rcog_engine_internal.h
 * @brief Internal shared declarations for nimcp_rcog_engine SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_RCOG_ENGINE_INTERNAL_H
#define NIMCP_RCOG_ENGINE_INTERNAL_H

#include "cognitive/recursive/nimcp_rcog_engine.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "cognitive/recursive/nimcp_rcog_context_store.h"
#include "cognitive/recursive/nimcp_rcog_orchestrator.h"
#include "cognitive/recursive/nimcp_rcog_delegation_pool.h"
#include "cognitive/recursive/nimcp_rcog_tool_router.h"
#include "cognitive/recursive/nimcp_rcog_answer.h"
#include "cognitive/recursive/nimcp_rcog_bio_async_bridge.h"
#include "cognitive/recursive/nimcp_rcog_immune_bridge.h"
#include "cognitive/recursive/nimcp_rcog_imagination_bridge.h"
#include "cognitive/recursive/nimcp_rcog_collective_bridge.h"
#include "cognitive/recursive/nimcp_rcog_brain_kg_bridge.h"
#include "cognitive/recursive/nimcp_rcog_snn_bridge.h"
#include "cognitive/recursive/nimcp_rcog_plasticity_bridge.h"
#include "utils/thread/nimcp_thread.h"
#include "utils/time/nimcp_time.h"
#include "cognitive/knowledge/nimcp_kg_reader.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "utils/bridge/nimcp_bridge_boilerplate.h"
#include "mesh/nimcp_mesh_participant.h"
#include "mesh/nimcp_mesh_adapter.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

 * INTERNAL STRUCTURES
 *===========================================================================*/

/**
 * @brief Active request tracking
 */
typedef struct {
    rcog_request_handle_t* handle;
    rcog_process_request_t request;
    rcog_decomposition_t decomp;
    rcog_batch_handle_t* batch;
    rcog_answer_state_t* answer;
    uint64_t started_ms;
    bool active;
} rcog_active_request_t;

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- execution module --- */
/* rcog_engine_training_step - defined in nimcp_rcog_engine_execution.c */
/* rcog_engine_process - defined in nimcp_rcog_engine_execution.c */
/* rcog_engine_process_ex - defined in nimcp_rcog_engine_execution.c */
/* rcog_engine_process_async - defined in nimcp_rcog_engine_execution.c */
/* rcog_engine_set_instance_health_agent - defined in nimcp_rcog_engine_execution.c */
/* rcog_engine_training_begin - defined in nimcp_rcog_engine_execution.c */
/* rcog_engine_training_end - defined in nimcp_rcog_engine_execution.c */
/* rcog_engine_connect_bio_async - defined in nimcp_rcog_engine_execution.c */
/* rcog_engine_connect_immune - defined in nimcp_rcog_engine_execution.c */
/* rcog_engine_connect_imagination - defined in nimcp_rcog_engine_execution.c */
/* rcog_engine_connect_collective - defined in nimcp_rcog_engine_execution.c */
/* rcog_engine_connect_brain_kg - defined in nimcp_rcog_engine_execution.c */
/* rcog_engine_await - defined in nimcp_rcog_engine_execution.c */

/* --- lifecycle module --- */
/* rcog_engine_create - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_create_default - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_init - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_start - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_stop - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_destroy - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_free_handle - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_free_result - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_reset_stats - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_create_goal - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_default_config - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_get_state - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_cancel - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_get_progress - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_default_request - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_state_name - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_is_ready - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_has_capacity - defined in nimcp_rcog_engine_lifecycle.c */
/* rcog_engine_query_self_knowledge - defined in nimcp_rcog_engine_lifecycle.c */

/* --- stack module --- */
/* rcog_engine_set_context - defined in nimcp_rcog_engine_stack.c */
/* rcog_engine_get_context - defined in nimcp_rcog_engine_stack.c */
/* rcog_engine_query_context - defined in nimcp_rcog_engine_stack.c */
/* rcog_engine_clear_context - defined in nimcp_rcog_engine_stack.c */
/* rcog_engine_clear_all_context - defined in nimcp_rcog_engine_stack.c */
/* rcog_engine_register_tool - defined in nimcp_rcog_engine_stack.c */
/* rcog_engine_unregister_tool - defined in nimcp_rcog_engine_stack.c */
/* rcog_engine_list_tools - defined in nimcp_rcog_engine_stack.c */
/* rcog_engine_apply_immune_modulation - defined in nimcp_rcog_engine_stack.c */

/* --- stats module --- */
/* rcog_engine_get_stats - defined in nimcp_rcog_engine_stats.c */
/* rcog_engine_get_immune_modulation - defined in nimcp_rcog_engine_stats.c */
/* rcog_engine_enter_degraded_mode - defined in nimcp_rcog_engine_stats.c */
/* rcog_engine_exit_degraded_mode - defined in nimcp_rcog_engine_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_RCOG_ENGINE_INTERNAL_H */
