/**
 * @file nimcp_rcog_orchestrator_internal.h
 * @brief Internal shared declarations for nimcp_rcog_orchestrator SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_RCOG_ORCHESTRATOR_INTERNAL_H
#define NIMCP_RCOG_ORCHESTRATOR_INTERNAL_H

#include "cognitive/recursive/nimcp_rcog_orchestrator.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "cognitive/recursive/nimcp_rcog_context_store.h"
#include "cognitive/recursive/nimcp_rcog_answer.h"
#include "cognitive/recursive/nimcp_rcog_imagination_bridge.h"
#include "cognitive/recursive/nimcp_rcog_immune_bridge.h"
#include "utils/thread/nimcp_thread.h"
#include "utils/platform/nimcp_platform_time.h"
#include "utils/algorithms/nimcp_sort.h"
#include "utils/algorithms/nimcp_monte_carlo.h"
#include "cognitive/knowledge/nimcp_kg_reader.h"
#include <string.h>
#include <stdio.h>
#include "utils/bridge/nimcp_bridge_boilerplate.h"
#include "mesh/nimcp_mesh_participant.h"
#include "mesh/nimcp_mesh_adapter.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

 * INTERNAL STRUCTURES
 *===========================================================================*/

/**
 * @brief Active decomposition tracking
 */
typedef struct {
    uint64_t decomp_id;
    rcog_decomposition_t* decomp;
    bool in_use;
} rcog_active_decomp_t;

/**
 * @brief Batch handle for tracking dispatched subtasks
 */
struct rcog_batch_handle {
    uint64_t batch_id;               /**< Unique batch identifier */
    uint64_t* task_ids;              /**< Array of dispatched task IDs */
    size_t num_tasks;                /**< Number of tasks in batch */
    size_t capacity;                 /**< Capacity of task_ids array */
    rcog_subtask_status_t* statuses; /**< Status of each task */
    size_t completed_count;          /**< Number of completed tasks */
    bool all_done;                   /**< True when all tasks complete */
    uint64_t created_ms;             /**< Creation timestamp */
};

 * MCTS STRATEGY SELECTION
 *===========================================================================*/

/**
 * @brief State for MCTS strategy selection
 */
typedef struct {
    rcog_goal_type_t goal_type;
    uint32_t num_context_refs;
    uint32_t current_depth;
    uint32_t max_depth;
    rcog_decomposition_strategy_t selected_strategy;
    float estimated_confidence;
    float complexity;
} rcog_mcts_state_t;

/**
 * @brief User data for MCTS callbacks
 */
typedef struct {
    rcog_orchestrator_t* orch;
    const rcog_goal_t* goal;
} rcog_mcts_user_data_t;

 * TOPOLOGICAL SORT CALLBACKS (for nimcp_sort.h API)
 *===========================================================================*/

/**
 * @brief Context for topological sort callbacks
 */
typedef struct {
    const rcog_decomposition_t* decomp;
    uint32_t* in_degrees;  /* Precomputed in-degrees */
} rcog_topo_context_t;

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- lifecycle module --- */
/* rcog_orchestrator_create - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_create_default - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_destroy - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_free_decomposition - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_destroy_sub - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_reset_stats - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_free_trace - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_connect_context_store - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_connect_answer_refiner - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_connect_delegation_pool - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_connect_imagination - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_connect_immune - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_connect_engine - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_decompose - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_decompose_with_strategy - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_decompose_with_hints - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_dispatch - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_dispatch_subtask - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_await_batch - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_aggregate - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_spawn_sub - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_get_trace - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_clear_trace - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_validate_decomposition - defined in nimcp_rcog_orchestrator_lifecycle.c */
/* rcog_orchestrator_get_topological_order - defined in nimcp_rcog_orchestrator_lifecycle.c */

/* --- monitoring module --- */
/* rcog_orchestrator_get_current_depth - defined in nimcp_rcog_orchestrator_monitoring.c */
/* rcog_orchestrator_get_max_depth - defined in nimcp_rcog_orchestrator_monitoring.c */
/* rcog_orchestrator_would_exceed_depth - defined in nimcp_rcog_orchestrator_monitoring.c */
/* rcog_orchestrator_push_depth - defined in nimcp_rcog_orchestrator_monitoring.c */
/* rcog_orchestrator_pop_depth - defined in nimcp_rcog_orchestrator_monitoring.c */
/* rcog_orchestrator_get_effective_limits - defined in nimcp_rcog_orchestrator_monitoring.c */
/* rcog_orchestrator_default_config - defined in nimcp_rcog_orchestrator_monitoring.c */
/* rcog_orchestrator_refine - defined in nimcp_rcog_orchestrator_monitoring.c */
/* rcog_orchestrator_is_answer_ready - defined in nimcp_rcog_orchestrator_monitoring.c */
/* rcog_orchestrator_apply_immune_modulation - defined in nimcp_rcog_orchestrator_monitoring.c */
/* rcog_orchestrator_select_strategy - defined in nimcp_rcog_orchestrator_monitoring.c */
/* rcog_orchestrator_recommend_strategies - defined in nimcp_rcog_orchestrator_monitoring.c */

/* --- scheduling module --- */
/* rcog_orchestrator_training_step - defined in nimcp_rcog_orchestrator_scheduling.c */
/* rcog_orchestrator_training_end - defined in nimcp_rcog_orchestrator_scheduling.c */

/* --- stats module --- */
/* rcog_orchestrator_get_stats - defined in nimcp_rcog_orchestrator_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_RCOG_ORCHESTRATOR_INTERNAL_H */
