/**
 * @file nimcp_systems_consolidation_internal.h
 * @brief Internal shared declarations for nimcp_systems_consolidation SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_SYSTEMS_CONSOLIDATION_INTERNAL_H
#define NIMCP_SYSTEMS_CONSOLIDATION_INTERNAL_H

#include "cognitive/memory/nimcp_systems_consolidation.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "cognitive/knowledge/nimcp_kg_reader.h"
#include "security/nimcp_security.h"
#include "security/nimcp_blood_brain_barrier.h"
#include "cognitive/memory/nimcp_engram.h"
#include <stddef.h>  /* for NULL */
#include "nimcp.h"  // For NIMCP_ERROR_* codes
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_router.h"
#include "async/nimcp_bio_messages.h"
#include "async/nimcp_wiring_helpers.h"
#include "utils/platform/nimcp_platform_time.h"
#include "utils/memory/nimcp_unified_memory.h"
#include "utils/memory/nimcp_memory_pool.h"
#include "utils/memory/nimcp_memory_guards.h"  // For nimcp_calloc/nimcp_free
#include "utils/containers/nimcp_vector.h"
#include <string.h>
#include <math.h>
#include <stdatomic.h>
#include "utils/bridge/nimcp_bridge_boilerplate.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- lifecycle module --- */
/* systems_consolidation_create - defined in nimcp_systems_consolidation_lifecycle.c */
/* systems_consolidation_destroy - defined in nimcp_systems_consolidation_lifecycle.c */
/* systems_consolidation_reset - defined in nimcp_systems_consolidation_lifecycle.c */

/* --- scheduling module --- */
/* systems_consolidation_set_sleep_system - defined in nimcp_systems_consolidation_scheduling.c */
/* systems_consolidation_find_similar - defined in nimcp_systems_consolidation_scheduling.c */
/* systems_consolidation_get_statistics - defined in nimcp_systems_consolidation_scheduling.c */
/* systems_consolidation_set_engram_system - defined in nimcp_systems_consolidation_scheduling.c */
/* systems_consolidation_query_self_knowledge - defined in nimcp_systems_consolidation_scheduling.c */
/* systems_consolidation_set_instance_health_agent - defined in nimcp_systems_consolidation_scheduling.c */
/* systems_consolidation_training_begin - defined in nimcp_systems_consolidation_scheduling.c */
/* systems_consolidation_training_end - defined in nimcp_systems_consolidation_scheduling.c */
/* systems_consolidation_training_step - defined in nimcp_systems_consolidation_scheduling.c */

/* --- transfer module --- */
/* systems_consolidation_schedule_replay - defined in nimcp_systems_consolidation_transfer.c */
/* systems_consolidation_execute_replays - defined in nimcp_systems_consolidation_transfer.c */
/* systems_consolidation_transfer_to_cortex - defined in nimcp_systems_consolidation_transfer.c */
/* systems_consolidation_update - defined in nimcp_systems_consolidation_transfer.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_SYSTEMS_CONSOLIDATION_INTERNAL_H */
