/**
 * @file nimcp_bio_router_internal.h
 * @brief Internal shared declarations for nimcp_bio_router SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_BIO_ROUTER_INTERNAL_H
#define NIMCP_BIO_ROUTER_INTERNAL_H

#include "async/nimcp_bio_router.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "async/nimcp_bio_async.h"
#include "api/nimcp_api_exception.h"
#include "async/nimcp_bio_messages.h"
#include "core/brain/nimcp_brain_kg.h"  /* Phase 7: KG-driven dispatch */
#include "mesh/nimcp_mesh_bio_integration.h"  /* Phase 15: Mesh integration */
#include "async/nimcp_predictive_protocol.h"
#include "security/nimcp_blood_brain_barrier.h"
#include "utils/memory/nimcp_unified_memory.h"
#include "utils/error/nimcp_error_codes.h"
#include "utils/platform/nimcp_platform_mutex.h"
#include "utils/platform/nimcp_platform_cond.h"
#include "utils/platform/nimcp_platform_time.h"
#include "utils/platform/nimcp_platform_once.h"
#include "utils/platform/nimcp_tier_optimization.h"
#include "cognitive/knowledge/nimcp_kg_reader.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdatomic.h>
#include <stddef.h>  /* for NULL */
#include "constants/nimcp_timing_constants.h"
#include "utils/fault_tolerance/nimcp_health_agent_macros.h"
#include "constants/nimcp_buffer_constants.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

 * INTERNAL STRUCTURES
 *============================================================================*/

/**
 * @brief Message queue entry (inbox/outbox)
 */
typedef struct {
    void* msg_data;                 /**< Message buffer (header + payload) */
    size_t msg_size;                /**< Total message size */
    nimcp_bio_promise_t response_promise; /**< Response promise (may be NULL) */
    uint64_t enqueue_time_us;       /**< Timestamp when queued */
} bio_msg_queue_entry_t;

/**
 * @brief Simple ring buffer for messages
 */
typedef struct {
    bio_msg_queue_entry_t* entries;
    uint32_t capacity;
    uint32_t read_idx;
    uint32_t write_idx;
    uint32_t count;
    nimcp_platform_mutex_t mutex;
    nimcp_platform_cond_t not_empty;
    nimcp_platform_cond_t not_full;
} bio_msg_queue_t;

/**
 * @brief Handler registration entry
 */
typedef struct {
    bio_message_type_t msg_type;    /**< Message type handled */
    uint32_t category_mask;         /**< Category mask (0 = specific type) */
    bio_message_handler_t handler;  /**< Handler callback */
    bool is_category_handler;       /**< true if category, false if specific */
} bio_handler_entry_t;

/**
 * @brief Module entry in router registry
 */
typedef struct {
    uint32_t magic;
    bio_module_id_t module_id;
    char module_name[MAX_MODULE_NAME];
    void* user_data;

    bio_msg_queue_t inbox;
    bio_handler_entry_t handlers[MAX_HANDLERS_PER_MODULE];
    uint32_t handler_count;
    nimcp_platform_mutex_t handler_mutex;

    // Statistics (all counters use _Atomic for thread-safe increments)
    _Atomic uint64_t messages_received;
    _Atomic uint64_t messages_sent;
    _Atomic uint64_t handler_invocations;
    _Atomic uint64_t handler_errors;
} bio_module_entry_t;

/**
 * @brief Module context (opaque handle)
 */
struct bio_module_context_struct {
    uint32_t magic;
    bio_module_entry_t* entry;  /**< Back-reference to registry entry */
};

/**
 * @brief Router global state
 */
struct bio_router_struct {
    uint32_t magic;
    bio_router_config_t config;

    bio_module_entry_t* modules;
    uint32_t module_count;
    uint32_t module_capacity;
    nimcp_platform_mutex_t modules_mutex;

    // Statistics
    bio_router_stats_t stats;
    nimcp_platform_mutex_t stats_mutex;

    // Predictive protocol (optional)
    predictive_protocol_t predictive_proto;

    // Brain immune integration
    void* brain_immune_system;         /**< Brain immune system handle */
    bio_module_context_t immune_ctx;   /**< Immune module context */

    unified_mem_manager_t mem_mgr;
    bool initialized;
    bool shutdown_requested;
};

 * PREDICTIVE CODING INTEGRATION
 *============================================================================*/

/**
 * @brief Signal observer entry for predictive coding
 */
typedef struct {
    char signal_name[NIMCP_ID_BUFFER_SIZE];
    float prediction;
    float precision;
    bio_prediction_observer_t callback;
    void* user_data;
    bool active;
} signal_observer_t;

 * PHASE SYNCHRONIZATION
 *============================================================================*/

/**
 * @brief Phase sync context (simplified implementation)
 */
typedef struct {
    nimcp_oscillation_band_t band;
    nimcp_bio_promise_t* promises;
    uint32_t promise_count;
    uint32_t completed_count;
    nimcp_platform_mutex_t mutex;
    nimcp_platform_cond_t cond;
    bool all_ready;
} phase_sync_context_t;

 * GLIAL WAVE INTEGRATION
 *============================================================================*/

/**
 * @brief Glial wave context
 */
typedef struct {
    uint32_t wave_id;
    bio_module_id_t source_module;
    float intensity;
    float current_intensity;
    uint64_t start_time_us;
    uint8_t metadata[256];
    size_t metadata_size;
    bool active;
} glial_wave_context_t;

/**
 * @brief Wave arrival callback registration
 */
typedef struct {
    bio_module_id_t module_id;
    nimcp_wave_callback_t callback;
    void* user_data;
    bool active;
} wave_callback_entry_t;

 * SUBSCRIPTION/UNSUBSCRIPTION IMPLEMENTATIONS
 *============================================================================*/

/**
 * @brief Subscription entry for tracking message subscriptions
 */
typedef struct {
    uint32_t msg_type;          /**< Message type subscribed to */
    void* callback;             /**< Handler callback */
    void* user_data;            /**< User context data */
    int channel;                /**< Neuromodulator channel */
    bool active;                /**< Whether subscription is active */
} bio_subscription_entry_t;

 * BBB EMOTION QUERY REGISTRATION
 *============================================================================*/

/**
 * @brief Emotion query registration entry
 */
typedef struct {
    void* system;               /**< System context pointer */
    char module_name[NIMCP_ID_BUFFER_SIZE];       /**< Module name */
    uint64_t query_count;       /**< Number of queries performed */
    bool active;                /**< Whether registration is active */
} bbb_emotion_registration_t;

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- dispatch module --- */
/* bio_router_default_config - defined in nimcp_bio_router_dispatch.c */
/* bio_router_init - defined in nimcp_bio_router_dispatch.c */
/* bio_router_get_global - defined in nimcp_bio_router_dispatch.c */
/* bio_router_shutdown - defined in nimcp_bio_router_dispatch.c */
/* bio_router_is_initialized - defined in nimcp_bio_router_dispatch.c */
/* bio_router_get_stats - defined in nimcp_bio_router_dispatch.c */
/* bio_router_reset_stats - defined in nimcp_bio_router_dispatch.c */
/* bio_router_register_module - defined in nimcp_bio_router_dispatch.c */
/* bio_router_unregister_module - defined in nimcp_bio_router_dispatch.c */
/* bio_router_register_handler - defined in nimcp_bio_router_dispatch.c */
/* bio_router_register_category_handler - defined in nimcp_bio_router_dispatch.c */
/* bio_router_unregister_handler - defined in nimcp_bio_router_dispatch.c */
/* bio_router_clear_handlers - defined in nimcp_bio_router_dispatch.c */
/* bio_router_send - defined in nimcp_bio_router_dispatch.c */
/* bio_router_send_async - defined in nimcp_bio_router_dispatch.c */
/* bio_router_request - defined in nimcp_bio_router_dispatch.c */
/* bio_router_broadcast - defined in nimcp_bio_router_dispatch.c */
/* bio_router_inbox_count - defined in nimcp_bio_router_dispatch.c */
/* bio_router_process_inbox - defined in nimcp_bio_router_dispatch.c */
/* bio_router_observe_signal - defined in nimcp_bio_router_dispatch.c */
/* bio_router_publish_signal - defined in nimcp_bio_router_dispatch.c */
/* bio_router_sync_request - defined in nimcp_bio_router_dispatch.c */
/* bio_router_initiate_wave - defined in nimcp_bio_router_dispatch.c */
/* bio_router_on_wave_arrival - defined in nimcp_bio_router_dispatch.c */
/* bio_router_subscribe - defined in nimcp_bio_router_dispatch.c */
/* bio_router_set_orchestrator - defined in nimcp_bio_router_dispatch.c */
/* bio_router_register_wiring_callback - defined in nimcp_bio_router_dispatch.c */
/* bio_router_set_brain_kg - defined in nimcp_bio_router_dispatch.c */
/* bio_router_kg_dispatch_available - defined in nimcp_bio_router_dispatch.c */
/* bio_router_query_self_knowledge - defined in nimcp_bio_router_dispatch.c */
/* bio_module_context_get_id - defined in nimcp_bio_router_dispatch.c */
/* bio_module_context_get_name - defined in nimcp_bio_router_dispatch.c */
/* bio_module_context_get_user_data - defined in nimcp_bio_router_dispatch.c */
/* bio_msg_type_name - defined in nimcp_bio_router_dispatch.c */
/* bio_async_unsubscribe - defined in nimcp_bio_router_dispatch.c */

/* --- lifecycle module --- */
/* bio_module_name - defined in nimcp_bio_router_lifecycle.c */
/* bio_async_connect_immune - defined in nimcp_bio_router_lifecycle.c */
/* bio_async_broadcast_cytokine - defined in nimcp_bio_router_lifecycle.c */
/* bio_async_inflammation_alert - defined in nimcp_bio_router_lifecycle.c */
/* bio_async_immune_phase_change - defined in nimcp_bio_router_lifecycle.c */
/* bbb_register_emotion_query - defined in nimcp_bio_router_lifecycle.c */

/* --- queue module --- */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_BIO_ROUTER_INTERNAL_H */
