/**
 * @file nimcp_knowledge_internal.h
 * @brief Internal shared declarations for nimcp_knowledge SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_KNOWLEDGE_INTERNAL_H
#define NIMCP_KNOWLEDGE_INTERNAL_H

#include "cognitive/knowledge/nimcp_knowledge.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "cognitive/knowledge/nimcp_kg_reader.h"
#include "cognitive/knowledge/nimcp_knowledge_snn_bridge.h"
#include "cognitive/knowledge/nimcp_knowledge_plasticity_bridge.h"
#include "security/nimcp_security.h"
#include "security/nimcp_blood_brain_barrier.h"
#include "utils/memory/nimcp_unified_memory.h"
#include <ctype.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/brain/nimcp_brain.h"
#include "cognitive/curiosity/nimcp_curiosity.h"
#include "cognitive/nimcp_symbolic_logic.h"
#include "utils/containers/nimcp_btree.h"
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_messages.h"
#include "async/nimcp_bio_router.h"
#include "async/nimcp_wiring_helpers.h"
#include "nimcp.h"  // For error codes
#include "utils/bridge/nimcp_bridge_boilerplate.h"
#include "mesh/nimcp_mesh_participant.h"
#include "mesh/nimcp_mesh_adapter.h"
#include "constants/nimcp_buffer_constants.h"


/* Additional includes from original source */
#include "utils/memory/nimcp_memory.h"  // CRITICAL: Declares nimcp_calloc/nimcp_free return types

/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

//=============================================================================
// Internal Data Structures with Documented Invariants
//=============================================================================

/**
 * @brief Reading progress tracking structure
 *
 * Invariants:
 * - current_page <= total_pages
 * - comprehension_score in range [0.0, 1.0]
 * - book_title is null-terminated
 */
typedef struct {
    char book_title[NIMCP_ERROR_BUFFER_SIZE];
    uint32_t current_page;
    uint32_t total_pages;
    float comprehension_score;
} reading_progress_t;

/**
 * @brief Hash table entry for O(log n) concept_str lookup
 *
 * Implements chaining for collision resolution.
 * Invariants:
 * - index points to valid item in knowledge_system items array
 * - next is NULL or points to valid hash_entry_t
 */
typedef struct hash_entry_struct {
    char* concept;
    uint32_t index;
    struct hash_entry_struct* next;
} hash_entry_t;

/**
 * @brief Hash table for fast concept_str lookup
 *
 * Provides O(1) average case lookup instead of O(n) linear search.
 * Invariants:
 * - size equals HASH_TABLE_SIZE
 * - entries is array of HASH_TABLE_SIZE pointers
 */
typedef struct {
    hash_entry_t** entries;
    uint32_t size;
} knowledge_hash_table_t;

/**
 * @brief Strategy interface for domain-specific learning
 *
 * Strategy Pattern: Different learning strategies for different knowledge types
 * (narrative, art, history, etc.)
 */
typedef struct {
    const char* domain_name;
    bool (*learn)(void* system, const void* data);
    void (*optimize)(void* system);
    float (*assess)(const void* system);
} learning_strategy_t;

/**
 * @brief Repository for knowledge storage abstraction
 *
 * Repository Pattern: Abstracts storage implementation from business logic.
 * Invariants:
 * - num_items <= capacity
 * - index is synchronized with items array
 * - confidence_btree is synchronized with items array
 */
typedef struct {
    knowledge_item_t* items;
    uint32_t num_items;
    uint32_t capacity;
    knowledge_hash_table_t* index;       /* O(1) lookup by concept_str name */
    btree_t* confidence_btree;            /* O(log n) range queries by confidence */
} knowledge_repository_t;

/**
 * @brief Main knowledge system structure
 *
 * Invariants:
 * - All pointers are either NULL or point to valid allocated memory
 * - num_* counters are always <= corresponding *_capacity values
 * - domain_brains array has exactly 11 entries
 * - domain_stats array has exactly 11 entries
 */
struct knowledge_system_struct {
    char learner_name[NIMCP_LABEL_BUFFER_SIZE];

    knowledge_repository_t* repository;

    narrative_knowledge_t* narratives;
    uint32_t num_narratives;
    uint32_t narratives_capacity;

    aesthetic_knowledge_t* artworks;
    uint32_t num_artworks;
    uint32_t artworks_capacity;

    historical_knowledge_t* history;
    uint32_t num_history;
    uint32_t history_capacity;

    // REMOVED: brain_t domain_brains[11] - Never used, completely dead code

    reading_progress_t* reading_list;
    uint32_t num_reading;
    uint32_t reading_capacity;

    // Unified brain for knowledge system (provides curiosity module)
    // Previously created curiosity independently - now follows "one brain, many modules" pattern
    brain_t knowledge_brain;

    domain_knowledge_t domain_stats[11];

    learning_strategy_t* strategies[11];

    // Bio-async integration
    bio_module_context_t bio_ctx;   /**< Bio-async module context */
    bool bio_async_enabled;         /**< Bio-async registration status */

    // SNN and Plasticity bridges
    knowledge_snn_bridge_t* snn_bridge;           /**< SNN bridge for neural encoding */
    knowledge_plasticity_bridge_t* plasticity_bridge;  /**< Plasticity bridge for learning */
    bool bridges_enabled;                         /**< Bridges enabled flag */
};

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- io module --- */
/* knowledge_read_book - defined in nimcp_knowledge_io.c */
/* knowledge_save - defined in nimcp_knowledge_io.c */
/* knowledge_load - defined in nimcp_knowledge_io.c */
/* knowledge_reinforce - defined in nimcp_knowledge_io.c */
/* knowledge_organize_domain - defined in nimcp_knowledge_io.c */
/* knowledge_get_map - defined in nimcp_knowledge_io.c */
/* knowledge_continue_reading - defined in nimcp_knowledge_io.c */
/* knowledge_get_reading_list - defined in nimcp_knowledge_io.c */
/* knowledge_assess_domain - defined in nimcp_knowledge_io.c */
/* knowledge_get_summary - defined in nimcp_knowledge_io.c */
/* knowledge_domain_name - defined in nimcp_knowledge_io.c */
/* knowledge_print_item - defined in nimcp_knowledge_io.c */
/* knowledge_print_assessment - defined in nimcp_knowledge_io.c */
/* knowledge_get_by_confidence_range - defined in nimcp_knowledge_io.c */

/* --- lifecycle module --- */
/* knowledge_system_create - defined in nimcp_knowledge_lifecycle.c */
/* knowledge_system_destroy - defined in nimcp_knowledge_lifecycle.c */
/* knowledge_learn_from_text - defined in nimcp_knowledge_lifecycle.c */

/* --- query module --- */
/* knowledge_retrieve - defined in nimcp_knowledge_query.c */
/* knowledge_find_connections - defined in nimcp_knowledge_query.c */
/* knowledge_query_self_knowledge - defined in nimcp_knowledge_query.c */
/* knowledge_learn_from_story - defined in nimcp_knowledge_query.c */
/* knowledge_learn_from_art - defined in nimcp_knowledge_query.c */
/* knowledge_learn_from_history - defined in nimcp_knowledge_query.c */
/* knowledge_learn_from_conversation - defined in nimcp_knowledge_query.c */
/* knowledge_learn_from_demonstration - defined in nimcp_knowledge_query.c */
/* knowledge_understand - defined in nimcp_knowledge_query.c */
/* knowledge_explain_simply - defined in nimcp_knowledge_query.c */
/* knowledge_transfer_learning - defined in nimcp_knowledge_query.c */
/* knowledge_build_on - defined in nimcp_knowledge_query.c */
/* knowledge_add_to_symbolic_logic - defined in nimcp_knowledge_query.c */
/* knowledge_set_instance_health_agent - defined in nimcp_knowledge_query.c */
/* knowledge_training_begin - defined in nimcp_knowledge_query.c */
/* knowledge_training_end - defined in nimcp_knowledge_query.c */
/* knowledge_training_step - defined in nimcp_knowledge_query.c */

/* --- stats module --- */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_KNOWLEDGE_INTERNAL_H */
