/**
 * @file nimcp_portia_internal.h
 * @brief Internal shared declarations for nimcp_portia SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_PORTIA_INTERNAL_H
#define NIMCP_PORTIA_INTERNAL_H

#include "portia/nimcp_portia.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "portia/nimcp_portia_messages.h"
#include "async/nimcp_bio_router.h"
#include "async/nimcp_wiring_helpers.h"
#include "security/nimcp_blood_brain_barrier.h"
#include "security/nimcp_bbb_helpers.h"
#include "utils/thread/nimcp_thread.h"
#include "utils/time/nimcp_time.h"
#include "utils/fault_tolerance/nimcp_health_agent_macros.h"
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <pthread.h>
#include <stdatomic.h>
#include "constants/nimcp_timing_constants.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

//=============================================================================
// Subsystem Structures
//=============================================================================

/**
 * @brief Tier manager subsystem
 */
struct portia_tier_manager_t {
    platform_tier_t current_tier;
    platform_tier_t recommended_tier;
    portia_tier_config_t config;
    uint64_t last_switch_time_us;
    uint64_t tier_switch_count;
    nimcp_mutex_t lock;
};

/**
 * @brief Power monitor subsystem
 */
struct portia_power_monitor_t {
    portia_power_state_t current_state;
    portia_power_config_t config;
    float battery_level;
    bool is_on_ac;
    uint64_t last_poll_time_us;
    nimcp_mutex_t lock;
};

/**
 * @brief Resource tracker subsystem
 */
struct portia_resource_tracker_t {
    portia_resource_config_t config;
    system_resources_t current_resources;
    float cpu_usage;
    float memory_usage;
    float temperature_celsius;
    portia_thermal_state_t thermal_state;
    uint64_t last_sample_time_us;
    nimcp_mutex_t lock;
};

/**
 * @brief Degradation controller subsystem
 */
struct portia_degradation_controller_t {
    portia_degradation_level_t current_level;
    portia_degradation_config_t config;
    uint64_t degradation_count;
    uint64_t last_degradation_time_us;
    nimcp_mutex_t lock;
};

/**
 * @brief Accelerator detector subsystem
 */
struct portia_accelerator_detector_t {
    portia_accelerator_config_t config;
    uint32_t num_accelerators;
    portia_accelerator_type_t accelerator_types[8];
    bool detection_complete;
    nimcp_mutex_t lock;
};

/**
 * @brief Sensor fusion subsystem
 */
struct portia_sensor_fusion_t {
    float overall_health;
    float resource_pressure;
    float performance_score;
    float efficiency_score;
    uint64_t last_fusion_time_us;
    nimcp_mutex_t lock;
};

/**
 * @brief Planning engine subsystem
 */
struct portia_planning_engine_t {
    portia_workload_type_t current_workload;
    platform_tier_t planned_tier;
    bool planning_active;
    nimcp_mutex_t lock;
};

/**
 * @brief Target classifier subsystem
 */
struct portia_target_classifier_t {
    portia_workload_type_t classified_workload;
    float classification_confidence;
    uint32_t pattern_id;
    nimcp_mutex_t lock;
};

/**
 * @brief Main Portia context
 */
struct portia_context_t {
    portia_config_t config;
    bool initialized;

    /* Subsystems */
    portia_tier_manager_t* tier_manager;
    portia_power_monitor_t* power_monitor;
    portia_resource_tracker_t* resource_tracker;
    portia_degradation_controller_t* degradation_controller;
    portia_accelerator_detector_t* accelerator_detector;
    portia_sensor_fusion_t* sensor_fusion;
    portia_planning_engine_t* planning_engine;
    portia_target_classifier_t* target_classifier;

    /* Bio-async integration */
    bio_module_context_t bio_ctx;

    /* Statistics */
    uint64_t update_count;
    float total_update_time_ms;
    uint64_t last_update_time_us;

    /* Thread safety */
    nimcp_mutex_t lock;
};

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- execution module --- */

/* --- lifecycle module --- */
/* portia_init - defined in nimcp_portia_lifecycle.c */
/* portia_destroy - defined in nimcp_portia_lifecycle.c */
/* portia_is_initialized - defined in nimcp_portia_lifecycle.c */
/* portia_get_default_config - defined in nimcp_portia_lifecycle.c */
/* portia_get_context - defined in nimcp_portia_lifecycle.c */
/* portia_update - defined in nimcp_portia_lifecycle.c */
/* portia_get_status - defined in nimcp_portia_lifecycle.c */
/* portia_set_tier - defined in nimcp_portia_lifecycle.c */
/* portia_power_state_name - defined in nimcp_portia_lifecycle.c */
/* portia_thermal_state_name - defined in nimcp_portia_lifecycle.c */
/* portia_accel_type_name - defined in nimcp_portia_lifecycle.c */
/* portia_workload_type_name - defined in nimcp_portia_lifecycle.c */
/* portia_degradation_level_name - defined in nimcp_portia_lifecycle.c */

/* --- planning module --- */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_PORTIA_INTERNAL_H */
