/**
 * @file nimcp_introspection_internal.h
 * @brief Internal shared declarations for nimcp_introspection SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_INTROSPECTION_INTERNAL_H
#define NIMCP_INTROSPECTION_INTERNAL_H

#include "cognitive/introspection/nimcp_introspection.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "cognitive/introspection/nimcp_ensemble_uncertainty.h"
#include "cognitive/introspection/nimcp_introspection_snn_bridge.h"
#include "cognitive/introspection/nimcp_introspection_plasticity_bridge.h"
#include "security/nimcp_security.h"
#include "security/nimcp_blood_brain_barrier.h"
#include "core/brain/factory/init/nimcp_brain_init_medulla.h"
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "utils/algorithms/nimcp_monte_carlo.h"  /* P1-COG-02: mc_random_uniform, mc_seed_from_time */
#include "plasticity/adaptive/nimcp_adaptive.h"
#include "core/brain/nimcp_brain.h"
#include "core/brain/nimcp_brain_internal.h"
#include "utils/memory/nimcp_unified_memory.h"
#include "utils/containers/nimcp_queue.h"
#include "utils/thread/nimcp_thread.h"
#include "utils/platform/nimcp_platform_mutex.h"
#include "utils/time/nimcp_time.h"
#include "utils/containers/nimcp_vector.h"
#include "utils/statistics/nimcp_statistics.h"
#include "nimcp.h"  // For error codes
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_messages.h"
#include "async/nimcp_bio_router.h"
#include "async/nimcp_wiring_helpers.h"
#include "core/brain/nimcp_brain_kg_helpers.h"
#include "cognitive/knowledge/nimcp_kg_reader.h"
#include "utils/bridge/nimcp_bridge_boilerplate.h"
#include "mesh/nimcp_mesh_participant.h"
#include "mesh/nimcp_mesh_adapter.h"
#include "cognitive/nimcp_working_memory.h"
#include "cognitive/nimcp_emotional_tagging.h"
#include "constants/nimcp_buffer_constants.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

 * INTERNAL STRUCTURES
 * ======================================================================== */

/**
 * WHAT: Pattern registry entry
 * WHY: Track learned patterns and their activity
 * HOW: Hash table of pattern metadata
 */
typedef struct pattern_entry {
    char* name;                 /* Pattern identifier */
    float current_activity;     /* Current activation */
    float activity_sum;         /* Sum for average */
    uint32_t activation_count;  /* Count for average */
    float pattern_strength;     /* Learning strength */
    uint64_t first_learned;     /* First occurrence */
    uint64_t last_activated;    /* Last occurrence */
    struct pattern_entry* next; /* Hash table chain */
} pattern_entry_t;

/**
 * WHAT: Pattern registry (hash table)
 * WHY: Fast O(1) lookup of patterns by name
 * HOW: Chained hash table with 256 buckets
 */
typedef struct {
    pattern_entry_t* buckets[256]; /* Hash buckets */
    uint32_t num_patterns;         /* Total patterns */
    nimcp_mutex_t lock;            /* Thread safety */
} pattern_registry_t;

/**
 * WHAT: Introspection context structure (Pimpl)
 * WHY: Encapsulate implementation details
 * HOW: Opaque pointer pattern
 *
 * REFACTORING NOTE (activity history):
 * - Replaced custom circular buffer (activity_history_buffer_t) with nimcp_queue
 * - WHY: Eliminates ~50 lines of code duplication, standardized API
 * - BENEFITS: Blocking operations, better statistics, peek/clear, thread-safe
 * - NO PERFORMANCE IMPACT: Both use mutex (not lock-free)
 */
struct introspection_context_struct {
    brain_t brain;                 /* Associated brain */
    introspection_config_t config; /* Configuration */

    /* Bio-async module context */
    bio_module_context_t bio_ctx;  /* Message router context */
    bool bio_async_enabled;        /* Bio-async registration status */

    /* Pattern tracking */
    pattern_registry_t* pattern_registry; /* Learned patterns */

    /* Activity history - now using standardized queue utility */
    nimcp_queue_handle_t activity_queue; /* Activity snapshots queue */

    /* Auto activity history state */
    uint64_t last_sample_time_ms;        /* Last sampling timestamp */
    activity_sample_callback_t sample_callback; /* Registered callback */
    void* sample_callback_context;       /* User context for callback */
    float last_avg_activation;           /* Previous avg for change detection */

    /* Network topology cache */
    network_topology_t topology; /* Cached topology */
    bool topology_cached;        /* Is topology valid? */

    /* Statistics */
    introspection_stats_t stats; /* Performance stats */

    /* Ensemble uncertainty (Phase: Real Ensemble Implementation) */
    ensemble_context_t ensemble; /* Ensemble for true uncertainty estimation */

    /* Brain immune system integration */
    struct brain_immune_system* immune_system; /* Connected immune system (optional) */

    /* Internal Knowledge Graph integration */
    kg_module_context_t kg_context; /* KG access context */
    bool kg_connected;              /* Internal KG is connected */

    /* Thread safety */
    nimcp_mutex_t lock; /* Protects context */

    /* SNN and Plasticity bridges */
    introspection_snn_bridge_t* snn_bridge;
    introspection_plasticity_bridge_t* plasticity_bridge;
    bool bridges_enabled;

    /* P1-COG-02: Thread-safe RNG seed for uncertainty estimation */
    uint32_t rand_seed;
};

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- lifecycle module --- */
/* introspection_context_create - defined in nimcp_introspection_lifecycle.c */
/* introspection_context_destroy - defined in nimcp_introspection_lifecycle.c */
/* neuron_population_free - defined in nimcp_introspection_lifecycle.c */
/* brain_state_free - defined in nimcp_introspection_lifecycle.c */
/* brain_uncertainty_free - defined in nimcp_introspection_lifecycle.c */
/* pattern_info_free - defined in nimcp_introspection_lifecycle.c */
/* pattern_list_free - defined in nimcp_introspection_lifecycle.c */
/* network_topology_free - defined in nimcp_introspection_lifecycle.c */
/* introspection_reset_stats - defined in nimcp_introspection_lifecycle.c */
/* introspection_default_config - defined in nimcp_introspection_lifecycle.c */
/* brain_get_active_population - defined in nimcp_introspection_lifecycle.c */
/* brain_get_neuron_activity - defined in nimcp_introspection_lifecycle.c */
/* brain_get_internal_state - defined in nimcp_introspection_lifecycle.c */
/* brain_state_similarity - defined in nimcp_introspection_lifecycle.c */
/* brain_get_uncertainty - defined in nimcp_introspection_lifecycle.c */
/* brain_is_pattern_active - defined in nimcp_introspection_lifecycle.c */
/* brain_get_pattern_info - defined in nimcp_introspection_lifecycle.c */
/* brain_list_patterns - defined in nimcp_introspection_lifecycle.c */
/* brain_get_topology - defined in nimcp_introspection_lifecycle.c */
/* brain_get_activity_history - defined in nimcp_introspection_lifecycle.c */
/* introspection_sample_activity - defined in nimcp_introspection_lifecycle.c */

/* --- stats module --- */
/* introspection_get_stats - defined in nimcp_introspection_stats.c */
/* introspection_get_history_stats - defined in nimcp_introspection_stats.c */
/* introspection_set_ensemble - defined in nimcp_introspection_stats.c */
/* introspection_get_ensemble - defined in nimcp_introspection_stats.c */
/* introspection_set_sample_interval - defined in nimcp_introspection_stats.c */
/* introspection_clear_history - defined in nimcp_introspection_stats.c */
/* introspection_set_activity_callback - defined in nimcp_introspection_stats.c */
/* introspection_connect_immune - defined in nimcp_introspection_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_INTROSPECTION_INTERNAL_H */
