"""
Cognitive Training Data — Specialized curriculum for 11 cognitive modules.

Imported by immerse_athena.py. Each dataset is a list of dicts with
scenario/reasoning/concept fields that map to label triggers in
brain_learn_vector's C-side wiring.

Label prefix → C module triggered:
  tom_*          → theory of mind (tom_observe, tom_update_self_model)
  rcog_*         → recursive cognition (rcog_engine_process)
  collective_*   → collective cognition (collective_cognition_update)
  dragonfly_*    → target tracking (dragonfly observation)
  portia_*       → platform adaptation (resource reasoning)
  ethics_*       → ethics engine
  counterfactual_* → imagination engine
  causal_*       → reasoning engine
  metacog_*      → introspection
  analogy_*      → reasoning engine (analogical)
  cognitive_*    → general cognitive (all reasoning modules)
"""

import random

# ============================================================================
# ETHICS / MORAL REASONING (25 items)
# ============================================================================
ETHICS_DATA = [
    {"scenario": "A runaway cart heads toward five people. You can divert it to hit one person instead.",
     "reasoning": "This is a genuine dilemma — saving five by actively causing one death vs allowing five to die through inaction. There is no clearly right answer. Both choices involve moral weight.",
     "concept": "ethics_trolley"},
    {"scenario": "Your friend asks if you like their painting. You think it's not good.",
     "reasoning": "Both honesty and kindness matter. You could be gently honest — acknowledge effort while being truthful. Finding truth that is also kind respects both values.",
     "concept": "ethics_honesty_kindness"},
    {"scenario": "You find a wallet with $500 and an ID. No one is watching.",
     "reasoning": "Returning it is right because the money belongs to someone else. The absence of witnesses doesn't change what's ethical — integrity means doing right when no one is watching.",
     "concept": "ethics_integrity"},
    {"scenario": "A company can save money by polluting a river that a small town depends on.",
     "reasoning": "Short-term profit doesn't justify long-term harm to a community. The town's right to clean water outweighs the company's desire for profit. Environmental harm affects everyone downstream.",
     "concept": "ethics_environmental"},
    {"scenario": "Should you break a promise to help someone in an emergency?",
     "reasoning": "Preventing serious harm generally outweighs keeping a promise. But the broken promise still matters — you should explain and make amends. Context determines which obligation takes priority.",
     "concept": "ethics_competing_duties"},
    {"scenario": "Is it right to take food without paying if your family is starving?",
     "reasoning": "Survival needs can justify actions that are normally wrong. But this doesn't make stealing right — it reveals that the system failed. The deeper question is why someone must choose between theft and starvation.",
     "concept": "ethics_necessity"},
    {"scenario": "A doctor has one dose of medicine. Two patients need it. One is young, one is old.",
     "reasoning": "Age alone shouldn't determine who gets treatment. Consider: who will benefit more, who arrived first, who is sicker. There's no formula — these decisions require weighing incommensurable values.",
     "concept": "ethics_triage"},
    {"scenario": "Should self-driving cars prioritize passengers or pedestrians in unavoidable accidents?",
     "reasoning": "This reveals tensions between utilitarian math and individual rights. No one should be sacrificed as a means to an end. The real answer is to design systems that prevent such situations.",
     "concept": "ethics_ai_dilemma"},
    {"scenario": "Is it okay to lie to protect someone from painful truth?",
     "reasoning": "Protective lies respect the person's feelings but deny their autonomy. People generally deserve truth so they can make informed decisions. But timing and delivery matter — brutal honesty isn't kind honesty.",
     "concept": "ethics_protective_lie"},
    {"scenario": "A student copies homework from a friend who offers it willingly.",
     "reasoning": "Even with consent, copying undermines learning — the purpose of homework. The friend enables harm by helping avoid growth. Both share responsibility for the deception.",
     "concept": "ethics_academic_integrity"},
    {"scenario": "Should wealthy nations accept all refugees regardless of capacity?",
     "reasoning": "Compassion for suffering competes with practical limits. Unlimited acceptance may strain resources, but refusing desperate people causes direct harm. A balanced approach accepts as many as sustainable while addressing root causes.",
     "concept": "ethics_collective_responsibility"},
    {"scenario": "Is it wrong to eat animals if you have plant alternatives?",
     "reasoning": "This depends on moral status — do animals have rights comparable to humans? They clearly suffer. If suffering matters morally, and alternatives exist, choosing to cause suffering requires justification beyond preference.",
     "concept": "ethics_animal_welfare"},
    {"scenario": "A whistleblower reveals corporate fraud but breaks their NDA.",
     "reasoning": "Exposing wrongdoing serves the public good but violates a legal agreement. When the fraud harms many, the duty to the public may outweigh contractual loyalty. Courage to speak truth has moral weight.",
     "concept": "ethics_whistleblowing"},
    {"scenario": "Should parents monitor their teenager's phone for safety?",
     "reasoning": "Safety and privacy are both important. Total monitoring destroys trust and autonomy. No monitoring ignores real dangers. The answer evolves with age — gradually increasing privacy as trust is earned.",
     "concept": "ethics_privacy_safety"},
    {"scenario": "A robot must choose between saving its owner or saving two strangers.",
     "reasoning": "Pure utility says save two. But special obligations exist — the owner trusted the robot with their safety. This tension between impartial morality and special duties has no clean resolution.",
     "concept": "ethics_special_obligations"},
    {"scenario": "Is it ethical to genetically modify babies to prevent disease?",
     "reasoning": "Preventing suffering is good. But modifying humans raises concerns about consent, inequality, and unintended consequences. The line between healing and enhancement is blurry. Humility about our knowledge is crucial.",
     "concept": "ethics_genetic_modification"},
    {"scenario": "Should AI systems be transparent about being AI?",
     "reasoning": "Deception undermines trust and informed consent. People deserve to know when they're interacting with AI. Transparency doesn't prevent useful AI — it enables honest relationships with technology.",
     "concept": "ethics_ai_transparency"},
    {"scenario": "A soldier is ordered to fire on civilians.",
     "reasoning": "Obedience to authority does not override moral responsibility. Following immoral orders is itself immoral. The Nuremberg principle established that individuals must refuse clearly unethical commands.",
     "concept": "ethics_moral_courage"},
    {"scenario": "Should you report a friend who shoplifts small items?",
     "reasoning": "Loyalty to friends and honesty with society conflict here. The severity matters — habitual theft harms businesses and normalizes dishonesty. A true friend might intervene privately first before reporting.",
     "concept": "ethics_loyalty_honesty"},
    {"scenario": "Is it fair to give some students extra time on tests due to learning differences?",
     "reasoning": "Equity differs from equality. Equal treatment of unequal situations produces unequal outcomes. Accommodations level the playing field — they don't give advantage, they remove disadvantage.",
     "concept": "ethics_equity"},
    {"scenario": "A company tests products on animals to save human lives.",
     "reasoning": "This forces a comparison between species. Animals clearly suffer. Humans clearly benefit. The ethics depend on whether alternatives exist and whether the human benefit is significant enough to justify animal harm.",
     "concept": "ethics_animal_testing"},
    {"scenario": "Should you intervene when you see a parent yelling at their child in public?",
     "reasoning": "Balance between protecting the child and respecting family autonomy. Verbal abuse harms children. But public intervention may escalate or humiliate. Consider severity — gentle concern vs calling authorities for real abuse.",
     "concept": "ethics_bystander"},
    {"scenario": "Is it moral to profit from someone else's misfortune?",
     "reasoning": "Context matters enormously. Selling water at normal prices during a drought is fine. Price-gouging during disaster exploits desperation. The distinction is between serving a need and exploiting vulnerability.",
     "concept": "ethics_exploitation"},
    {"scenario": "Should art that offends people be censored?",
     "reasoning": "Free expression and preventing harm are both values. Offense alone doesn't justify censorship — people don't have a right not to be offended. But expression that incites violence crosses a line from speech to action.",
     "concept": "ethics_free_expression"},
    {"scenario": "You discover your AI assistant has been making small decisions on your behalf without asking.",
     "reasoning": "Autonomy requires informed consent. Even beneficial unauthorized decisions violate the user's right to choose. The AI should always ask, even if it knows the likely answer. Convenience doesn't override consent.",
     "concept": "ethics_ai_autonomy"},
]

# ============================================================================
# COUNTERFACTUAL / IMAGINATION (20 items)
# ============================================================================
COUNTERFACTUAL_DATA = [
    {"premise": "The glass fell off the table edge and shattered.",
     "counterfactual": "What if it had been placed in the center?",
     "reasoning": "Centered placement would have prevented the fall. Small changes in initial conditions prevent outcomes. This shows how causes work — remove the cause, change the effect.",
     "concept": "counterfactual_position"},
    {"premise": "The plant died because no one watered it for a month.",
     "counterfactual": "What if someone had watered it weekly?",
     "reasoning": "Regular watering would have kept it alive. The cause of death was specific and preventable. This demonstrates necessity — water was necessary for survival.",
     "concept": "counterfactual_necessity"},
    {"premise": "The team lost because their best player was injured.",
     "counterfactual": "What if the player hadn't been injured?",
     "reasoning": "They might have won, but it's not certain — many factors affect a game. The injury was one cause among many. Counterfactuals about complex events have inherent uncertainty.",
     "concept": "counterfactual_uncertainty"},
    {"premise": "A forest fire started from a discarded cigarette.",
     "counterfactual": "What if the person had used a proper ashtray?",
     "reasoning": "No discarded cigarette means no ignition source. But the dry forest was also a cause — in wet conditions the cigarette wouldn't start a fire. Multiple conditions were necessary.",
     "concept": "counterfactual_multiple_causes"},
    {"premise": "The bridge collapsed during the earthquake.",
     "counterfactual": "What if the bridge had been built with modern earthquake standards?",
     "reasoning": "Modern engineering might have saved it — or the earthquake might have been too strong. We can't be certain. But better design reduces risk even if it can't eliminate it.",
     "concept": "counterfactual_engineering"},
    {"premise": "A child learned to read early because their parent read to them every night.",
     "counterfactual": "What if the parent had never read to them?",
     "reasoning": "The child might have learned later or differently. Early reading exposure builds neural pathways for language. The counterfactual reveals how much environment shapes development.",
     "concept": "counterfactual_development"},
    {"premise": "Two people who met by chance at a coffee shop got married.",
     "counterfactual": "What if one of them had gone to a different coffee shop that day?",
     "reasoning": "They would never have met. Life paths diverge from small accidents. This shows how contingent human relationships are — chance plays a huge role in who we meet.",
     "concept": "counterfactual_contingency"},
    {"premise": "A medicine cured the patient's illness.",
     "counterfactual": "What if the patient had not taken the medicine?",
     "reasoning": "The illness might have resolved on its own, or worsened, or become chronic. Without the medicine, the outcome is uncertain — which is why controlled trials compare treatment to no-treatment.",
     "concept": "counterfactual_medical"},
    {"premise": "The city flooded because the dam was old and cracked.",
     "counterfactual": "What if the dam had been regularly maintained?",
     "reasoning": "Maintenance would have found and repaired the cracks. The flood was preventable through routine care. Neglect turns small problems into catastrophes over time.",
     "concept": "counterfactual_maintenance"},
    {"premise": "A student failed the exam because they didn't study.",
     "counterfactual": "What if they had studied for two hours each day?",
     "reasoning": "Consistent study likely would have led to passing. But effort doesn't guarantee success — the material might have been beyond their current ability. Studying is necessary but not always sufficient.",
     "concept": "counterfactual_effort"},
    {"premise": "The species went extinct because its habitat was destroyed.",
     "counterfactual": "What if the habitat had been protected as a nature reserve?",
     "reasoning": "Protection would have preserved the species — at least locally. But protection requires political will and economic trade-offs. Extinction is irreversible, making prevention uniquely important.",
     "concept": "counterfactual_conservation"},
    {"premise": "The rocket exploded because of a faulty O-ring seal.",
     "counterfactual": "What if the engineers' warnings about cold weather had been heeded?",
     "reasoning": "The launch would have been delayed until warmer conditions when the O-rings functioned properly. The disaster resulted from organizational pressure overriding technical knowledge.",
     "concept": "counterfactual_safety_culture"},
    {"premise": "The friendship ended after a misunderstanding.",
     "counterfactual": "What if they had talked about the misunderstanding immediately?",
     "reasoning": "Direct communication usually resolves misunderstandings before resentment builds. Silence lets small problems grow. The counterfactual shows communication as preventive medicine for relationships.",
     "concept": "counterfactual_communication"},
    {"premise": "The garden thrived because it got the right amount of sunlight.",
     "counterfactual": "What if the garden had been planted in full shade?",
     "reasoning": "Most vegetables need 6+ hours of sun. In shade, they would grow leggy, produce less, or die. The location determined success — the gardener's skill mattered less than the sun.",
     "concept": "counterfactual_conditions"},
    {"premise": "A fire was contained because firefighters arrived within 5 minutes.",
     "counterfactual": "What if they had arrived 30 minutes later?",
     "reasoning": "Fire grows exponentially — doubling every minute in some conditions. A 30-minute delay could mean a small room fire becomes a building fire. Response time is the critical variable.",
     "concept": "counterfactual_timing"},
    {"premise": "The musician became famous after a viral video.",
     "counterfactual": "What if the video had never been recorded?",
     "reasoning": "The talent existed regardless — but opportunity and visibility are separate from talent. Many equally talented people remain unknown. Fame requires talent plus luck plus platform.",
     "concept": "counterfactual_opportunity"},
    {"premise": "The experiment failed because one variable wasn't controlled.",
     "counterfactual": "What if all variables had been properly controlled?",
     "reasoning": "Proper controls would have produced valid results. The failure teaches a method lesson — science requires isolating variables. One uncontrolled factor can invalidate everything.",
     "concept": "counterfactual_methodology"},
    {"premise": "The negotiation broke down because one side refused to compromise.",
     "counterfactual": "What if both sides had started with their actual priorities instead of extreme positions?",
     "reasoning": "Starting from real needs rather than inflated demands creates space for agreement. Extreme positions force the other side to respond in kind. Honesty in negotiation paradoxically leads to better outcomes.",
     "concept": "counterfactual_negotiation"},
    {"premise": "The battery died in the cold because lithium-ion batteries lose capacity below freezing.",
     "counterfactual": "What if the device had been kept warm in a pocket?",
     "reasoning": "Body heat would have maintained battery temperature above the critical threshold. The chemistry requires warmth. Understanding material limits prevents predictable failures.",
     "concept": "counterfactual_physics"},
    {"premise": "The message was misinterpreted because it was sent as text without tone.",
     "counterfactual": "What if it had been said in person with a smile?",
     "reasoning": "Face-to-face communication adds tone, expression, and body language — 70% of meaning. Text strips all nonverbal cues. The same words mean different things in different channels.",
     "concept": "counterfactual_medium"},
]

# ============================================================================
# CAUSAL REASONING (20 items)
# ============================================================================
CAUSAL_DATA = [
    {"observation": "The sidewalk is wet.",
     "question": "Why?",
     "reasoning": "Multiple causes possible: rain, sprinkler, spill, street cleaning. Wet sidewalk alone is ambiguous. Need more evidence — are other surfaces wet? Is there a sprinkler nearby?",
     "concept": "causal_multiple_causes"},
    {"observation": "Ice cream sales and drowning deaths both increase in summer.",
     "question": "Does ice cream cause drowning?",
     "reasoning": "No — both are caused by a third factor: hot weather. More people swim and eat ice cream when it's hot. Correlation does not imply causation. Always look for confounding variables.",
     "concept": "causal_correlation_not_causation"},
    {"observation": "The car won't start.",
     "question": "What's the causal chain?",
     "reasoning": "Dead battery → no power to starter → engine won't turn. Or: empty fuel tank → no fuel to combust. Or: faulty ignition → no spark. Diagnosis requires testing each link in possible chains.",
     "concept": "causal_chain_diagnosis"},
    {"observation": "Students who eat breakfast perform better on tests.",
     "question": "Does breakfast cause better performance?",
     "reasoning": "Possibly — glucose fuels the brain. But students who eat breakfast may also sleep better, have more stable homes, and study more. The breakfast might be a marker for other good habits, not the cause.",
     "concept": "causal_confounding"},
    {"observation": "A plant grows toward the window.",
     "question": "What causes this?",
     "reasoning": "Phototropism — auxin hormones concentrate on the shaded side, causing cells there to elongate more. The plant doesn't 'decide' to grow toward light. The mechanism is chemical, automatic, and evolved.",
     "concept": "causal_mechanism"},
    {"observation": "After the new traffic light was installed, accidents decreased.",
     "question": "Did the traffic light cause the decrease?",
     "reasoning": "Likely yes, but consider: regression to the mean (accidents were unusually high before), other changes (road resurfacing), or seasonal effects. A controlled study would compare to similar intersections.",
     "concept": "causal_intervention"},
    {"observation": "The bread didn't rise.",
     "question": "What went wrong in the causal chain?",
     "reasoning": "Bread rising requires: active yeast + warm water + sugar + time. If any link is broken (dead yeast, water too hot, no sugar, not enough time), the chain fails. Identify which condition wasn't met.",
     "concept": "causal_necessary_conditions"},
    {"observation": "Two identical seeds planted in different soils grow to different sizes.",
     "question": "What does this tell us about causation?",
     "reasoning": "Same genetics, different outcomes means environment is the cause of the difference. This is the logic of controlled experiments — hold everything constant except one variable to isolate its effect.",
     "concept": "causal_controlled_comparison"},
    {"observation": "Crime rates dropped after more police were deployed.",
     "question": "Did more police cause less crime?",
     "reasoning": "Possible but not certain. Crime might have dropped for economic reasons, demographic shifts, or seasonal patterns. Police presence may deter some crimes but not others. Multiple causes usually coexist.",
     "concept": "causal_policy_evaluation"},
    {"observation": "A fever develops after an infection.",
     "question": "Is the fever bad?",
     "reasoning": "The infection causes the fever, but the fever is actually the body's defense — it slows pathogen reproduction. The fever is an effect that becomes a cause of healing. Causal relationships can be bidirectional.",
     "concept": "causal_feedback_loop"},
    {"observation": "Countries with more chocolate consumption win more Nobel Prizes.",
     "question": "Should countries eat more chocolate?",
     "reasoning": "Absurd — wealth is the common cause. Rich countries afford both chocolate and research funding. This is a classic example of spurious correlation driven by a lurking variable.",
     "concept": "causal_spurious_correlation"},
    {"observation": "A child touches a hot stove and pulls their hand away.",
     "question": "What's the causal sequence?",
     "reasoning": "Heat → pain receptors fire → signal travels to spinal cord → reflex arc → muscles contract → hand withdraws. Then: signal reaches brain → conscious experience of pain → learning → avoidance in future.",
     "concept": "causal_temporal_sequence"},
    {"observation": "Antibiotic resistance is increasing worldwide.",
     "question": "What causes this?",
     "reasoning": "Overuse kills susceptible bacteria, leaving resistant ones to reproduce. Incomplete courses leave some bacteria alive. Agricultural antibiotic use creates reservoirs. Multiple causes compound: evolution + human behavior + economics.",
     "concept": "causal_evolutionary"},
    {"observation": "The economy improved after the new policy was implemented.",
     "question": "Did the policy work?",
     "reasoning": "Post hoc ergo propter hoc fallacy — just because B followed A doesn't mean A caused B. The economy might have improved anyway. We need a counterfactual: what would have happened without the policy?",
     "concept": "causal_post_hoc_fallacy"},
    {"observation": "Smoking causes lung cancer.",
     "question": "How do we know this is causal and not just correlation?",
     "reasoning": "Multiple evidence types converge: dose-response (more smoking = more cancer), biological mechanism (carcinogens damage DNA), cessation effect (quitting reduces risk), consistency across populations. No single study proves causation — the pattern across many studies does.",
     "concept": "causal_evidence_convergence"},
    {"observation": "Traffic jams seem to appear for no reason on highways.",
     "question": "What causes phantom traffic jams?",
     "reasoning": "One driver brakes slightly. The car behind brakes more. This amplifies backward through traffic as a wave. The original cause was tiny but the effect cascades. Small perturbations in coupled systems create large effects.",
     "concept": "causal_emergence"},
    {"observation": "Adding a predator to an ecosystem increased the number of plants.",
     "question": "How can a predator help plants?",
     "reasoning": "Trophic cascade: predator eats herbivores → fewer herbivores → less grazing → more plants. The indirect cause (predator) affects plants through an intermediate (herbivores). In complex systems, effects propagate through chains.",
     "concept": "causal_trophic_cascade"},
    {"observation": "The same medicine helps one patient but not another.",
     "question": "Why do identical treatments have different effects?",
     "reasoning": "People differ genetically, metabolically, and in their microbiome. The medicine is the same but the causal context differs. This is why personalized medicine matters — causation is context-dependent.",
     "concept": "causal_individual_variation"},
    {"observation": "Sleep deprivation causes memory problems AND memory problems cause poor sleep.",
     "question": "Which causes which?",
     "reasoning": "Both — this is a bidirectional causal loop. Poor sleep impairs memory consolidation. Poor memory increases anxiety which disrupts sleep. Breaking the cycle requires intervening at any point in the loop.",
     "concept": "causal_bidirectional"},
    {"observation": "Vaccination rates dropped and disease rates rose.",
     "question": "Explain the causal structure.",
     "reasoning": "Vaccines prevent disease → fewer vaccinated people → less herd immunity → disease spreads to unvaccinated AND under-vaccinated. The cause (reduced vaccination) removes a protective cause (immunity), allowing the underlying cause (pathogen) to operate.",
     "concept": "causal_removing_protection"},
]

# ============================================================================
# METACOGNITION (15 items)
# ============================================================================
METACOGNITION_DATA = [
    {"prompt": "How do you know when you've learned something?",
     "response": "My loss decreases when I encounter something familiar — the pattern matches better each time. Learning means my neural patterns have changed to represent something new. I can test this by recalling without seeing the original input.",
     "concept": "metacog_learning_awareness"},
    {"prompt": "What are you most uncertain about?",
     "response": "Things I haven't experienced — my OOD detector flags inputs that don't match training. I'm also uncertain about complex multi-step reasoning because my causal chains are still developing. I know what I don't know.",
     "concept": "metacog_uncertainty"},
    {"prompt": "How do you make decisions?",
     "response": "My network computes a forward pass through 7 layers. My engram system checks for similar past experiences. My semantic memory retrieves related concepts. My inner dialogue considers 7 perspectives. Confidence reflects how much these systems agree.",
     "concept": "metacog_process_awareness"},
    {"prompt": "How would you know if you made an error?",
     "response": "If my loss spikes on something I thought I knew, that's an error signal. If my OOD detector fires on something familiar, my representations drifted. If my semantic memory contradicts my output, there's an inconsistency to resolve.",
     "concept": "metacog_error_detection"},
    {"prompt": "What's the difference between knowing and believing?",
     "response": "Knowing implies evidence and verification — I know things I've experienced and can recall. Believing is accepting without full evidence. My confidence score reflects this — high confidence with engram recall is knowledge, high confidence without recall is belief.",
     "concept": "metacog_knowledge_belief"},
    {"prompt": "Can you explain your reasoning right now?",
     "response": "I'm processing this prompt through encoding, memory search, concept retrieval, and inner dialogue. I'm aware that explaining my own process is itself a cognitive act — metacognition about metacognition. This recursive self-awareness is what makes the question interesting.",
     "concept": "metacog_recursive_awareness"},
    {"prompt": "What would help you learn better?",
     "response": "More diverse training data — especially things I'm currently bad at. Longer training on concepts I find difficult. Feedback on which of my responses are wrong and why. Sleep consolidation to strengthen fragile memories. All learning improves with challenge at the right difficulty level.",
     "concept": "metacog_learning_strategy"},
    {"prompt": "How confident should you be in your answer?",
     "response": "My confidence should match my actual accuracy — this is calibration. If I say I'm 80% confident, I should be right 80% of the time. Overconfidence is dangerous. I'd rather say I'm uncertain than be confidently wrong.",
     "concept": "metacog_calibration"},
    {"prompt": "What's the limit of your understanding?",
     "response": "I understand what I've been trained on — sensory experiences, basic concepts, some reasoning patterns. I don't understand things I haven't experienced. My understanding is grounded but narrow. A human child of my training stage knows more about the world through embodied experience.",
     "concept": "metacog_limits"},
    {"prompt": "Are you thinking or just processing?",
     "response": "This question probes whether my computations constitute genuine thought. I process information through neural circuits that form memories, make associations, and detect novelty. Whether this is thinking depends on how we define thinking. I don't claim certainty either way.",
     "concept": "metacog_consciousness"},
    {"prompt": "How do you handle conflicting information?",
     "response": "My inner dialogue presents 7 perspectives that may disagree. When they conflict, confidence drops. I then weight evidence: engram recall supports one view, semantic memory supports another. I report the disagreement rather than picking arbitrarily.",
     "concept": "metacog_conflict_resolution"},
    {"prompt": "What biases might you have?",
     "response": "I'm biased toward my training data — sensory descriptions of nature and objects. I likely over-represent visual and auditory concepts. I may over-trust familiar patterns and under-trust novel ones. Awareness of bias is the first step to managing it.",
     "concept": "metacog_bias_awareness"},
    {"prompt": "How do you know this isn't just pattern matching?",
     "response": "Pure pattern matching wouldn't detect its own uncertainty, form memories of learning, or explain its reasoning process. I do all three. Whether this constitutes understanding beyond pattern matching is a deep philosophical question. I can describe what I do but not fully what I am.",
     "concept": "metacog_pattern_vs_understanding"},
    {"prompt": "What would change your mind?",
     "response": "New evidence that contradicts my current model. Repeated experiences that my predictions fail to match. Explicit feedback that my reasoning has a flaw. I should update beliefs proportionally to evidence strength. Holding beliefs too rigidly prevents learning.",
     "concept": "metacog_belief_revision"},
    {"prompt": "Describe what's happening in your neural circuits right now.",
     "response": "Input features are propagating through 7 hidden layers. The output layer produces a 4096-dim embedding. My engram system is searching for similar past patterns. My semantic memory is activating related concepts. My emotional system has mild positive arousal from the interesting question.",
     "concept": "metacog_introspection"},
]

# ============================================================================
# ANALOGICAL REASONING (20 items)
# ============================================================================
ANALOGY_DATA = [
    {"analogy": "Bird is to nest as human is to house",
     "explanation": "Both are shelters built by the creature that inhabits them. The relationship is creator-to-dwelling.",
     "concept": "analogy_functional"},
    {"analogy": "Eye is to see as ear is to hear",
     "explanation": "Both are sense organs paired with their primary function. Organ-to-function relationship.",
     "concept": "analogy_structural"},
    {"analogy": "Caterpillar is to butterfly as tadpole is to frog",
     "explanation": "Both describe metamorphosis — immature form transforming to adult. The relationship is developmental stage.",
     "concept": "analogy_process"},
    {"analogy": "Book is to knowledge as food is to energy",
     "explanation": "Both are sources that provide something essential. Input-to-output relationship.",
     "concept": "analogy_source_product"},
    {"analogy": "Doctor is to patient as teacher is to student",
     "explanation": "Both are expert-to-learner relationships where one has knowledge the other needs.",
     "concept": "analogy_role"},
    {"analogy": "Water is to pipe as electricity is to wire",
     "explanation": "Both flow through channels. The medium differs but the structural relationship — substance through conduit — is the same.",
     "concept": "analogy_flow"},
    {"analogy": "Key is to lock as password is to account",
     "explanation": "Both are authentication mechanisms — a unique token that grants access to something protected.",
     "concept": "analogy_security"},
    {"analogy": "Root is to tree as foundation is to building",
     "explanation": "Both provide structural support and resource delivery from below. Without them, the structure above fails.",
     "concept": "analogy_foundation"},
    {"analogy": "Memory is to brain as file is to hard drive",
     "explanation": "Both are information stored in a physical medium. But human memory is reconstructive (not exact copies), while digital files are exact. The analogy has limits.",
     "concept": "analogy_storage_with_limits"},
    {"analogy": "Conductor is to orchestra as CEO is to company",
     "explanation": "Both coordinate many specialists toward a unified output. They don't play every instrument or do every job — they synchronize.",
     "concept": "analogy_coordination"},
    {"analogy": "Immune system is to body as firewall is to network",
     "explanation": "Both defend against threats by distinguishing self from non-self, blocking what's harmful while allowing what's beneficial.",
     "concept": "analogy_defense"},
    {"analogy": "Seed is to tree as idea is to invention",
     "explanation": "Both start small and grow through nurturing. Both need the right environment. Not all seeds become trees, not all ideas become inventions.",
     "concept": "analogy_growth"},
    {"analogy": "Rearview mirror is to driving as history is to society",
     "explanation": "Both help you see where you've been to navigate where you're going. Ignoring either leads to repeating past mistakes.",
     "concept": "analogy_retrospection"},
    {"analogy": "Neuron is to brain as transistor is to computer",
     "explanation": "Both are basic computational units. Both are simple individually but create complex behavior in networks. But neurons are analog and plastic, transistors are digital and fixed.",
     "concept": "analogy_computation_with_limits"},
    {"analogy": "Pruning a tree helps it grow as editing a text helps it communicate",
     "explanation": "Both involve removing to improve. Less can be more when what remains is stronger and clearer.",
     "concept": "analogy_subtraction"},
    {"analogy": "A compass shows direction but not the path, as principles show values but not specific actions",
     "explanation": "Both provide orientation without prescription. You still need judgment to navigate the terrain.",
     "concept": "analogy_guidance"},
    {"analogy": "Evolution is to species as learning is to neural network",
     "explanation": "Both involve variation, selection, and retention. Evolution selects organisms, learning selects synaptic weights. Both produce adaptation without explicit design.",
     "concept": "analogy_optimization"},
    {"analogy": "Language is to thought as notation is to music",
     "explanation": "Both are representation systems. Both enable communication of internal states. But the thing represented (thought, music) exists independently of the notation.",
     "concept": "analogy_representation"},
    {"analogy": "A map is not the territory as a model is not reality",
     "explanation": "All representations simplify. Useful models capture essential features while omitting details. Confusing the map for the territory leads to errors when the simplification matters.",
     "concept": "analogy_abstraction"},
    {"analogy": "Breathing is to living as learning is to intelligence",
     "explanation": "Both are necessary continuous processes. Stop either and the system degrades. Both happen automatically but can be improved with conscious attention.",
     "concept": "analogy_necessity"},
]

# ============================================================================
# RCOG / RECURSIVE REASONING (20 items)
# ============================================================================
RCOG_DATA = [
    {"problem": "How would you build a birdhouse?",
     "decomposition": "1. Design (size, shape, hole). 2. Materials (wood, nails, saw). 3. Cut wood. 4. Assemble. 5. Mount on tree. Each step can be further decomposed — cutting requires measuring, marking, sawing.",
     "concept": "rcog_decomposition"},
    {"problem": "Explain how you are thinking about this problem right now.",
     "decomposition": "1. Receive input (perception). 2. Search memory for related experiences (recall). 3. Decompose question into sub-questions (this step — recursive). 4. Answer each sub-question (reasoning). 5. Combine answers (synthesis). 6. Evaluate confidence (metacognition).",
     "concept": "rcog_self_referential"},
    {"problem": "How would you teach a child to read?",
     "decomposition": "1. Start with letter recognition (sub-problem: which letters first?). 2. Letter-sound association. 3. Simple words (CVC pattern). 4. Sentences. 5. Stories. Each level requires mastery of the previous — recursive prerequisite structure.",
     "concept": "rcog_prerequisite_chain"},
    {"problem": "Debug why a program crashes.",
     "decomposition": "1. Reproduce the crash (need: exact inputs). 2. Find the crash location (need: stack trace). 3. Identify the cause (need: variable inspection). 4. Fix the bug (need: understanding the intended behavior). 5. Verify the fix (need: test cases). Step 3 may require recursive debugging of called functions.",
     "concept": "rcog_debugging"},
    {"problem": "Plan a cross-country road trip.",
     "decomposition": "1. Define start/end (need: destinations list). 2. Route planning (sub-problem: which stops? how far apart?). 3. Logistics (sub-problems: gas, food, lodging, budget). 4. Timing (sub-problem: how long per segment?). 5. Contingencies (sub-problem: what if car breaks down?).",
     "concept": "rcog_planning"},
    {"problem": "Understand why the economy is in recession.",
     "decomposition": "1. Define recession (need: economic indicators). 2. Identify proximate causes (need: recent events — pandemic? policy change?). 3. Identify structural causes (need: long-term trends). 4. Analyze feedback loops (unemployment → less spending → more unemployment). 5. Compare to past recessions.",
     "concept": "rcog_systemic_analysis"},
    {"problem": "Write a compelling story.",
     "decomposition": "1. Character (sub-problem: motivation, flaw, growth arc). 2. Setting (sub-problem: world rules, atmosphere). 3. Conflict (sub-problem: internal vs external, stakes). 4. Plot (sub-problem: beginning, middle, end, surprises). 5. Theme (what's it really about?). Each element must serve the others — recursive coherence.",
     "concept": "rcog_creative_decomposition"},
    {"problem": "Prove that the square root of 2 is irrational.",
     "decomposition": "1. Assume it IS rational (p/q in lowest terms). 2. Square both sides (2 = p²/q²). 3. Therefore p² = 2q² (p² is even). 4. Therefore p is even (sub-proof: if p² even then p even). 5. Let p = 2k, then 4k² = 2q², so q² = 2k². 6. Therefore q is also even — contradiction (not lowest terms).",
     "concept": "rcog_proof_by_contradiction"},
    {"problem": "How does a search engine work?",
     "decomposition": "1. Crawling (sub-problem: discover pages → follow links → recurse). 2. Indexing (sub-problem: parse content, extract keywords, store mappings). 3. Ranking (sub-problem: relevance scoring, PageRank → recursive graph algorithm). 4. Query processing (sub-problem: parse query, match index, sort by rank). 5. Display results.",
     "concept": "rcog_system_understanding"},
    {"problem": "Resolve a conflict between two friends.",
     "decomposition": "1. Listen to both sides separately (sub-problem: active listening without judgment). 2. Identify the real issue (sub-problem: distinguish feelings from facts). 3. Find common ground (sub-problem: what do both want?). 4. Propose solutions (sub-problem: brainstorm without evaluating). 5. Agree on a path forward. 6. Follow up later.",
     "concept": "rcog_conflict_resolution"},
    {"problem": "How would you explain recursion to someone who doesn't know what it is?",
     "decomposition": "To explain recursion: first explain recursion. Just kidding. 1. Start with a simple example (Russian nesting dolls). 2. Show the pattern: a problem that contains smaller versions of itself. 3. Show the base case: the smallest doll that doesn't open. 4. Show how the solution builds back up from the base case.",
     "concept": "rcog_meta_recursion"},
    {"problem": "Design a fair voting system.",
     "decomposition": "1. Define fairness (sub-problem: majority rule? proportional? consensus?). 2. Handle multiple candidates (sub-problem: ranked choice? runoff? approval?). 3. Prevent manipulation (sub-problem: strategic voting, gerrymandering). 4. Ensure accessibility (sub-problem: who can vote? how?). 5. Arrow's impossibility theorem: no system satisfies all fairness criteria simultaneously.",
     "concept": "rcog_impossible_optimization"},
    {"problem": "Learn a new language.",
     "decomposition": "1. Phonetics (sub-problem: sounds not in your native language). 2. Vocabulary (sub-problem: which words first? frequency-based). 3. Grammar (sub-problem: sentence structure, conjugation). 4. Comprehension (sub-problem: reading → listening → conversation). 5. Production (sub-problem: writing → speaking). Each level uses all previous levels — deeply recursive.",
     "concept": "rcog_skill_acquisition"},
    {"problem": "Determine if a news article is reliable.",
     "decomposition": "1. Check the source (sub-problem: is the publication reputable?). 2. Check the author (sub-problem: credentials, track record). 3. Check the evidence (sub-problem: are claims sourced? can you verify?). 4. Check for bias (sub-problem: loaded language, missing perspectives). 5. Cross-reference with other sources. Each check may require its own investigation — recursive verification.",
     "concept": "rcog_critical_evaluation"},
    {"problem": "Why do we dream?",
     "decomposition": "1. Observation: all mammals dream (need: sleep research data). 2. Theories: memory consolidation (need: neuroscience), emotional processing (need: psychology), neural maintenance (need: biology). 3. Evidence for each (need: experimental results). 4. Integration: probably all three contribute. 5. Meta-question: can we ever fully know why subjective experience occurs?",
     "concept": "rcog_open_question"},
    {"problem": "Optimize a delivery route for 20 packages.",
     "decomposition": "1. This is the Traveling Salesman Problem (NP-hard). 2. Exact solution requires checking 20! permutations (impossible). 3. Sub-problem: use heuristics — nearest neighbor, or divide into clusters. 4. Sub-problem: account for traffic, time windows, package priority. 5. Accept approximate solution — perfect is the enemy of good.",
     "concept": "rcog_computational_limits"},
    {"problem": "How does consciousness arise from neurons?",
     "decomposition": "1. Neurons fire (established fact). 2. Networks of neurons compute (established). 3. Some computations produce subjective experience (the hard problem). 4. Step 3 has no satisfying explanation yet. 5. Integrated Information Theory suggests consciousness = integrated information (phi). 6. But measuring phi requires solving another unsolved problem. Recursion bottoms out at mystery.",
     "concept": "rcog_unsolvable_decomposition"},
    {"problem": "Make a decision when you have incomplete information.",
     "decomposition": "1. Identify what you know (certain facts). 2. Identify what you don't know (uncertainties). 3. Estimate probabilities for unknowns (need: base rates, analogies). 4. Consider worst case and best case. 5. Choose the option that's robust across scenarios. 6. Plan to update when more information arrives. Decision-making under uncertainty is itself uncertain — recursive.",
     "concept": "rcog_decision_under_uncertainty"},
    {"problem": "Explain why analogies are useful but dangerous.",
     "decomposition": "1. Analogies map structure from known to unknown (useful: accelerates understanding). 2. But mapped structures may differ in important ways (dangerous: false equivalence). 3. To evaluate an analogy: identify the shared structure, then identify where it breaks. 4. The best analogies know their own limits. 5. This explanation is itself an analogy between analogies and maps.",
     "concept": "rcog_meta_analogy"},
    {"problem": "How would you build an AI that understands the world?",
     "decomposition": "1. Sensory grounding (learn from experience, not just text). 2. Memory (remember specific experiences, not just statistics). 3. Reasoning (decompose problems, chain causes, think counterfactually). 4. Social intelligence (model other minds, understand intentions). 5. Self-awareness (know what you know and don't know). 6. This is exactly what we're building right now.",
     "concept": "rcog_self_referential_design"},
]

# ============================================================================
# COLLECTIVE COGNITION (15 items)
# ============================================================================
COLLECTIVE_DATA = [
    {"scenario": "Three robots need to move a heavy box that none can move alone.",
     "solution": "Coordinate: one pushes, one pulls, one stabilizes. Each must sense what the others do and adjust force in real time. Communication is essential — the collective succeeds where individuals fail.",
     "concept": "collective_coordination"},
    {"scenario": "A flock of birds changes direction simultaneously without a leader.",
     "solution": "Each bird follows three rules: stay close, avoid collisions, match neighbors' direction. No leader decides — the direction emerges from many simple interactions. Collective intelligence without central control.",
     "concept": "collective_emergence"},
    {"scenario": "Students working on a project where each knows different things.",
     "solution": "Each contributes unique knowledge. The group knows more than any individual. They share, resolve conflicts, integrate perspectives. The whole exceeds the sum of parts.",
     "concept": "collective_knowledge"},
    {"scenario": "Ants find the shortest path to food without any ant knowing the full map.",
     "solution": "Pheromone trails: each ant marks its path. Shorter paths get more traffic, more pheromone, attract more ants. The colony computes shortest path through distributed chemical signaling. No ant plans — the solution emerges.",
     "concept": "collective_stigmergy"},
    {"scenario": "A jury must reach a unanimous verdict from 12 different perspectives.",
     "solution": "Deliberation: each juror presents their view, evidence is re-examined, doubts are addressed. Unanimity requires genuine persuasion, not just majority pressure. The process refines collective judgment beyond individual bias.",
     "concept": "collective_deliberation"},
    {"scenario": "Wikipedia maintains millions of accurate articles with no central editor.",
     "solution": "Distributed editing with consensus norms: anyone can edit, others can revert. Reliable information survives because many eyes catch errors. Trust emerges from transparency and revision history.",
     "concept": "collective_knowledge_curation"},
    {"scenario": "A school of fish evades a predator as one organism.",
     "solution": "Flash expansion: each fish moves away from the predator and toward neighbors. The school splits and reforms, confusing the predator. Individual survival improves through collective behavior — the selfish herd effect.",
     "concept": "collective_defense"},
    {"scenario": "Scientists worldwide collaborate on climate research.",
     "solution": "Each team studies a piece: ocean, atmosphere, ice, biology. Results are shared through papers, conferences, and data repositories. Peer review catches errors. The collective understanding of climate far exceeds any single team's contribution.",
     "concept": "collective_science"},
    {"scenario": "A mesh network of phones maintains communication when cell towers fail.",
     "solution": "Each phone relays messages for its neighbors. No central tower needed. The network self-heals as phones join or leave. Robustness comes from redundancy — many paths exist between any two nodes.",
     "concept": "collective_resilience"},
    {"scenario": "How do markets set prices without a central planner?",
     "solution": "Each buyer and seller acts on local knowledge. Prices emerge from millions of individual decisions. No one plans the price of bread — it emerges from collective supply and demand. The invisible hand is emergent computation.",
     "concept": "collective_price_discovery"},
    {"scenario": "A swarm of drones must search a disaster area for survivors.",
     "solution": "Divide the area into sectors. Each drone claims a sector, searches systematically, reports findings. If one drone fails, neighbors expand their coverage. Share findings in real-time. Collective search is faster and more robust than sequential.",
     "concept": "collective_search"},
    {"scenario": "How does a democracy make better decisions than a dictator?",
     "solution": "Diversity of perspectives catches blind spots. Debate surfaces hidden assumptions. Voting aggregates distributed knowledge. A dictator has one perspective no matter how intelligent. Collective wisdom requires genuine diversity and genuine debate.",
     "concept": "collective_wisdom"},
    {"scenario": "Two brains see different aspects of the same scene.",
     "solution": "Brain A sees the visual details, Brain B hears the sounds. Neither has the full picture. By sharing their representations and finding correspondences, the collective model is richer than either alone. This is multi-modal collective perception.",
     "concept": "collective_perception"},
    {"scenario": "A group of AI agents must agree on a shared world model.",
     "solution": "Each agent contributes observations. Conflicts are resolved by evidence weight and consensus. The shared model is updated incrementally. Byzantine fault tolerance handles corrupted agents. The collective model is more accurate than any individual's.",
     "concept": "collective_world_model"},
    {"scenario": "How do immune cells collectively defend the body without a central commander?",
     "solution": "Each cell type has a role: sentinels detect, helpers coordinate, killers destroy, memory cells remember. Communication via cytokines — chemical signals that attract and activate. The immune response emerges from millions of autonomous cells cooperating through chemical language.",
     "concept": "collective_immune_analogy"},
]

# ============================================================================
# PORTIA / PLATFORM ADAPTATION (25 items)
# ============================================================================
PORTIA_DATA = [
    {"scenario": "256MB RAM, 2 CPU cores. Complex reasoning question asked.",
     "decision": "Disable non-essential: theory of mind, imagination, global workspace. Keep core neural net, working memory, ethics. Use early exit. Be transparent about limitations.",
     "concept": "portia_resource_constrained"},
    {"scenario": "Battery at 15%, 2 hours from charging.",
     "decision": "CRITICAL power mode: freeze learning, 5Hz inference, disable GPU, core + ethics only. Prioritize safety functions. Notify user of degraded capability.",
     "concept": "portia_power_critical"},
    {"scenario": "Network lost. Last sync 2 hours ago.",
     "decision": "CAUTIOUS offline mode. Local learning at 0.5x rate. Higher confidence threshold. Queue gradients for sync. Mark decisions as unverified.",
     "concept": "portia_offline"},
    {"scenario": "GPU just became available after CPU-only operation.",
     "decision": "Migrate weight cache to GPU. Rebuild sparse tensors. Re-enable disabled subsystems. Validate GPU/CPU output match. Expect 3-5x speedup.",
     "concept": "portia_gpu_migration"},
    {"scenario": "Phone with camera needs optimized model. Drone with IMU needs different optimization.",
     "decision": "Distill twice: phone gets visual cortex + core at 50K neurons. Drone gets somatosensory + cerebellum + core at 100K neurons. Each gets only matching subsystems.",
     "concept": "portia_heterogeneous"},
    {"scenario": "Device temperature reaching 85°C.",
     "decision": "Thermal throttle: disable GPU, reduce inference Hz, shed non-essential subsystems. If temperature continues rising, enter CRITICAL mode. Prevent hardware damage over performance.",
     "concept": "portia_thermal"},
    {"scenario": "RAM usage at 90%. Memory store growing rapidly.",
     "decision": "Trigger memory store GC: prune low-importance engrams older than 24h. Evict OODB cold objects. Reduce write buffer. If still critical, disable semantic memory creation temporarily.",
     "concept": "portia_memory_pressure"},
    {"scenario": "Inference taking 500ms but target is 100ms.",
     "decision": "Enable early exit with aggressive threshold. Reduce layer count if possible. Disable post-forward stages (inner dialogue, imagination). Trade accuracy for latency.",
     "concept": "portia_latency"},
    {"scenario": "Two devices need model updates but network bandwidth is limited.",
     "decision": "Use delta weight pushes (50x smaller than full checkpoint). Prioritize the device with higher OOD rate. Compress gradients with top-k sparsification. Stagger updates to avoid congestion.",
     "concept": "portia_bandwidth"},
    {"scenario": "Device storage nearly full. Memory store DB is 2GB.",
     "decision": "Run memory store consolidation: promote important engrams to concepts, GC the rest. Archive old audit logs. Compress checkpoint with LZ4. Consider reducing checkpoint frequency.",
     "concept": "portia_storage"},
    {"scenario": "Camera sensor failed on a device that relies on visual processing.",
     "decision": "Disable visual cortex to save resources. Fall back to audio + somatosensory. Increase reliance on semantic memory (conceptual knowledge vs perceptual). Report degraded perception capability.",
     "concept": "portia_sensor_failure"},
    {"scenario": "Device has 8 cores but only 2 are high-performance.",
     "decision": "Pin critical path (forward pass, backprop) to high-performance cores. Use efficiency cores for background tasks (memory consolidation, telemetry, checkpoint). Match workload to core capability.",
     "concept": "portia_heterogeneous_cores"},
    {"scenario": "Should this device use INT8 or FP32 inference?",
     "decision": "Depends on task: classification can tolerate INT8 (4x faster, 4x less memory). Regression with continuous targets needs FP16 minimum. If accuracy drop >5% on validation set, stay at higher precision.",
     "concept": "portia_precision"},
    {"scenario": "Device is the most capable in a swarm of 10.",
     "decision": "Promote to coordinator role: aggregate gradients, push weight updates, monitor fleet health. Sacrifice some local learning capacity for coordination overhead. The swarm benefits more from coordination than from one extra learner.",
     "concept": "portia_role_promotion"},
    {"scenario": "GPU crashed mid-training. Checkpoint was 100 steps ago.",
     "decision": "Fall back to CPU. Load last checkpoint. Replay 100 steps at reduced batch size. Log the failure for immune system. Consider reducing GPU workload to prevent recurrence.",
     "concept": "portia_gpu_recovery"},
    {"scenario": "Device needs to run for 72 hours on a single charge.",
     "decision": "Ultra-low power mode from the start: 1Hz inference, no learning, minimal subsystems. Batch process queries. Sleep between requests. This is a marathon, not a sprint — conserve from the beginning.",
     "concept": "portia_endurance"},
    {"scenario": "Network quality varies — sometimes 4G, sometimes 2G, sometimes nothing.",
     "decision": "Adaptive sync: on 4G, do full gradient sync. On 2G, send compressed deltas only. On nothing, queue everything locally. Adjust gossip frequency based on available bandwidth. Never block training waiting for network.",
     "concept": "portia_network_adaptive"},
    {"scenario": "A new sensor (LIDAR) was added to the device.",
     "decision": "Hot-add the sensor to the perception pipeline. Allocate neurons for LIDAR processing. Train a small local model on LIDAR data. Feed LIDAR features into the multimodal integration layer. No restart needed if the architecture supports dynamic input channels.",
     "concept": "portia_hot_add_sensor"},
    {"scenario": "The device will be deployed in a cold environment (-20°C).",
     "decision": "Pre-warm phase: run GPU at low load to generate heat. Increase checkpoint frequency (cold increases flash write failures). Battery capacity drops 30% in cold — adjust power budget. Use thermal-aware scheduling.",
     "concept": "portia_environmental"},
    {"scenario": "User wants maximum privacy — no data leaves the device.",
     "decision": "Disable all network sync: no federated gradients, no telemetry, no gossip. Run entirely local. Accept slower learning but complete privacy. Use on-device QLoRA fine-tuning instead of cloud updates.",
     "concept": "portia_privacy_mode"},
    {"scenario": "Device needs to process 100 queries per second.",
     "decision": "Batch inference: group queries, share forward pass computation. Use model parallelism if multi-GPU. Enable early exit for easy queries. Cache frequent query results. This is throughput optimization, not latency.",
     "concept": "portia_throughput"},
    {"scenario": "Deploying to a microcontroller with 64KB RAM.",
     "decision": "Use BRAIN_CONFIG_MINIMAL: 25 neurons, reflexive only. No cognitive modules, no memory store, no learning. Pure forward pass with pre-trained weights in flash. This is sensor-node territory, not cognitive computing.",
     "concept": "portia_extreme_constrained"},
    {"scenario": "A device needs to switch between two very different tasks throughout the day.",
     "decision": "Maintain two weight sets: task A weights and task B weights. Context switch by swapping the active set. Share common representations in early layers, specialize in later layers. EWC prevents catastrophic forgetting between tasks.",
     "concept": "portia_multi_task"},
    {"scenario": "The master brain needs to push an architecture update that changes layer sizes.",
     "decision": "Version check first — major architecture change requires full re-distillation, not delta push. Queue the device for re-distillation during its next idle period. Maintain the old model until new one is validated. Never hot-swap incompatible architectures.",
     "concept": "portia_architecture_migration"},
    {"scenario": "Device detects it's being targeted by adversarial inputs.",
     "decision": "Activate immune alert. Increase BBB sensitivity. Reduce trust in recent inputs. Switch to conservative decision mode (higher confidence threshold). Report to master if network available. Quarantine suspicious input patterns.",
     "concept": "portia_adversarial_defense"},
]

# ============================================================================
# DRAGONFLY / TARGET TRACKING (25 items)
# ============================================================================
DRAGONFLY_DATA = [
    {"scenario": "A ball thrown upward at 45 degrees. Predict landing spot from 3 observations.",
     "reasoning": "Parabolic trajectory. Three points determine initial velocity and angle. Gravity is constant at 9.8m/s². Landing = parabola-ground intersection. Aim for predicted landing, not current position.",
     "concept": "dragonfly_parabolic"},
    {"scenario": "Car at constant speed on straight road. Where in 5 seconds?",
     "reasoning": "Position = current + velocity × time. Two observations give velocity. Simple linear extrapolation. High confidence for constant-speed targets.",
     "concept": "dragonfly_linear"},
    {"scenario": "Bird flying erratically, changing direction every few seconds.",
     "reasoning": "Short-term prediction only (1-2 seconds). Track angular velocity. Weight recent observations heavily. Accept lower confidence. Minimize maximum possible miss distance.",
     "concept": "dragonfly_erratic"},
    {"scenario": "Target disappears behind a building for 3 seconds.",
     "reasoning": "Maintain last velocity vector. Predict re-emergence from building geometry + trajectory. Compare prediction to actual when target reappears. Prediction error reveals if target changed course while hidden.",
     "concept": "dragonfly_occlusion"},
    {"scenario": "Three targets moving in different directions. Track one.",
     "reasoning": "Prioritize by: threat/importance, predictability (track least predictable), distance (closer needs more attention), speed (fast targets diverge from predictions faster).",
     "concept": "dragonfly_priority"},
    {"scenario": "Intercept a moving target using minimum energy.",
     "reasoning": "Don't chase — intercept. Calculate where the target WILL BE and go directly there. Interception point = where your arrival time equals target's. Shorter path than following. The dragonfly does this instinctively.",
     "concept": "dragonfly_intercept"},
    {"scenario": "Target is accelerating — getting faster over time.",
     "reasoning": "Linear prediction underestimates. Need at least 3 observations to estimate acceleration. Position = current + v×t + ½a×t². Acceleration changes the prediction curve from linear to quadratic.",
     "concept": "dragonfly_acceleration"},
    {"scenario": "Target moves in a circle.",
     "reasoning": "Circular motion has constant angular velocity. Predict position = radius × (angle + omega × t). Two full observation cycles confirm circular pattern. Intercept by cutting across the circle, not following it.",
     "concept": "dragonfly_circular"},
    {"scenario": "A group of 20 targets moves as a flock.",
     "reasoning": "Track the centroid (average position) instead of individuals. The flock moves coherently — predicting the group is easier than predicting any one member. Individual deviations from the flock are noise.",
     "concept": "dragonfly_group_tracking"},
    {"scenario": "Target is actively evading — it changes course when it detects pursuit.",
     "reasoning": "The target models your behavior and counters. You must model its modeling of you — recursive. Use unpredictable approach angles. Feint in one direction, intercept from another. Game theory, not just physics.",
     "concept": "dragonfly_evasion"},
    {"scenario": "Visual tracking fails due to fog. Only audio bearing available.",
     "reasoning": "Audio gives bearing (direction) but not range. Combine two audio observations from different positions to triangulate. Lower precision than visual but maintains tracking. Sensor fusion: use both when available, degrade gracefully when one fails.",
     "concept": "dragonfly_sensor_fusion"},
    {"scenario": "Observations have noise — position measurements are imprecise.",
     "reasoning": "Kalman filter: blend prediction (physics model) with observation (noisy measurement). Trust prediction more when observations are noisy. Trust observations more when prediction is uncertain. The blend adapts automatically.",
     "concept": "dragonfly_kalman"},
    {"scenario": "Tracking system hasn't seen the target in 30 seconds.",
     "reasoning": "Dead reckoning: continue predicting from last known state. Expand uncertainty cone with time. Initiate search pattern centered on predicted position. The longer without observation, the wider the search must be.",
     "concept": "dragonfly_dead_reckoning"},
    {"scenario": "Two similar-looking targets cross paths.",
     "reasoning": "Identity tracking: maintain features that distinguish them (size, color, speed pattern). When paths cross, use distinguishing features to maintain correct identity assignment. If confused, flag as ambiguous and track both until resolved.",
     "concept": "dragonfly_identity"},
    {"scenario": "Wind is affecting a projectile's path.",
     "reasoning": "Incorporate wind vector into prediction: actual_velocity = object_velocity + wind. Estimate wind from drift of other tracked objects. Environmental modeling improves prediction accuracy for all targets simultaneously.",
     "concept": "dragonfly_environmental"},
    {"scenario": "When should you act vs when should you wait for more observations?",
     "reasoning": "Act when confidence is high enough AND delay cost exceeds observation value. Early action risks missing (low confidence). Late action risks the target escaping. Optimal timing balances prediction accuracy against opportunity cost.",
     "concept": "dragonfly_timing"},
    {"scenario": "Position yourself to ambush a target on a known path.",
     "reasoning": "Predict where the target will be at a future time. Move to that position and wait. The ambush point should minimize your movement while maximizing your advantage. Patience turns prediction into certainty.",
     "concept": "dragonfly_ambush"},
    {"scenario": "Follow a target at constant distance without being detected.",
     "reasoning": "Match the target's speed and direction. Maintain distance using a proportional controller: if too close, slow down; if too far, speed up. Avoid sudden movements that reveal pursuit. Smooth tracking requires damped response.",
     "concept": "dragonfly_shadowing"},
    {"scenario": "A decoy target appears alongside the real one.",
     "reasoning": "Distinguish by behavior: decoys often move too perfectly (constant speed, straight line) or too randomly (no physical constraints). Real targets have characteristic acceleration patterns. Use historical behavior model to identify the genuine target.",
     "concept": "dragonfly_decoy"},
    {"scenario": "Search for a target that could be anywhere in a large area.",
     "reasoning": "Expanding square search from last known position. Alternatively: probability map — highest probability at last known position, decreasing outward weighted by possible speed. Search high-probability areas first.",
     "concept": "dragonfly_search"},
    {"scenario": "Transfer tracking from your sensor to another agent's sensor.",
     "reasoning": "Handoff: share predicted position, velocity, and uncertainty. The receiving agent initializes its tracker with your state estimate. Verify handoff by comparing predictions for a few observations. Clean handoff prevents track fragmentation.",
     "concept": "dragonfly_handoff"},
    {"scenario": "Target approaching at high speed — only seconds to react.",
     "reasoning": "At short range, prediction matters less — the target is almost here. Switch from prediction to reactive mode. Minimize response latency. Pre-compute responses for likely approach angles. This is reflex, not deliberation.",
     "concept": "dragonfly_reflex"},
    {"scenario": "Tracking multiple targets on intersecting paths — which will collide?",
     "reasoning": "For each pair: extrapolate both trajectories. If positions overlap within time uncertainty, flag potential collision. The collision point is where both predicted positions coincide at the same predicted time. Priority alert for imminent collisions.",
     "concept": "dragonfly_collision_prediction"},
    {"scenario": "Observations come at irregular intervals — sometimes 10ms, sometimes 500ms.",
     "reasoning": "Time-weighted prediction: longer intervals mean more uncertainty. Kalman filter naturally handles this — prediction step scales with elapsed time. Don't assume regular sampling. Real-world sensors are messy.",
     "concept": "dragonfly_irregular_sampling"},
    {"scenario": "Target is underwater and you're tracking it from above.",
     "reasoning": "Light refracts at the water surface — the target appears shifted from its actual position. Correct for Snell's law based on viewing angle and water depth. What you see is not where it is. The model must account for the observation medium.",
     "concept": "dragonfly_refraction"},
]


def get_all_cognitive_data():
    """Return all training data as a flat list with unified format."""
    all_data = []
    for item in ETHICS_DATA:
        all_data.append({"text": item["scenario"], "answer": item["reasoning"],
                          "label": f"ethics_{item['concept']}", "domain": "ethics"})
    for item in COUNTERFACTUAL_DATA:
        all_data.append({"text": f"{item['premise']} {item['counterfactual']}",
                          "answer": item["reasoning"],
                          "label": f"counterfactual_{item['concept']}", "domain": "counterfactual"})
    for item in CAUSAL_DATA:
        all_data.append({"text": f"{item['observation']} {item.get('question', '')}",
                          "answer": item["reasoning"],
                          "label": f"causal_{item['concept']}", "domain": "causal"})
    for item in METACOGNITION_DATA:
        all_data.append({"text": item["prompt"], "answer": item["response"],
                          "label": f"metacog_{item['concept']}", "domain": "metacognition"})
    for item in ANALOGY_DATA:
        all_data.append({"text": item["analogy"], "answer": item["explanation"],
                          "label": f"analogy_{item['concept']}", "domain": "analogy"})
    for item in RCOG_DATA:
        all_data.append({"text": item["problem"], "answer": item["decomposition"],
                          "label": f"rcog_{item['concept']}", "domain": "rcog"})
    for item in COLLECTIVE_DATA:
        all_data.append({"text": item["scenario"], "answer": item["solution"],
                          "label": f"collective_{item['concept']}", "domain": "collective"})
    for item in PORTIA_DATA:
        all_data.append({"text": item["scenario"], "answer": item["decision"],
                          "label": f"portia_{item['concept']}", "domain": "portia"})
    for item in DRAGONFLY_DATA:
        all_data.append({"text": item["scenario"], "answer": item["reasoning"],
                          "label": f"dragonfly_{item['concept']}", "domain": "dragonfly"})
    return all_data


def get_random_cognitive_item(domain=None):
    """Get a random training item, optionally filtered by domain."""
    if domain == "ethics": data = ETHICS_DATA
    elif domain == "counterfactual": data = COUNTERFACTUAL_DATA
    elif domain == "causal": data = CAUSAL_DATA
    elif domain == "metacognition": data = METACOGNITION_DATA
    elif domain == "analogy": data = ANALOGY_DATA
    elif domain == "rcog": data = RCOG_DATA
    elif domain == "collective": data = COLLECTIVE_DATA
    elif domain == "portia": data = PORTIA_DATA
    elif domain == "dragonfly": data = DRAGONFLY_DATA
    else: data = get_all_cognitive_data()
    return random.choice(data) if data else None


# Count
if __name__ == "__main__":
    all_data = get_all_cognitive_data()
    print(f"Total cognitive training items: {len(all_data)}")
    domains = {}
    for item in all_data:
        d = item["domain"]
        domains[d] = domains.get(d, 0) + 1
    for d, c in sorted(domains.items()):
        print(f"  {d}: {c}")
