"""CE-6: Music + rhythm corpus for the audio cortex.

Pure-Python curriculum module that adds *music + rhythm* as a register for the
2M-neuron Athena brain. The deployment has tight disk + storage constraints so
we CANNOT pre-store .wav / .mid / audio files (MB-GB each). Instead, this
module is a **procedural generator**: it synthesizes deterministic
MFCC-style feature frames on demand from named rhythm patterns and hands them
straight into the brain's audio path. No audio data is ever persisted to disk.

Audio path selection (decided per-call at run-time, not at import-time):

    1. **Preferred** — if `brain.audio_cortex_process(samples)` is available,
       we flatten the (frames, n_features) matrix into a 1D float list and
       call that RPC. This is the canonical audio ingest exposed by
       brain_daemon._cmd_audio_cortex_process.
    2. **Fallback** — if `audio_cortex_process` is not present (e.g. lean
       test fixtures, daemons built without the audio cortex wired), we use
       `brain.train_language(description, description)` with a short verbal
       description of the pattern (e.g. "fast steady drum pattern at 120
       BPM"). Less faithful but ensures CE-6 is never a no-op.

After ingest we always probe `brain.produce_text(intent)` to capture how the
brain narrates the rhythm, score the response with `score_audio_response`, and
gate the per-pattern feedback signal:

    composite >= 0.45  →  brain.learn_language(response)        # consolidate
    composite <  0.45  →  brain.train_language(description,     # re-anchor
                                                description)

Stage 1 is **NOT** a no-op — even early Athena should have some rhythm
exposure (rhythm is primal and pre-linguistic). Stage 1 just uses a simpler
4-pattern palette of beats; stage 2 adds clave / waltz / march / shuffle /
rumba; stage 3 adds polyrhythms, syncopation, irregular meter, agogic accents.

Public API:
    RHYTHM_PATTERNS                          dict[int, list[str]]
    generate_rhythm_features(name, *, frames, sample_rate) -> np.ndarray
    generate_melody_description(name, stage) -> str
    score_audio_response(response, expected_keywords) -> dict
    run_music_drip(brain, stage, *, composer, num_patterns, pattern_index,
                   log_every) -> list[dict] | None
    MUSIC_PASS_THRESHOLD                    float = 0.45
"""
from __future__ import annotations

import re
from typing import Iterable

import numpy as np

# ---------------------------------------------------------------------------
# Stage palettes
# ---------------------------------------------------------------------------

# Stage 1 — primal rhythm: simple beats + alternating dynamics + rests.
# Stage 2 — culturally common meters: march / waltz / clave / shuffle / rumba.
# Stage 3 — irregular / non-isochronous: polyrhythm / swing / 5/4 / funk / agogic.
RHYTHM_PATTERNS: dict[int, list[str]] = {
    1: [
        "steady_quarter",
        "steady_eighth",
        "alt_loud_soft",
        "rest_beat",
    ],
    2: [
        "march_4_4",
        "waltz_3_4",
        "clave_son",
        "shuffle_8th",
        "rumba",
    ],
    3: [
        "polyrhythm_3_against_2",
        "swing_8th",
        "5_4_irregular",
        "syncopated_funk",
        "agogic_accent",
    ],
}

# Onset patterns — beat positions in [0.0, 1.0]. Each list represents one
# bar / cycle of the pattern. Values are deterministic and were chosen to
# reflect the canonical onset structure of each style. The features are
# generated by tiling these onsets across `frames` MFCC-like rows.
_ONSET_TABLE: dict[str, list[float]] = {
    # Stage 1 — primal
    "steady_quarter": [0.00, 0.25, 0.50, 0.75],
    "steady_eighth":  [0.00, 0.125, 0.25, 0.375, 0.50, 0.625, 0.75, 0.875],
    "alt_loud_soft":  [0.00, 0.25, 0.50, 0.75],   # accents handled via velocity
    "rest_beat":      [0.00, 0.50],               # half-time / breath

    # Stage 2 — cultural
    "march_4_4":      [0.00, 0.25, 0.50, 0.75],
    "waltz_3_4":      [0.00, 1.0/3.0, 2.0/3.0],
    # Son clave (3-2): hits at 1, 1.5, 2.5, 4, 5 in a 8-beat bar
    "clave_son":      [0.0, 0.1875, 0.375, 0.625, 0.875],
    # Shuffle: long-short triplet feel — long on beats, short on the "ah"
    "shuffle_8th":    [0.00, 0.167, 0.25, 0.417, 0.50, 0.667, 0.75, 0.917],
    # Rumba clave (variant): 1, 1.5, 3, 4.5, 5
    "rumba":          [0.0, 0.1875, 0.375, 0.5625, 0.875],

    # Stage 3 — irregular / syncopated
    # 3-against-2: union of {0, 1/3, 2/3} and {0, 1/2}
    "polyrhythm_3_against_2": [0.0, 1.0/3.0, 0.5, 2.0/3.0],
    # Swing eighths: straight beats + delayed-and-tied off-beats
    "swing_8th":              [0.00, 0.167, 0.25, 0.417, 0.50, 0.667, 0.75, 0.917],
    # 5/4: five beats, accents on 1 and 3
    "5_4_irregular":          [0.0, 0.20, 0.40, 0.60, 0.80],
    # Funk: heavy 1, ghost on the e-and, push on 3, tied 4&
    "syncopated_funk":        [0.00, 0.1875, 0.375, 0.5, 0.625, 0.8125],
    # Agogic accent: shifted long note breaking otherwise-even spacing
    "agogic_accent":          [0.00, 0.20, 0.45, 0.70],  # 4 beats with 1 stretched
}

# Velocity / accent profiles — per-onset emphasis multiplier in [0,1]. Used
# to color the impulse magnitude so e.g. waltz lands a heavy "1" and lighter
# "2 3", march a steady accent on "1" and "3", funk a snap on the "and".
# Default if absent: uniform 1.0.
_ACCENT_TABLE: dict[str, list[float]] = {
    "alt_loud_soft":           [1.0, 0.4, 1.0, 0.4],
    "march_4_4":               [1.0, 0.6, 0.85, 0.6],
    "waltz_3_4":               [1.0, 0.5, 0.5],
    "clave_son":               [1.0, 0.85, 0.85, 0.7, 0.7],
    "rumba":                   [1.0, 0.85, 0.7, 0.85, 0.7],
    "polyrhythm_3_against_2":  [1.0, 0.7, 0.85, 0.7],
    "swing_8th":               [1.0, 0.6, 0.85, 0.6, 1.0, 0.6, 0.85, 0.6],
    "5_4_irregular":           [1.0, 0.5, 0.85, 0.5, 0.5],
    "syncopated_funk":         [1.0, 0.5, 0.85, 0.6, 0.7, 0.55],
    "agogic_accent":           [1.0, 0.6, 0.95, 0.6],
}

# Human-readable description templates per pattern. The keywords here are the
# ones the scoring step will look for in the brain's response.
_DESCRIPTION_TABLE: dict[str, str] = {
    "steady_quarter":          "a steady drum beat at a regular tempo",
    "steady_eighth":           "a fast steady drum pattern with quick beats",
    "alt_loud_soft":           "a beat alternating loud and soft notes",
    "rest_beat":               "a slow drum with rests and breaths between beats",

    "march_4_4":               "a marching drum pattern in four-four time",
    "waltz_3_4":               "a waltz rhythm in three-four time with one strong beat",
    "clave_son":               "a son clave pattern with a syncopated tropical rhythm",
    "shuffle_8th":              "a shuffle eighth-note rhythm with a swung feel",
    "rumba":                    "a rumba clave drum rhythm with off-beat accents",

    "polyrhythm_3_against_2":  "a polyrhythm of three against two cross-pulse",
    "swing_8th":                "a swing eighth-note jazz rhythm with triplet feel",
    "5_4_irregular":            "an irregular five-four time signature with uneven beats",
    "syncopated_funk":          "a syncopated funk drum groove with off-beat accents",
    "agogic_accent":            "a rhythm with an agogic accent and one stretched note",
}

# Default MFCC-like feature dimensionality. 13 is the canonical MFCC count.
DEFAULT_N_FEATURES = 13

# Pass threshold for the scoring → feedback gate.
MUSIC_PASS_THRESHOLD = 0.45


# ---------------------------------------------------------------------------
# Procedural rhythm feature generator
# ---------------------------------------------------------------------------

def _impulse_profile(n_features: int) -> np.ndarray:
    """Spectral envelope of a percussive attack — energy concentrated in
    the low coefficients (a drum hit is broadband but front-loaded in the
    low cepstrum). Values are positive and roughly normalized so the
    profile has unit max."""
    idx = np.arange(n_features, dtype=np.float32)
    # Exponential decay from coef 0; small mid-band bump at coef 3.
    base = np.exp(-idx / 4.0)
    bump = 0.25 * np.exp(-((idx - 3.0) ** 2) / 4.0)
    profile = base + bump
    profile = profile / float(profile.max() + 1e-9)
    return profile.astype(np.float32)


def _background_profile(n_features: int) -> np.ndarray:
    """Quiet inter-onset background — a small flat noise floor with a
    gentle low-coefficient bias (room tone)."""
    idx = np.arange(n_features, dtype=np.float32)
    profile = 0.05 + 0.08 * np.exp(-idx / 8.0)
    return profile.astype(np.float32)


def generate_rhythm_features(pattern_name: str, *,
                              frames: int = 64,
                              sample_rate: int = 22050) -> np.ndarray:
    """Generate a deterministic (frames, n_features) MFCC-like matrix for
    `pattern_name`. The matrix encodes onset positions as energy peaks and
    inter-onset silences as a low-energy background profile.

    `sample_rate` is accepted for API parity with real audio pipelines but
    does not affect the generated values — these are *feature stand-ins*,
    not a synthesized waveform. We never produce raw samples.

    Same `pattern_name` always returns identical features (RNG is seeded
    from the pattern name's hash) so callers can rely on determinism for
    test fixtures and replay.
    """
    if pattern_name not in _ONSET_TABLE:
        raise KeyError(f"unknown rhythm pattern: {pattern_name!r}")

    if frames <= 0:
        raise ValueError("frames must be positive")

    n_features = DEFAULT_N_FEATURES
    onsets = _ONSET_TABLE[pattern_name]
    accents = _ACCENT_TABLE.get(pattern_name, [1.0] * len(onsets))

    # Deterministic RNG keyed on the pattern name. Mask to 32 bits — Python's
    # hash() is 64-bit-signed and numpy seeds want unsigned 32-bit.
    seed = abs(hash(pattern_name)) & 0xFFFFFFFF
    rng = np.random.default_rng(seed)

    impulse = _impulse_profile(n_features)
    background = _background_profile(n_features)

    # Map each onset (in [0,1]) to a frame index in [0, frames-1]. The frame
    # array is then a sum of impulse profiles centered on each onset frame
    # times its accent, plus the background profile, plus a small noise term.
    onset_frames = np.array([int(round(o * (frames - 1))) for o in onsets],
                            dtype=np.int64)
    onset_frames = np.clip(onset_frames, 0, frames - 1)

    # Build per-frame onset-proximity weights (0..1). Each onset contributes
    # a triangular kernel of half-width `support` frames around its center.
    # Wider support → smoother transitions; narrower → sharper attacks.
    support = max(1, frames // 32)
    proximity = np.zeros(frames, dtype=np.float32)
    accent_at_frame = np.zeros(frames, dtype=np.float32)
    for f, vel in zip(onset_frames, accents):
        for k in range(-support, support + 1):
            j = f + k
            if 0 <= j < frames:
                # Triangular falloff in [0, 1].
                w = max(0.0, 1.0 - abs(k) / float(support + 1))
                if w > proximity[j]:
                    proximity[j] = w
                    accent_at_frame[j] = float(vel)

    # Compose the feature matrix. The math:
    #   frame[f] = proximity[f] * accent[f] * impulse + (1-proximity[f]) * background + noise
    # Result: at onsets, frames are dominated by the impulse profile scaled by
    # the accent; between onsets, frames sit at the quiet background floor.
    proximity_2d = proximity[:, None]                  # (frames, 1)
    accent_2d = accent_at_frame[:, None]               # (frames, 1)
    onset_part = proximity_2d * accent_2d * impulse[None, :]
    bg_part = (1.0 - proximity_2d) * background[None, :]
    noise = rng.standard_normal(size=(frames, n_features)).astype(np.float32) * 0.01

    features = onset_part + bg_part + noise
    return features.astype(np.float32)


# ---------------------------------------------------------------------------
# Verbal description (used by the train_language fallback + scoring keywords)
# ---------------------------------------------------------------------------

# Stage modifiers prepended to the base description. Stage 1 keeps it concrete,
# stage 3 admits more abstract metric language.
_STAGE_PREFIX: dict[int, str] = {
    1: "I hear ",
    2: "Listen to ",
    3: "Notice the rhythm in ",
}


def generate_melody_description(pattern_name: str, stage: int) -> str:
    """Return a short human-readable description of the rhythm pattern for
    use as either (a) an intent prompt for produce_text or (b) the textual
    fallback when audio_cortex_process isn't available.

    Always non-empty: unknown patterns degrade to a generic description so
    the drip can still complete a probe rather than crash.
    """
    base = _DESCRIPTION_TABLE.get(pattern_name)
    if not base:
        # Defensive — shouldn't happen because patterns are drawn from
        # RHYTHM_PATTERNS, but cheap insurance.
        base = f"a rhythm pattern called {pattern_name}"
    prefix = _STAGE_PREFIX.get(int(stage), "I hear ")
    return f"{prefix}{base}"


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

# Keep the stop-list small and shared with storytelling so off-topic scoring
# focuses on content words.
_STOPWORDS = frozenset({
    "a", "an", "the", "and", "or", "but", "if", "then", "of", "in", "on",
    "at", "to", "from", "with", "by", "for", "into", "out", "up", "down",
    "is", "are", "was", "were", "be", "been", "being", "am",
    "do", "does", "did", "have", "has", "had", "having",
    "i", "me", "my", "we", "us", "our", "you", "your", "he", "him", "his",
    "she", "her", "it", "its", "they", "them", "their",
    "this", "that", "these", "those", "there", "here",
    "as", "so", "not", "no", "yes",
})


def _tokenize(text: str) -> list[str]:
    if not text:
        return []
    return [m.group(0) for m in re.finditer(r"[A-Za-z']+", text.lower())]


def _content_words(text: str) -> set[str]:
    return {t for t in _tokenize(text) if t not in _STOPWORDS and len(t) > 2}


def _description_keywords(description: str) -> set[str]:
    """Extract the keywords we expect a brain to mention when narrating
    `description` — content words from the description itself, minus the
    stage prefix tokens which are scaffolding rather than rhythm content."""
    return _content_words(description)


def score_audio_response(brain_response_text: str,
                          expected_keywords: Iterable[str]) -> dict:
    """Score `brain_response_text` against `expected_keywords`.

    Composite is the same `(2*recall + specificity) / 3` shape used by CE-1
    audio-adjacent tasks: recall (how many expected keywords made it into
    the response) is weighted twice as heavily as specificity (what fraction
    of the response is on-topic) so a charitable but partly off-topic
    response still passes, but a totally empty / repetitive response fails.

    Returns dict with `recall`, `specificity`, `composite`, `tokens`.
    """
    expected = {w.lower() for w in expected_keywords if w}
    response_tokens = _tokenize(brain_response_text)
    response_set = {t for t in response_tokens if t not in _STOPWORDS}

    if not expected:
        # Charitable degenerate case: no keywords to match against. Flag
        # composite=0 (we can't evaluate) rather than 1 (false-positive).
        return {
            "recall": 0.0,
            "specificity": 0.0,
            "composite": 0.0,
            "tokens": len(response_tokens),
        }

    if not response_tokens:
        return {
            "recall": 0.0,
            "specificity": 0.0,
            "composite": 0.0,
            "tokens": 0,
        }

    hits = sum(1 for w in expected if w in response_set)
    recall = hits / float(len(expected))

    # Specificity: how much of the response is content words (filters out
    # responses that are 95% stop-words). Bounded [0,1].
    if not response_set:
        specificity = 0.0
    else:
        on_topic_in_response = sum(1 for t in response_set if t in expected)
        specificity = on_topic_in_response / float(len(response_set))

    composite = (2.0 * recall + specificity) / 3.0
    return {
        "recall": recall,
        "specificity": specificity,
        "composite": composite,
        "tokens": len(response_tokens),
    }


# ---------------------------------------------------------------------------
# Drip driver
# ---------------------------------------------------------------------------

# Module-level rotation counters per stage. Same NOT-checkpointed semantics
# as storytelling: re-rotating from 0 on resume is acceptable.
_ROTATION_COUNTER: dict[int, int] = {1: 0, 2: 0, 3: 0}


def _bump_rotation(stage: int) -> int:
    cur = _ROTATION_COUNTER.get(int(stage), 0)
    _ROTATION_COUNTER[int(stage)] = cur + 1
    return cur


def _intent_vector(composer, description: str) -> list[float] | None:
    """Compose the description into a 1024-d intent vector for produce_text.
    Falls back to a zero vector if no composer is supplied or composition
    raises. Returns a Python list (the daemon RPC layer prefers lists)."""
    intent = None
    if composer is not None:
        try:
            intent = composer.compose(text=description, modality="text")
        except Exception:
            intent = None

    if intent is None:
        try:
            intent = np.zeros(1024, dtype=np.float32)
        except Exception:
            return None

    try:
        return intent.tolist() if hasattr(intent, "tolist") else list(intent)
    except Exception:
        return None


def _ingest_audio(brain, features: np.ndarray, description: str) -> str:
    """Hand `features` to the brain via whichever audio path is available.

    Returns the path used as a string ("audio_cortex" | "train_language").
    Caller can log this for visibility. Errors are caught + logged at the
    drip level, not here.
    """
    if hasattr(brain, "audio_cortex_process") and callable(
            brain.audio_cortex_process):
        # Flatten (frames, n_features) → 1D float list. The audio cortex
        # treats the stream as a contiguous buffer; for our procedural
        # features that's fine — the temporal structure is preserved by
        # the row-major flattening order.
        samples = features.astype(np.float32).reshape(-1).tolist()
        brain.audio_cortex_process(samples)
        return "audio_cortex"

    # Fallback — verbal stand-in via train_language(description, description).
    try:
        brain.train_language(description, description)
    except TypeError:
        brain.train_language(text=description, target_text=description)
    return "train_language"


def run_music_drip(brain, stage: int, *,
                    composer=None,
                    num_patterns: int = 2,
                    pattern_index: int | None = None,
                    log_every: int = 10,
                    ) -> list[dict] | None:
    """Run a music + rhythm drip for `stage`. Returns a list of per-pattern
    score dicts (length up to `num_patterns`), or None if the stage has no
    patterns or the drip cannot start.

    Stage 1 IS active (4-pattern primal palette). Pattern selection rotates
    deterministically through `RHYTHM_PATTERNS[stage]`; pass `pattern_index`
    to pin a specific pattern (the module rotation counter is then NOT
    advanced — useful for tests + replays).
    """
    patterns = RHYTHM_PATTERNS.get(int(stage), [])
    if not patterns:
        return None

    n = max(1, int(num_patterns))
    results: list[dict] = []

    for i in range(n):
        if pattern_index is not None:
            rot = int(pattern_index) + i
        else:
            rot = _bump_rotation(stage)

        pattern_name = patterns[rot % len(patterns)]
        description = generate_melody_description(pattern_name, stage)
        keywords = _description_keywords(description)

        # Generate features. If the math throws (shouldn't, but cheap
        # insurance) we skip this iteration cleanly.
        try:
            features = generate_rhythm_features(pattern_name)
        except Exception as e:
            print(f"  [Music:s{stage}] feature gen failed for "
                  f"{pattern_name!r}: {e}")
            continue

        # Ingest via the available audio path.
        try:
            ingest_path = _ingest_audio(brain, features, description)
        except Exception as e:
            print(f"  [Music:s{stage}] audio ingest failed: {e}")
            continue

        # Probe — produce_text on the description's intent vector.
        intent = _intent_vector(composer, description)
        if intent is None:
            # Rare — composer + numpy both unavailable. Skip this pattern
            # but keep the drip going for the next ones.
            continue

        try:
            result = brain.produce_text(intent)
        except Exception as e:
            print(f"  [Music:s{stage}] produce_text failed: {e}")
            continue

        produced = (result or {}).get("text", "") if isinstance(result, dict) else ""
        confidence = (result or {}).get("confidence", 0.0) if isinstance(result, dict) else 0.0

        score = score_audio_response(produced, keywords)

        # Feedback gate — same shape as CE-1.
        try:
            if score["composite"] >= MUSIC_PASS_THRESHOLD and produced.strip():
                brain.learn_language(produced)
            else:
                try:
                    brain.train_language(description, description)
                except TypeError:
                    brain.train_language(text=description, target_text=description)
        except Exception as e:
            print(f"  [Music:s{stage}] feedback signal failed: {e}")

        if int(rot) % max(1, int(log_every)) == 0:
            print(f"  [Music:s{stage}] {pattern_name} composite={score['composite']:.2f} "
                  f"recall={score['recall']:.2f} spec={score['specificity']:.2f} "
                  f"tok={score['tokens']} conf={confidence:.2f} "
                  f"path={ingest_path}")

        results.append({
            "stage": int(stage),
            "rotation": int(rot),
            "pattern": pattern_name,
            "description": description,
            "produced": produced,
            "confidence": float(confidence),
            "ingest_path": ingest_path,
            **score,
        })

    return results
