/**
 * @file nimcp_fep_orchestrator_internal.h
 * @brief Internal shared declarations for nimcp_fep_orchestrator SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_FEP_ORCHESTRATOR_INTERNAL_H
#define NIMCP_FEP_ORCHESTRATOR_INTERNAL_H

#include "cognitive/free_energy/nimcp_fep_orchestrator.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "core/brain/nimcp_brain_internal.h"
#include "cognitive/knowledge/nimcp_kg_reader.h"
#include "utils/error/nimcp_error_codes.h"
#include "utils/platform/nimcp_platform_time.h"
#include "api/nimcp_api_exception.h"
#include <string.h>
#include <math.h>
#include <stdio.h>
#include "utils/bridge/nimcp_bridge_boilerplate.h"
#include "mesh/nimcp_mesh_participant.h"
#include "mesh/nimcp_mesh_adapter.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- io module --- */
/* fep_orchestrator_get_load - defined in nimcp_fep_orchestrator_io.c */
/* fep_orchestrator_get_state - defined in nimcp_fep_orchestrator_io.c */
/* fep_bridge_category_to_string - defined in nimcp_fep_orchestrator_io.c */
/* fep_orchestrator_state_to_string - defined in nimcp_fep_orchestrator_io.c */
/* fep_orchestrator_query_self_knowledge - defined in nimcp_fep_orchestrator_io.c */
/* fep_orchestrator_set_instance_health_agent - defined in nimcp_fep_orchestrator_io.c */
/* fep_orchestrator_training_begin - defined in nimcp_fep_orchestrator_io.c */
/* fep_orchestrator_training_end - defined in nimcp_fep_orchestrator_io.c */
/* fep_orchestrator_training_step - defined in nimcp_fep_orchestrator_io.c */

/* --- lifecycle module --- */
/* fep_orchestrator_create - defined in nimcp_fep_orchestrator_lifecycle.c */
/* fep_orchestrator_destroy - defined in nimcp_fep_orchestrator_lifecycle.c */
/* fep_orchestrator_start - defined in nimcp_fep_orchestrator_lifecycle.c */
/* fep_orchestrator_stop - defined in nimcp_fep_orchestrator_lifecycle.c */
/* fep_orchestrator_reset_stats - defined in nimcp_fep_orchestrator_lifecycle.c */
/* fep_orchestrator_default_config - defined in nimcp_fep_orchestrator_lifecycle.c */
/* fep_orchestrator_pause - defined in nimcp_fep_orchestrator_lifecycle.c */
/* fep_orchestrator_resume - defined in nimcp_fep_orchestrator_lifecycle.c */
/* fep_orchestrator_register_bridge - defined in nimcp_fep_orchestrator_lifecycle.c */
/* fep_orchestrator_unregister_bridge - defined in nimcp_fep_orchestrator_lifecycle.c */

/* --- stats module --- */
/* fep_orchestrator_get_stats - defined in nimcp_fep_orchestrator_stats.c */
/* fep_orchestrator_disconnect_internal_kg - defined in nimcp_fep_orchestrator_stats.c */
/* fep_orchestrator_get_bridges_for_module - defined in nimcp_fep_orchestrator_stats.c */
/* fep_orchestrator_get_topology_summary - defined in nimcp_fep_orchestrator_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_FEP_ORCHESTRATOR_INTERNAL_H */
