/**
 * @file nimcp_global_workspace_internal.h
 * @brief Internal shared declarations for nimcp_global_workspace SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_GLOBAL_WORKSPACE_INTERNAL_H
#define NIMCP_GLOBAL_WORKSPACE_INTERNAL_H

#include "cognitive/global_workspace/nimcp_global_workspace.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "constants/nimcp_buffer_constants.h"
#include "security/nimcp_security.h"
#include "security/nimcp_blood_brain_barrier.h"
#include "cognitive/knowledge/nimcp_kg_reader.h"
#include "utils/memory/nimcp_unified_memory.h"
#include "utils/memory/nimcp_memory_pool.h"
#include "utils/platform/nimcp_platform_mutex.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <time.h>
#include <assert.h>
#include "nimcp.h"  // For error codes
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_messages.h"
#include "async/nimcp_wiring_helpers.h"
#include "async/nimcp_bio_router.h"
#include "cognitive/global_workspace/nimcp_gw_snn_bridge.h"
#include "cognitive/global_workspace/nimcp_gw_plasticity_bridge.h"
#include "utils/bridge/nimcp_bridge_boilerplate.h"
#include "mesh/nimcp_mesh_participant.h"
#include "mesh/nimcp_mesh_adapter.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

//=============================================================================
// Internal Structures
//=============================================================================

/**
 * @brief Global workspace implementation (opaque)
 *
 * WHAT: Internal representation of workspace
 * WHY:  Encapsulation - users see only opaque pointer
 * HOW:  Struct contains all state and buffers
 */
struct global_workspace_struct {
    // Configuration (immutable after creation)
    global_workspace_config_t config;

    // Thread safety mutex for public API operations
    nimcp_platform_mutex_t mutex;           /**< Protects all mutable state */

    // Current broadcast state
    workspace_broadcast_t current_broadcast;
    float* broadcast_content;            /**< Content buffer [capacity_dim] */

    // Competition pool
    competitor_entry_t competitors[GLOBAL_WORKSPACE_MAX_COMPETITORS];
    uint32_t num_active_competitors;

    // Subscribers
    cognitive_module_t subscribers[GLOBAL_WORKSPACE_MAX_SUBSCRIBERS];
    uint32_t num_subscribers;

    // Broadcast history (circular buffer)
    workspace_broadcast_t* history;      /**< [history_depth] */
    float** history_content;             /**< [history_depth][capacity_dim] */
    uint32_t history_head;               /**< Circular buffer index */
    uint32_t history_count;              /**< How many in history */

    // Statistics
    workspace_statistics_t stats;

    // Timing state
    uint64_t last_broadcast_time_ms;
    uint64_t pool_activation_time_ms;  /**< When pool went from empty to non-empty */
    uint32_t next_broadcast_id;

    // Round-robin state (for ROUND_ROBIN strategy)
    uint32_t last_winner_idx;

    // Phase 1.5: Memory pools for hot-path allocations
    memory_pool_t broadcast_content_pool;   /**< Pool for broadcast content buffers */
    memory_pool_t history_content_pool;     /**< Pool for history content buffers */

    // Bio-async integration
    bio_module_context_t bio_ctx;           /**< Bio-async module context */
    bool bio_async_enabled;                 /**< Bio-async registration status */

    // SNN and Plasticity bridge integration
    gw_snn_bridge_t* snn_bridge;            /**< SNN bridge for spike-based processing */
    gw_plasticity_bridge_t* plasticity_bridge; /**< Plasticity bridge for learning */
    bool bridges_enabled;                   /**< Bridge integration status */
};

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- access module --- */
/* global_workspace_create - defined in nimcp_global_workspace_access.c */
/* global_workspace_create_custom - defined in nimcp_global_workspace_access.c */
/* global_workspace_destroy - defined in nimcp_global_workspace_access.c */
/* global_workspace_submit - defined in nimcp_global_workspace_access.c */
/* global_workspace_resolve - defined in nimcp_global_workspace_access.c */
/* global_workspace_subscribe - defined in nimcp_global_workspace_access.c */
/* global_workspace_unsubscribe - defined in nimcp_global_workspace_access.c */
/* global_workspace_get_subscriber_count - defined in nimcp_global_workspace_access.c */
/* global_workspace_get_history - defined in nimcp_global_workspace_access.c */
/* global_workspace_get_statistics - defined in nimcp_global_workspace_access.c */
/* global_workspace_reset_statistics - defined in nimcp_global_workspace_access.c */
/* global_workspace_print_state - defined in nimcp_global_workspace_access.c */
/* global_workspace_default_config - defined in nimcp_global_workspace_access.c */
/* global_workspace_set_ignition_threshold - defined in nimcp_global_workspace_access.c */
/* global_workspace_get_ignition_threshold - defined in nimcp_global_workspace_access.c */
/* global_workspace_set_module_priority - defined in nimcp_global_workspace_access.c */
/* global_workspace_validate_config - defined in nimcp_global_workspace_access.c */
/* global_workspace_query_self_knowledge - defined in nimcp_global_workspace_access.c */
/* global_workspace_get_capabilities - defined in nimcp_global_workspace_access.c */
/* global_workspace_get_integrations - defined in nimcp_global_workspace_access.c */
/* global_workspace_set_instance_health_agent - defined in nimcp_global_workspace_access.c */
/* global_workspace_training_begin - defined in nimcp_global_workspace_access.c */
/* global_workspace_training_end - defined in nimcp_global_workspace_access.c */
/* global_workspace_training_step - defined in nimcp_global_workspace_access.c */
/* cognitive_module_to_string - defined in nimcp_global_workspace_access.c */
/* competition_strategy_to_string - defined in nimcp_global_workspace_access.c */

/* --- broadcast module --- */
/* global_workspace_read_broadcast - defined in nimcp_global_workspace_broadcast.c */
/* global_workspace_has_broadcast - defined in nimcp_global_workspace_broadcast.c */
/* global_workspace_get_broadcast_source - defined in nimcp_global_workspace_broadcast.c */
/* global_workspace_get_broadcast_strength - defined in nimcp_global_workspace_broadcast.c */
/* global_workspace_time_since_broadcast - defined in nimcp_global_workspace_broadcast.c */
/* global_workspace_query_broadcast_targets - defined in nimcp_global_workspace_broadcast.c */

/* --- competition module --- */
/* global_workspace_compete - defined in nimcp_global_workspace_competition.c */
/* global_workspace_get_competitor_count - defined in nimcp_global_workspace_competition.c */
/* global_workspace_is_competing - defined in nimcp_global_workspace_competition.c */
/* global_workspace_query_competition_knowledge - defined in nimcp_global_workspace_competition.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_GLOBAL_WORKSPACE_INTERNAL_H */
