/**
 * @file nimcp_brain_training_integration_internal.h
 * @brief Internal shared declarations for nimcp_brain_training_integration SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_BRAIN_TRAINING_INTEGRATION_INTERNAL_H
#define NIMCP_BRAIN_TRAINING_INTEGRATION_INTERNAL_H

#include "middleware/training/nimcp_brain_training_integration.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include "security/nimcp_security.h"
#include "security/nimcp_blood_brain_barrier.h"
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_router.h"
#include "async/nimcp_bio_messages.h"
#include "middleware/training/nimcp_training_plasticity_bridge.h"
#include "plasticity/nimcp_second_messengers.h"
#include "utils/time/nimcp_time.h"
#include "utils/platform/nimcp_platform_tier.h"
#include "portia/nimcp_portia.h"
#include "api/nimcp_api_exception.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <float.h>
#include <time.h>
#include <stddef.h>  /* for NULL */
#include "utils/fault_tolerance/nimcp_health_agent_macros.h"
#include "constants/nimcp_dimension_constants.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

 * Internal Structures
 * ============================================================================ */

/**
 * @brief Loss context slot
 */
typedef struct {
    nimcp_loss_context_t* ctx;
    uint32_t id;
    bool active;
} loss_slot_t;

/**
 * @brief Optimizer context slot
 */
typedef struct {
    nimcp_optimizer_context_t* ctx;
    uint32_t id;
    bool active;
} optimizer_slot_t;

/**
 * @brief LR Scheduler context slot
 */
typedef struct {
    nimcp_lr_scheduler_ctx_t* ctx;
    uint32_t id;
    bool active;
} scheduler_slot_t;

/**
 * @brief Gradient manager context slot
 */
typedef struct {
    nimcp_gradient_manager_ctx_t* ctx;
    uint32_t id;
    bool active;
} gradmgr_slot_t;

/**
 * @brief Brain-Training integration context
 */
struct nimcp_brain_training_ctx {
    /* Configuration */
    nimcp_brain_training_config_t config;

    /* Security integration */
    nimcp_sec_integration_t* security_ctx;
    uint32_t loss_module_id;
    uint32_t optimizer_module_id;
    uint32_t scheduler_module_id;
    uint32_t gradmgr_module_id;
    bool security_registered;

    /* Memory manager */
    unified_mem_manager_t memory_mgr;

    /* Loss function contexts */
    loss_slot_t loss_slots[NIMCP_TRAINING_MAX_LOSS_CONTEXTS];
    uint32_t loss_count;
    uint32_t next_loss_id;

    /* Optimizer contexts */
    optimizer_slot_t optimizer_slots[NIMCP_TRAINING_MAX_OPTIMIZER_CONTEXTS];
    uint32_t optimizer_count;
    uint32_t next_optimizer_id;

    /* LR Scheduler contexts */
    scheduler_slot_t scheduler_slots[NIMCP_TRAINING_MAX_SCHEDULER_CONTEXTS];
    uint32_t scheduler_count;
    uint32_t next_scheduler_id;

    /* Gradient manager contexts */
    gradmgr_slot_t gradmgr_slots[NIMCP_TRAINING_MAX_GRADMGR_CONTEXTS];
    uint32_t gradmgr_count;
    uint32_t next_gradmgr_id;

    /* Training state */
    nimcp_training_mode_t mode;
    uint64_t current_epoch;
    uint64_t current_batch;

    /* Statistics */
    nimcp_training_session_stats_t stats;

    /* Event callback */
    nimcp_training_event_callback_t event_callback;
    void* callback_user_data;

    /* Convergence/divergence tracking */
    float last_loss;
    uint32_t stable_loss_count;
    bool converged;
    bool diverged;

    /* Early stopping state */
    float best_loss;
    uint32_t early_stop_wait;
    bool early_stopped;

    /* Random state for dropout */
    uint32_t dropout_seed;

    /* Plasticity Bridge integration (Phase TPB-1) */
    tpb_context_t* plasticity_bridge;
    float biological_modulation_strength;
    float prev_loss;          /* For RPE computation */
    float cumulative_da;      /* For avg dopamine tracking */
    float cumulative_lr_mod;  /* For avg LR modulation tracking */
    uint64_t bio_update_count;

    /* Training Callbacks integration (Phase TCB-1) */
    tcb_context_t* callbacks;

    /* Bio-async integration */
    bio_module_context_t bio_ctx;
    bool bio_async_enabled;

    /* Second Messenger Cascade integration */
    second_messenger_system_t* second_messengers;
    bool second_messengers_enabled;

    /* Portia Resource Management integration */
    void* portia_context;              /* portia_context_t* - opaque to avoid circular dep */
    platform_tier_t current_tier;
    bool resource_aware_training;
    float tier_batch_size_multiplier;
    float tier_lr_multiplier;
    bool training_paused;
    uint32_t degradation_level;
};

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- data module --- */
/* nimcp_brain_training_get_adjusted_batch_size - defined in nimcp_brain_training_integration_data.c */
/* nimcp_brain_training_on_tier_change - defined in nimcp_brain_training_integration_data.c */
/* nimcp_brain_training_on_degradation_event - defined in nimcp_brain_training_integration_data.c */
/* nimcp_brain_training_is_paused - defined in nimcp_brain_training_integration_data.c */
/* nimcp_brain_training_resume - defined in nimcp_brain_training_integration_data.c */
/* nimcp_brain_training_get_adjusted_lr - defined in nimcp_brain_training_integration_data.c */
/* nimcp_brain_training_request_resources - defined in nimcp_brain_training_integration_data.c */

/* --- lifecycle module --- */
/* nimcp_brain_training_create - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_init - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_destroy - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_create_loss - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_destroy_loss - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_create_optimizer - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_destroy_optimizer - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_reset_stats - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_create_gradient_manager - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_destroy_gradient_manager - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_check_early_stop - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_reset_early_stop - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_create_callbacks - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_training_event_type_name - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_training_mode_name - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_default_config - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_validate_config - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_register_security - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_unregister_security - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_is_security_registered - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_get_security_ids - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_get_loss - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_get_optimizer - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_set_mode - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_get_mode - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_compute_loss - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_get_gradient_manager - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_accumulate_gradients - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_gradients_ready - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_get_accumulated_gradients - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_apply_regularization - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_clip_gradients - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_apply_dropout - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_get_callbacks - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_connect_second_messengers - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_get_cascade_modulation - defined in nimcp_brain_training_integration_lifecycle.c */
/* nimcp_brain_training_connect_portia - defined in nimcp_brain_training_integration_lifecycle.c */

/* --- pipeline module --- */
/* nimcp_brain_training_step - defined in nimcp_brain_training_integration_pipeline.c */
/* nimcp_brain_training_step_scheduler - defined in nimcp_brain_training_integration_pipeline.c */
/* nimcp_brain_training_step_scheduler_metric - defined in nimcp_brain_training_integration_pipeline.c */
/* nimcp_brain_training_step_full - defined in nimcp_brain_training_integration_pipeline.c */
/* nimcp_brain_training_step_biological - defined in nimcp_brain_training_integration_pipeline.c */
/* nimcp_brain_training_optimize - defined in nimcp_brain_training_integration_pipeline.c */
/* nimcp_brain_training_connect_plasticity_bridge - defined in nimcp_brain_training_integration_pipeline.c */
/* nimcp_brain_training_get_plasticity_bridge - defined in nimcp_brain_training_integration_pipeline.c */
/* nimcp_brain_training_set_biological_modulation - defined in nimcp_brain_training_integration_pipeline.c */
/* nimcp_brain_training_get_biological_modulation - defined in nimcp_brain_training_integration_pipeline.c */

/* --- schedule module --- */
/* nimcp_brain_training_create_scheduler - defined in nimcp_brain_training_integration_schedule.c */
/* nimcp_brain_training_get_scheduler - defined in nimcp_brain_training_integration_schedule.c */
/* nimcp_brain_training_destroy_scheduler - defined in nimcp_brain_training_integration_schedule.c */
/* nimcp_brain_training_is_converged - defined in nimcp_brain_training_integration_schedule.c */
/* nimcp_brain_training_is_diverged - defined in nimcp_brain_training_integration_schedule.c */

/* --- stats module --- */
/* nimcp_brain_training_get_stats - defined in nimcp_brain_training_integration_stats.c */
/* nimcp_brain_training_update_stats - defined in nimcp_brain_training_integration_stats.c */
/* nimcp_brain_training_emit_event - defined in nimcp_brain_training_integration_stats.c */
/* nimcp_brain_training_register_callback - defined in nimcp_brain_training_integration_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_BRAIN_TRAINING_INTEGRATION_INTERNAL_H */
