/**
 * @file nimcp_logging_internal.h
 * @brief Internal shared declarations for nimcp_logging SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_LOGGING_INTERNAL_H
#define NIMCP_LOGGING_INTERNAL_H

#include "utils/logging/nimcp_logging.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include <stddef.h>  /* for NULL */
#include "security/nimcp_security.h"
#include "security/nimcp_blood_brain_barrier.h"
#include "async/nimcp_bio_async.h"
#include "async/nimcp_bio_messages.h"
#include "utils/platform/nimcp_platform_mutex.h"
#include "utils/platform/nimcp_platform_cond.h"
#include "utils/platform/nimcp_platform_thread.h"
#include "utils/platform/nimcp_platform_time.h"
#include "utils/platform/nimcp_platform_once.h"
#include "utils/thread/nimcp_atomic.h"
#include <errno.h>
#include <libgen.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>  // For strcasecmp
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>
#include <sys/syscall.h>
#include <syslog.h>
#include "utils/fault_tolerance/nimcp_health_agent_macros.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

// Unified memory forward declarations
typedef struct {
    size_t size;
    const void* initial_data;
    int strategy;
    bool enable_cow;
    size_t alignment;
} unified_mem_request_t;

//=============================================================================
// Internal Structures
//=============================================================================

/**
 * @brief Module filter entry
 */
typedef struct {
    char module[NIMCP_LOG_MAX_MODULE_LEN];
    log_level_t level;
    bool enabled;
} log_module_filter_t;

/**
 * @brief Rate limiter state (token bucket)
 */
typedef struct {
    nimcp_atomic_uint64_t tokens;
    nimcp_atomic_uint64_t last_refill_time_ns;
    uint32_t max_tokens;
    uint32_t refill_rate;  // tokens per second
    bool enabled;
} log_rate_limiter_t;

/**
 * @brief Ring buffer for async logging
 */
typedef struct {
    nimcp_log_entry_t* entries;
    size_t capacity;
    nimcp_atomic_uint64_t write_pos;
    nimcp_atomic_uint64_t read_pos;
    nimcp_atomic_uint64_t drop_count;
} log_ring_buffer_t;

/**
 * @brief Allocation header for unified memory tracking
 */
typedef struct {
    unified_mem_handle_t handle;
    size_t size;
} log_alloc_header_t;

/**
 * @brief Logger instance structure
 */
struct nimcp_logger_struct {
    uint32_t magic;                     /**< Magic for validation */

    // Configuration
    log_level_t level;
    uint32_t destinations;
    nimcp_log_format_t format;
    nimcp_log_async_mode_t async_mode;
    nimcp_log_color_mode_t color_mode;
    bool include_source_location;

    // File output
    FILE* file;
    char file_path[PATH_MAX];
    nimcp_platform_mutex_t file_mutex;

    // Rotation
    nimcp_log_rotation_config_t rotation;
    size_t current_file_size;
    time_t last_rotation_time;

    // Rate limiting
    log_rate_limiter_t rate_limiter;

    // Module filtering
    log_module_filter_t module_filters[MAX_MODULE_FILTERS];
    size_t module_filter_count;
    nimcp_platform_mutex_t filter_mutex;

    // Callbacks
    nimcp_log_output_callback_t callback;
    void* callback_user_data;
    nimcp_log_filter_t filter;
    void* filter_user_data;

    // Async components
    log_ring_buffer_t ring_buffer;
    nimcp_platform_thread_t writer_thread;
    nimcp_platform_mutex_t async_mutex;
    nimcp_platform_cond_t async_cond;
    nimcp_atomic_bool_t async_running;
    uint32_t flush_interval_ms;

    // Statistics
    nimcp_atomic_uint64_t messages_logged;
    nimcp_atomic_uint64_t messages_dropped;
    nimcp_atomic_uint64_t messages_filtered;
    nimcp_atomic_uint64_t level_counts[LOG_LEVEL_COUNT];
    nimcp_atomic_uint64_t async_writes;
    nimcp_atomic_uint64_t sync_writes;
    nimcp_atomic_uint64_t buffer_overflows;
    nimcp_atomic_uint64_t flush_operations;
    nimcp_atomic_uint64_t rotations_performed;
    nimcp_atomic_uint64_t bytes_written;
    nimcp_atomic_uint64_t rate_limit_hits;
    nimcp_atomic_uint64_t total_log_time_ns;
    nimcp_atomic_uint64_t max_log_time_ns;
    nimcp_atomic_uint32_t sequence;
    uint64_t start_time_ns;

    // Integration
    unified_mem_manager_t memory_mgr;
    nimcp_sec_integration_t* security_ctx;
    uint32_t security_module_id;

    // Context (thread-local simulation via mutex)
    nimcp_platform_mutex_t context_mutex;
    char current_context[NIMCP_LOG_MAX_CONTEXT_LEN];

    // Syslog
    bool syslog_opened;
};

/**
 * @brief Log context structure
 */
struct nimcp_log_context_struct {
    nimcp_logger_t logger;
    char context_id[NIMCP_LOG_MAX_CONTEXT_LEN];
    char previous_context[NIMCP_LOG_MAX_CONTEXT_LEN];
};

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- buffer module --- */
/* nimcp_log_flush - defined in nimcp_logging_buffer.c */

/* --- filter module --- */
/* nimcp_log_set_level - defined in nimcp_logging_filter.c */
/* nimcp_log_get_level - defined in nimcp_logging_filter.c */
/* nimcp_log_is_level_enabled - defined in nimcp_logging_filter.c */
/* nimcp_log_set_filter - defined in nimcp_logging_filter.c */
/* nimcp_log_clear_module_filters - defined in nimcp_logging_filter.c */
/* nimcp_log_level_name - defined in nimcp_logging_filter.c */
/* nimcp_log_level_from_string - defined in nimcp_logging_filter.c */
/* nimcp_log_entry - defined in nimcp_logging_filter.c */
/* nimcp_log_set_callback - defined in nimcp_logging_filter.c */
/* nimcp_log_enable_module - defined in nimcp_logging_filter.c */
/* nimcp_log_disable_module - defined in nimcp_logging_filter.c */
/* nimcp_log_get_security_id - defined in nimcp_logging_filter.c */

/* --- lifecycle module --- */
/* nimcp_log_create - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_destroy - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_is_initialized - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_init - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_shutdown - defined in nimcp_logging_lifecycle.c */
/* log_init - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_context_create - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_context_destroy - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_reset_rate_limit - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_reset_stats - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_default_config - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_get_global - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_set_global - defined in nimcp_logging_lifecycle.c */
/* log_message - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_get_context_id - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_set_context_id - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_rotate - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_set_rotation - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_get_file_path - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_set_file_path - defined in nimcp_logging_lifecycle.c */
/* nimcp_log_set_rate_limit - defined in nimcp_logging_lifecycle.c */

/* --- output module --- */
/* nimcp_log_write - defined in nimcp_logging_output.c */
/* nimcp_log_writev - defined in nimcp_logging_output.c */
/* nimcp_log_set_format - defined in nimcp_logging_output.c */
/* nimcp_log_format_name - defined in nimcp_logging_output.c */
/* log_close - defined in nimcp_logging_output.c */
/* nimcp_log - defined in nimcp_logging_output.c */
/* nimcp_log_set_destinations - defined in nimcp_logging_output.c */
/* nimcp_log_set_color_mode - defined in nimcp_logging_output.c */
/* nimcp_log_is_tty - defined in nimcp_logging_output.c */

/* --- stats module --- */
/* nimcp_log_get_stats - defined in nimcp_logging_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_LOGGING_INTERNAL_H */
