/**
 * @file nimcp_language_orchestrator_internal.h
 * @brief Internal shared declarations for nimcp_language_orchestrator SRP split
 * @date 2026-02-16
 *
 * Auto-generated by tools/srp_splitter.py
 * This header is shared between all split implementation files.
 */

#ifndef NIMCP_LANGUAGE_ORCHESTRATOR_INTERNAL_H
#define NIMCP_LANGUAGE_ORCHESTRATOR_INTERNAL_H

#include "language/nimcp_language_orchestrator.h"
#include "utils/memory/nimcp_memory.h"
#include "utils/logging/nimcp_logging.h"
#include "utils/exception/nimcp_exception_macros.h"

#include <stddef.h>  /* for NULL */
#include "language/nimcp_language_bio_async.h"
#include "language/bridges/nimcp_language_perception_bridge.h"
#include "language/bridges/nimcp_language_cognitive_bridge.h"
#include "language/bridges/nimcp_language_training_bridge.h"
#include "language/bridges/nimcp_language_omni_bridge.h"
#include "language/bridges/nimcp_language_immune_bridge.h"
#include "language/bridges/nimcp_language_gpu_bridge.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "utils/fault_tolerance/nimcp_health_agent_macros.h"
#include "constants/nimcp_timing_constants.h"


/* ============================================================================
 * Internal Struct Definitions (moved from .c for SRP split access)
 * ============================================================================ */

//=============================================================================
// Internal Structures
//=============================================================================

/**
 * @brief Callback registration entry
 */
typedef struct {
    language_event_callback_t callback;
    void* user_data;
    bool active;
} callback_entry_t;

/**
 * @brief Pending input buffer
 */
typedef struct {
    language_phoneme_t* phonemes;
    uint32_t phoneme_count;
    uint32_t phoneme_capacity;

    language_word_t* words;
    uint32_t word_count;
    uint32_t word_capacity;

    char* text_buffer;
    uint32_t text_length;
    uint32_t text_capacity;
} input_buffer_t;

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Forward Declarations for Split Modules
 * ============================================================================ */

/* --- integration module --- */
/* language_orchestrator_connect_wernicke - defined in nimcp_language_orchestrator_integration.c */
/* language_orchestrator_connect_broca - defined in nimcp_language_orchestrator_integration.c */
/* language_orchestrator_connect_nlp - defined in nimcp_language_orchestrator_integration.c */
/* language_orchestrator_connect_speech_cortex - defined in nimcp_language_orchestrator_integration.c */
/* language_orchestrator_connect_multimodal - defined in nimcp_language_orchestrator_integration.c */
/* language_orchestrator_connect_perception_bridge - defined in nimcp_language_orchestrator_integration.c */
/* language_orchestrator_connect_cognitive_bridge - defined in nimcp_language_orchestrator_integration.c */
/* language_orchestrator_connect_training_bridge - defined in nimcp_language_orchestrator_integration.c */
/* language_orchestrator_connect_omni_bridge - defined in nimcp_language_orchestrator_integration.c */
/* language_orchestrator_connect_immune_bridge - defined in nimcp_language_orchestrator_integration.c */
/* language_orchestrator_connect_gpu_bridge - defined in nimcp_language_orchestrator_integration.c */
/* language_orchestrator_is_running - defined in nimcp_language_orchestrator_integration.c */
/* language_state_to_string - defined in nimcp_language_orchestrator_integration.c */
/* language_mode_to_string - defined in nimcp_language_orchestrator_integration.c */
/* language_input_type_to_string - defined in nimcp_language_orchestrator_integration.c */
/* language_output_type_to_string - defined in nimcp_language_orchestrator_integration.c */
/* phoneme_category_to_string - defined in nimcp_language_orchestrator_integration.c */
/* part_of_speech_to_string - defined in nimcp_language_orchestrator_integration.c */
/* thematic_role_to_string - defined in nimcp_language_orchestrator_integration.c */
/* phrase_type_to_string - defined in nimcp_language_orchestrator_integration.c */

/* --- lifecycle module --- */
/* language_orchestrator_create - defined in nimcp_language_orchestrator_lifecycle.c */
/* language_orchestrator_destroy - defined in nimcp_language_orchestrator_lifecycle.c */
/* language_orchestrator_start - defined in nimcp_language_orchestrator_lifecycle.c */
/* language_orchestrator_stop - defined in nimcp_language_orchestrator_lifecycle.c */
/* language_orchestrator_reset - defined in nimcp_language_orchestrator_lifecycle.c */
/* language_orchestrator_reset_stats - defined in nimcp_language_orchestrator_lifecycle.c */
/* language_comprehension_result_free - defined in nimcp_language_orchestrator_lifecycle.c */
/* language_production_plan_free - defined in nimcp_language_orchestrator_lifecycle.c */
/* language_orchestrator_default_config - defined in nimcp_language_orchestrator_lifecycle.c */
/* language_orchestrator_get_mode - defined in nimcp_language_orchestrator_lifecycle.c */
/* language_orchestrator_set_mode - defined in nimcp_language_orchestrator_lifecycle.c */
/* language_orchestrator_register_callback - defined in nimcp_language_orchestrator_lifecycle.c */
/* language_orchestrator_unregister_callback - defined in nimcp_language_orchestrator_lifecycle.c */

/* --- pipeline module --- */
/* language_orchestrator_process_input - defined in nimcp_language_orchestrator_pipeline.c */
/* language_orchestrator_process_phonemes - defined in nimcp_language_orchestrator_pipeline.c */
/* language_orchestrator_process_text - defined in nimcp_language_orchestrator_pipeline.c */
/* language_orchestrator_process_messages - defined in nimcp_language_orchestrator_pipeline.c */
/* language_orchestrator_generate_output - defined in nimcp_language_orchestrator_pipeline.c */
/* language_orchestrator_get_comprehension - defined in nimcp_language_orchestrator_pipeline.c */
/* language_orchestrator_get_production_plan - defined in nimcp_language_orchestrator_pipeline.c */
/* language_orchestrator_update - defined in nimcp_language_orchestrator_pipeline.c */
/* language_orchestrator_get_state - defined in nimcp_language_orchestrator_pipeline.c */

/* --- stats module --- */
/* language_orchestrator_get_stats - defined in nimcp_language_orchestrator_stats.c */


#ifdef __cplusplus
}
#endif

#endif /* NIMCP_LANGUAGE_ORCHESTRATOR_INTERNAL_H */
